__d("widget.shortcut1.shortcut1","common.js.widget,common.js.browser,common.js.format,common.js.profile,common.js.cookie,common.js.config,common.js.animation,common.js.pageEvents".split(","),function(s,u,n,e){e("common.js.widget");var b=e("common.js.browser"),c=e("common.js.format"),d=e("common.js.profile"),f=e("common.js.cookie");e("common.js.config");var p=e("common.js.animation"),h=e("common.js.pageEvents"),a,i=!1,k=!1,j=70;6==b.ie&&(j=10);$.widget("hao123.shortcut1",{options:{tip:"",title:"",
tpl:'<a monkey="righttip" href="#{url}" target="_bank" class="tip"><img width=120 height=110 src="#{img}"/></a>',shoppingMap:["-71 10","-159 10","-247 10","-335 10"],lifeMap:["-71 -27","-159 -27","-247 -27","-335 -27"],relaxMap:["-72 -67","-160 -67","-248 -67"],gobottomMap:["-73 -136","-161 -136","-249 -136"],gotopMap:["-73 -103","-161 -103","-249 -103"],gameMap:["-71 -167","-159 -167","-247 -167"],videoMap:["-71 -199","-159 -199","-247 -199","-335 -199","-407 -199"]},_init:function(){a=this;a.hidden=
!1;a.shortcut=$("#shortcut-box");a.goshop=$("#shortcut-shop");a.golife=$("#shortcut-life");a.gorelax=$("#shortcut-relax");a.gogame=$("#shortcut-game");a.govideo=$("#shortcut-video");a.toptoggle=$("#shortcut-toptoggle");a.newindex=$("#shortcut-indexnew");a.goerwei=$("#shortcut-goerwei");a.goerweiclz=$("#shortcut-goerwei .clz");a.qrnotshow=f.has("qr_notshow");a.shortcutImage=$("#shortcut-image");h.on("viewport.deferchange",a._onscroll);h.on("navigate.tabchange",a._ontabchange);h.on("viewport.change",
a._onchange);a.toptoggle.click(a._ontoptoggle);a.goshop.click(a._ongoshop);a.gorelax.click(a._ongorelax);a.golife.click(a.ongolife);a.gogame.click(a._ongogame);a.govideo.click(a._ongovideo);a.attop=a._isAtTop();a.goerweiclz.click(a._hideQrCode);6!=b.ie&&a._showOrHideGoErwei();$(document).on("toppicturehijackclick",function(){a._ongoshop()});var q=d.get("navigate");a._setNavShow(q);a._showNav();a._initHoverAnimation();a._onscroll();a._triggerNewYear()},_triggerNewYear:function(){var a=window.location.search.match(/\?goto=([^<>&]+)/),
b=this,c="";a&&a[1]&&(c=a[1]||"",setTimeout(function(){switch(c){case "gw":b._ongoshop();break;case "yx":b._ongogame();break;case "sp":b._ongovideo();break;case "sh":b.ongolife();break;case "wl":b._ongorelax()}},1E3))},_initHoverAnimation:function(){var a=this,b=a.options,c=p().changePosition(a.goshop.get(0),b.shoppingMap).repeat(),d=p().changePosition(a.golife.get(0),b.lifeMap).repeat(),e=p().changePosition(a.gorelax.get(0),b.relaxMap).repeat(),f=p().changePosition(a.gogame.get(0),b.gameMap).repeat(),
h=p().changePosition(a.govideo.get(0),b.videoMap).repeat();a.gogame.hover(function(){f.start(200)},function(){f.pause();this.style.backgroundPosition="15px -167px"});a.govideo.hover(function(){h.start(200)},function(){h.pause();this.style.backgroundPosition="15px -199px"});a.goshop.hover(function(){c.start(200)},function(){c.pause();this.style.backgroundPosition="15px 10px"});a.golife.hover(function(){d.start(200)},function(){d.pause();this.style.backgroundPosition="15px -28px"});a.gorelax.hover(function(){e.start(200)},
function(){e.pause();this.style.backgroundPosition="15px -67px"});a.toptoggle.hover(function(){var b=this,c=a.options;a.toggleAnimate=p().enterFrame(function(d,e){var f=e/200|0,h=a.attop?c.gobottomMap:c.gotopMap;3<=f?d():(f=h[f].split(" "),b.style.backgroundPosition=f[0]+"px "+f[1]+"px")}).repeat().start(200)},function(){a.toggleAnimate.dispose();this.style.backgroundPosition=a.attop?"15px -136px":"15px -103px"})},_showTip:function(){var a=this.options,b=a.tip,d=a.title,f=a.url||"";if(""!=b&&!this.$tip&&
(this.$tip=$(c(a.tpl,{img:b,url:f})),this.$tip.appendTo(this.shortcut).animate({top:-110,height:110}),""==f))switch(d){case "gw":this.$tip.click(this._ongoshop);break;case "yx":this.$tip.click(this._ongogame);break;case "sp":this.$tip.click(this._ongovideo);break;case "sh":this.$tip.click(this.ongolife);break;case "wl":this.$tip.click(this._ongorelax);break;default:this.$tip.click(this._ongorelax)}},_showOrHideGoErwei:function(){if(a.qrnotshow||1230>$(window).width())a.goerwei.hide();else{var b=a.shortcutImage.attr("data-class");
b&&a.shortcutImage.addClass(b).attr("data-class","");a.goerwei.show()}},_hideQrCode:function(){f.set("qr_notshow",1);a.qrnotshow=!0;a.goerwei.hide()},_isAtTop:function(){return 1E3>$(window).scrollTop()?!0:!1},_showTopToggle:function(){a.attop=a._isAtTop();a.attop&&!i?a.toptoggle.fadeOut():a.attop?(a.toptoggle.removeClass("gotop gotop-hook").addClass("gobottom gobottom-hook").attr("title","\u8df3\u8f6c\u5230\u9875\u5e95").show().find(".text").text("\u5230\u5e95\u90e8"),a.toptoggle.get(0).style.backgroundPosition=
"15px -136px"):(a.toptoggle.removeClass("gobottom gobottom-hook").addClass("gotop gotop-hook").attr("title","\u8fd4\u56de\u9876\u90e8").show().find(".text").text("\u56de\u9876\u90e8"),a.toptoggle.get(0).style.backgroundPosition="15px -103px")},_showShortcut:function(){1200<$(window).width()?6==b.ie?a.shortcut.show():a.shortcut.fadeIn():6==b.ie?a.shortcut.hide():a.shortcut.fadeOut()},_showNav:function(){i?6==b.ie?(a.goshop.show(),a.newindex.show(),a._showTip(),a.golife.show(),a.gorelax.show(),a.gogame.show(),
a.govideo.show()):(a.toptoggle.fadeIn(),a.newindex.fadeIn(),a.gogame.fadeIn(function(){a._showTip()}),a.govideo.fadeIn(),a.goshop.fadeIn(),a.golife.fadeIn(),a.gorelax.fadeIn()):6==b.ie?(a.goshop.hide(),a.golife.hide(),a.gorelax.hide(),a.gogame.hide(),a.govideo.hide()):(a.goshop.fadeOut(),a.golife.fadeOut(),a.gorelax.fadeOut(),a.gogame.fadeOut(),a.govideo.fadeOut())},_setNavShow:function(){i=!0},_ontabchange:function(b){a._setNavShow(b);a._showNav();a._showTopToggle()},_onchange:function(){a._showOrHideGoErwei();
a._showTopToggle();a._showShortcut()},_windowGoTo:function(a,b){$("html,body").animate({scrollTop:a+"px"},function(){window.setTimeout(function(){b&&$(window).scrollTop(b.offset().top-j)},20)})},_ontoptoggle:function(){a.attop?a._windowGoTo(document.body.scrollHeight-$(window).height()):a._windowGoTo(0);return!1},_ongoshop:function(){var b=$("#hao123-gw11");a._windowGoTo(b.offset().top-j,b);return!1},ongolife:function(){var b=$("#hao123-lbspanel");a._windowGoTo(b.offset().top-j,b);return!1},_ongorelax:function(){var b=
$("#hao123-wuliao");a._windowGoTo(b.offset().top-j,b);return!1},_ongogame:function(){var b=0;k||(k=!0,b=94);a._windowGoTo($("#hao123-game").offset().top-j-b);return!1},_ongovideo:function(){a._windowGoTo($("#hao123-video").offset().top-j);return!1},_onscroll:function(){if(6==b.ie){var c=document.documentElement.scrollTop+document.documentElement.clientHeight-311,d=document.documentElement.scrollTop+document.documentElement.clientHeight-166;a.shortcut.stop(!0,!0);a.goerwei.stop(!0,!0);a.shortcut.animate({top:c},
200);a.goerwei.animate({top:d},200)}a._showTopToggle();a._showShortcut()},destroy:function(){$.Widget.prototype.destroy.call(this)}});return n});
__d("common.js.slider",["common.js.jquery"],function(s,u,n,e){var b=e("common.js.jquery");return function(c){function d(){if("fade"==k)0==g?i(m-1):i(g-1);else{if(l.is(":animated"))return!1;g--;0>g&&(g=m-1,l.css("left",-m*r));h();l.stop(!0,!0).animate({left:"+="+r},250,"linear",function(){g==m-1&&l.css("left",-g*r);a()})}}function f(){if("fade"==k)g+1==m?i(0):i(g+1);else{if(l.is(":animated"))return!1;g++;g==m&&(g=0);h();l.stop(!0,!0).animate({left:"-="+r},250,"linear",function(){0==g&&l.css("left",
0);a()})}}function e(b){var c;c=b-g;0!=c&&(g=b,h(),l.stop(!0,!0).animate({left:"-="+c*r},500,"linear",function(){a()}))}function h(){0!=x.length&&x.each(function(){b(this).removeClass(q);b(this).data("index")==g&&b(this).addClass(q)})}function a(){z&&(clearInterval(y),y=setInterval(function(){f()},u))}function i(b){b!=g&&(t.eq(g).removeClass(q).css({opacity:1}).stop().animate({opacity:0},800),t.eq(b).addClass(q).css({opacity:0}).stop().animate({opacity:1},800),g=b,h(),a())}var k=c.type||"l2r",j=c.trigger||
"click",q=c.selectCls||"selected",n=c.gridhoverCls||"grid_hover",z=c.auto||!1,o=c.context?b(c.slider,c.context):b(c.slider),l=b(c.slides,o),t=b(c.slides,o).children(),v=b(c.prev,o),w=b(c.next,o),x=b(c.points,o).children(),s=b(c.grid,o),A=t.eq(0),r=c.width||A.width();A.height();var m=t.length,g=0;"l2r"==k&&(A.clone().insertAfter(t.eq(m-1)),l.css({width:r*(m+1)+"px"}));(function(){v.click(function(){d();return!1});v.mousedown(function(a){a.preventDefault()});w.click(function(){f();return!1});w.mousedown(function(a){a.preventDefault()});
"click"==j?x.click(function(){"fade"==k?i(b(this).data("index")):e(b(this).data("index"))}):"hover"==j&&x.hover(function(){"fade"==k?i(b(this).data("index")):e(b(this).data("index"))},function(){});s.hover(function(){b(this).addClass(n)},function(){b(this).removeClass(n)});z&&s.hover(function(){clearInterval(y)},function(){a()});"fade"==k&&o.hover(function(){v.show();w.show()},function(){v.hide();w.hide()})})();if(z){var y,u=c.interval||1E4;a()}return{dispose:function(){clearInterval(y)}}}});
__d("widget.gw11slider.gouwu",["common.js.widget","common.js.slider"],function(s,u,n,e){e("common.js.widget");$.widget("hao123.gouwu",{options:{len:1,hoverCls:"grid_hover",selectCls:"selected",curCls:"current"},_create:function(){var b=this.element;this.$items=$(".item-hook",b);this.$activebg=$(".active_bg-hook",b);this.$grid=$(".grid-hook",b);this.$slides=$(".slides-hook",b);this.$point=$(".point",b)},_init:function(){var b=this.options,c,d,f=this.$grid.length;this.slider=[];for(d=0;d<f;d++)1<$(".screen",
this.$grid.eq(d)).length&&(c=e("common.js.slider"),this.slider[d]=c({slider:".grid-hook"+d,slides:".slides-hook",prev:".prev-hook",next:".next-hook",auto:1,interval:1E4}),this.$grid.eq(d).hover(function(){$(this).addClass(b.hoverCls)},function(){$(this).removeClass(b.hoverCls)}));this._bindEvent()},_bindEvent:function(){var b=this,c=b.options;b.$slides.hover(function(){b.$activebg.each(function(){$.contains(b.current,this)||$(this).show().stop().animate({opacity:0.6})})},function(){b.$activebg.each(function(){$(this).stop().animate({opacity:0},
function(){$(this).hide()})})});b.$point.click(function(){return!1});b.$point.mouseenter(function(){var d=$(this).data("index"),f=$("img",b.$grid.eq(d)),e=f.length;$(this).hasClass(c.selectCls)||(b.$point.removeClass(c.selectCls),$(this).addClass(c.selectCls),b.$grid.removeClass(c.curCls),b.$grid.eq(d).addClass(c.curCls));if(!f.eq(0).attr("src"))for(d=0;d<e;d++){var h=f[d];h.setAttribute("src",h.getAttribute("data-src"))}});b.$items.hover(function(){b.current=this;$(this).find(".active_bg-hook").stop().css({opacity:0}).hide()},
function(){$(this).find(".active_bg-hook").show().stop().animate({opacity:0.6})})},destroy:function(){if(this.slider){var b=this.slider.length,c;for(c=0;c<b;c++)this.slider[c].dispose()}$.Widget.prototype.destroy.call(this)}});return n});window.js_bHANKrKyHI&&window.js_bHANKrKyHI(!0);
