__d("widget.sitelinks.sitelinks",["common.js.widget","common.js.browser"],function(o,p,m,c){c("common.js.widget");var g=c("common.js.browser");$.widget("hao123.sitelinks",{options:{},_create:function(){this._render();this._bindEvent()},_render:function(){var c=this.element;this.$bgbox=$(".js_bgbox",c);this.$openup=$(".js_openup",c);this.$sites=$(".js_bgbox a",c);6==g.ie&&this._setWidth(this.$bgbox.width()-16)},_setWidth:function(c){this.$sites.width(c)},_bindEvent:function(){var c=this;this.$bgbox.hover(function(){clearTimeout(c.hideTimer)},
function(){clearTimeout(c.showTimer);c.hideTimer=setTimeout(function(){c._hide()},300)});this.$openup.hover(function(){clearTimeout(c.hideTimer);c.showTimer=setTimeout(function(){c._show()},300)},function(){clearTimeout(c.showTimer);c.hideTimer=setTimeout(function(){c._hide()},300)});this.$sites.bind("click",function(){c._hide()})},_hide:function(){$(this.element).css("z-index","0");this.$bgbox.hide()},_show:function(){$(this.element).css("z-index","90");this.$bgbox.show()},destroy:function(){$.Widget.prototype.destroy.call(this)}});
return m});
__d("widget.famoussite.famoussite",["common.js.jquery","common.js.log","widget.append.append","common.js.profile"],function(o,p,m,c){var g=c("common.js.jquery"),j=c("common.js.log"),l=c("widget.append.append"),h=c("common.js.profile");return function(){var b=g("#box-famoussite .wf-slider"),i=g("#box-famoussite .widget-famoussite .wf-inner"),c=g("#box-wfslider");g(".widget-wfslider",c);var f=b.parent(".wf-line"),d=!0;b.click(function(){d&&(d=!1,i.slideToggle(200,function(){l();i.css("overflow","visible");
f.hasClass("js_sliderClose")?(h.set("fms","0"),b.attr("title","\u70b9\u6211\u6536\u8d77\u5b9e\u7ebf\u4ee5\u4e0b\u7f51\u5740"),BigPipe.request("/api/gettop/?fms=0",["box-wfslider"]),j({type:"fms",v:0})):(h.set("fms","1"),b.attr("title","\u70b9\u6211\u5c55\u5f00\u7f51\u5740"),BigPipe.request("/api/gettop/?fms=1",["box-wfslider"]),j({type:"fms",v:1}));f.toggleClass("js_sliderClose");d=!0}));return!1});c.click(function(a){if(g(a.target).hasClass("wf-change")){a=parseInt(g(a.target).attr("rnd"));a+=1;
if(3<a||1>a)a=1;BigPipe.request("/api/gettop/?fms=1&rnd="+a,["box-wfslider"]);return!1}})}});
__d("widget.suggest.nssug",["common.js.jquery","common.js.config","common.js.format"],function(o,p,m,c){function g(b){for(var b=b||{},c=arguments,f=c.length,d=0,a,e;++d<f;)if(a=c[d])for(e in a)a.hasOwnProperty(e)&&(b[e]=a[e]);return b}function j(b,c,f,d){var a={url:"http://nssug.baidu.com/su?cb=?",data:{},queryKey:"wd",cache:!1,dataType:"jsonp",scriptCharset:"gbk"},e={},f=f||j.defaultCallback;b&&(e.prod=b);g(a.data,e,c);g(a,d);return function(e){var d=this,b=a.data||{};(e=e.replace(/^\s+|\s+$/g,""))?
(b[a.queryKey]=e,a.data=b,h.ajax(a).done(function(){f.apply(d,arguments);d=null})):d.clear()}}function l(c,k){var f=k;c&&-1<f.indexOf(c)&&(f=["<b>",f.replace(c,b("</b>#{0}<b>",c)),"</b>"].join("").replace("<b></b>",""));return f}var h=c("common.js.jquery");c("common.js.config");var b=c("common.js.format");j.defaultCallback=function(b){var c,f,d,a;this.clear();if(b&&(c=b.s)&&(d=c.length)){b=b.q||"";for(f=0;f<d;f++)a=c[f],this.add(a,l(b,a));this.show()}};j.getSuggestHTML=l;return j});
__d("widget.suggest.suggest",["common.js.widget","common.js.format","common.js.events","common.js.JSON"],function(o,p,m,c){function g(d,a){"length"in d&&(d=d[0]);return d.getAttribute("data-"+a)}function j(d){d=parseInt(g(d,"index"));return isNaN(d)?0:d}c("common.js.widget");var l=c("common.js.format"),h=c("common.js.events"),b=c("common.js.JSON"),i="input",k=!0,f=function(){};$.widget("hao123.suggest",{options:{popupTpl:'<div class="suggest #{classes|e}"><div class="header-hook"></div><ul class="list-hook"></ul><div class="footer-hook"></div></div>',
itemTpl:'<li class="suggest-item item-hook" data-query="#{query|e}" data-index="#{index|e}" data-data="#{data|e}">#{html}</li>',header:"",footer:"",classes:"",hoverClass:"hover g-bg3",inputDelay:200,hideDelay:20,eventSpace:"suggest"},_create:function(){var d=this.options,a=this.element;this.$tip=$(l(d.popupTpl,d));this.$list=$(".list-hook",this.$tip);this.$header=$(".header-hook",this.$tip);this.$footer=$(".footer-hook",this.$tip);this._footer=this._header="";this.header(d.header);this.footer(d.footer);
this.$tip.appendTo(a.parent())},_init:function(){this.repaint=this.showed=this.inited=!1;this.content=[];this.$items=null;this._index=0;this._original=this.element.val();this._shouldClose=this._hold=this._skipChange=!1;this._inputHandler=f;this._initInputEvent();this._initTipToggle();this._initKeyEvent()},_initTipToggle:function(){function d(){clearTimeout(f);f=setTimeout(a,n)}function a(){var a;if((e._shouldClose=a=!c&&!i)&&!e._hold)e.original(b.val()),e.hide(k)}var e=this,b=e.element,f=0,n=e.options.hideDelay,
c=!1,i=!1,h=!1;b.on("input focus keydown",function(){c=!0;d()}).on("blur",function(){c=!1;d()}).on("beforedeactivate",function(){return!h});e.$tip.hover(function(){i=!0;d()},function(){i=!1;d()});e.$list.mousedown(function(){h=!0;setTimeout(function(){h=!1},0);return!1}).mouseup(function(a){2<a.which||0==e._index||(e.select(e._index,!0),e.submit("click"))})},hold:function(d){var a=this.element;this._hold=!!d;this._shouldClose&&!d&&(this.original(a.val()),this.clear())},_initInputEvent:function(){function d(){c=
b.val().replace(/^\s+|\s+$/g,"");e.original(c);clearTimeout(n);n=setTimeout(a,f)}function a(){k!==c&&(k=c,e._triggerEvent(i,{value:c})&&e._inputHandler(c))}var e=this,b=e.element,f=e.options.inputDelay,n=0,c=null,k=null;b.attr("autocomplete","off");b.on("input",d);b.on("propertychange",function(a){(a=a.originalEvent)&&"value"==a.propertyName&&(e._skipChange||d())});e.original()&&d()},_initKeyEvent:function(){var d=this;d.element.on("keydown",function(a){var e=!1;switch(a.keyCode){case 38:d.select(d._index-
1,!0);e=!0;break;case 40:d.select(d._index+1,!0);e=!0;break;case 13:d.submit("enter");e=!1;break;case 27:d.hide(k),e=!0}return!e})},_addItemEvent:function(){var d=this;d.$items.mouseenter(function(){d.select(j(this))})},_removeItemEvent:function(){me.$items.off("mouseenter mouseleave click")},_triggerEvent:function(d,a){var e=this.options,b;b=this._trigger(d,null,a)&&!0;b=h.emit(e.eventSpace+"."+d,a)&&b;return!!b},submit:function(d){d={value:this.element.val(),index:this._index,from:d};this.hide(k);
this._triggerEvent("submit",d)},show:function(){this.repaint&&(this.$item&&this._removeItemEvent(),this.$list.html(this.content.join("")),this.$items=$(".item-hook",this.$list),this._addItemEvent(),this.repaint=!1);this.showed||this.$tip.show();this.showed=!0},hide:function(d){this.showed&&(this.$tip.hide(),this._triggerEvent("hide"));this.showed=!1;d||this.select(0)},header:function(d){this._header!=d&&(d?(this.$header.html(d),this._header||this.$header.show()):this.$header.hide(),this._header=d)},
getHeader:function(){return this.$header},getList:function(){return this.$list},footer:function(d){this._footer!=d&&(d?(this.$footer.html(d),this._footer||this.$footer.show()):this.$footer.hide(),this._footer=d)},clear:function(){this.content.length&&(this.content=[],this.repaint=!0);this.hide()},add:function(d,a,e){var x=this.options,c=this.content,n=c.length+1;c.push(l(x.itemTpl,{query:d,index:n,html:void 0===a?d:a,data:b.stringify(2<arguments.length?e:null)}));this.repaint=!0;this.showed&&this.show()},
select:function(d,a){var e=this,c=e.element,f=e.$items,n=e.options.hoverClass,i=e.content.length+1,k=e._index,h=null,j=null,l=null,h=null,d=d%i;0>d&&(d+=i);a=!!a;e._index=d;0<k&&f.eq(k-1).removeClass(n);0<d&&f.eq(d-1).addClass(n);a&&(0<d?(f=f.eq(d-1),j=g(f,"query"),l=b.parse(g(f,"data"))):(j=e.original(),l=null),h=c.val(),h={index:d,oldValue:h,newValue:j,data:l},e._triggerEvent("change",h)&&(e._skipChange=!0,c.val(j),setTimeout(function(){e._skipChange=!1},0)));var m=d;0==m&&(m=1);window.setTimeout(function(){var a=
e.$list.find("li").eq(m-1),a=a&&a.data()?a.data().data:void 0;e._trigger("select",null,{index:d,data:a,q:c.val()})},0)},original:function(d){if(arguments.length)this._original=d;else return this._original},index:function(){return this._index},handler:function(d){this._inputHandler=d||f}});return m});
__d("widget.suggest.webHandler",["common.js.jquery","common.js.format","common.js.cookie"],function(o,p,m,c){function g(b){var d=this;h.ajax({url:"http://suggestion.baidu.com/su?cb=?",data:{wd:b,sc:"hao123"},queryKey:"wd",cache:!1,dataType:"jsonp",scriptCharset:"gbk"}).done(function(a){d.clear();var e=!1,b=k.check(a.s),c=a.z?!0:!1;h.each(a.s,function(n){if(b&&10<this.length)return!0;e=!0;if(c&&a.z[n])n=l(a.z[n]),d.add(a.q,n.html,{suggestId:n.id});else if(k.checkItem(this)){var f=k.getData(this);d.add(a.s[n],
k.getHTML(a.q,this,f),f)}else d.add(a.s[n],j(a.q,this))});e?d.show():d.hide()})}function j(b,d){var a="<b>"+d.replace(RegExp(b,"g"),"</b>"+b+"<b>")+"</b>";a.replace("<b></b>","");return a}function l(c){var d=parseInt(c.type),a={};switch(d){case 1:case 2:if(void 0===c.key)return!1;a.query=c.key;a.html=b('<dl class="aladdin"><dt class="info g-fc2"><img class="icon" src="http://s1.hao123img.com/index/images/xiongzhang.png" width="12" height="12" />#{key}#{auth}</dt><dd class="define">#{word}#{word_add}</dd></dl>',
{key:c.key,auth:function(){return 2==d?" - \u767e\u5ea6\u5b89\u5168\u8ba4\u8bc1":""},word:c.word||"",word_add:function(){return c.word_add?b(' <span class="info g-fc2">(#{0})</span>',c.word_add):""}});a.id=c.id;break;default:return!1}return a}var h=c("common.js.jquery"),b=c("common.js.format"),i=c("common.js.cookie"),k=function(){var b;h.ajax({url:"/api/ssugdata",data:{c:i.getCSRFId(),r:(new Date).getTime()/3E5|0},cache:!0,dataType:"json"}).done(function(d){b=d});return{check:function(d){if(!b)return!1;
for(var a=0,e=d.length;a<e;a++)for(var c=0,i=b.length;c<i;c++)if(h.trim(d[a])==h.trim(b[c].title))return!0},checkItem:function(d){if(!b)return!1;for(var a=0,e=b.length;a<e;a++)if(h.trim(d)==h.trim(b[a].title))return!0;return!1},getData:function(d){if(b&&b)for(var a=0,e=b.length;a<e;a++)if(h.trim(b[a].title)==h.trim(d))return b[a].isSpecial=!0,b[a]},getHTML:function(b,a,e){b="<b>"+a.replace(RegExp(b,"g"),"</b>"+b+"<b>")+"</b>";b.replace("<b></b>","");return b+='<i class="suggest-hint">'+{m:"\u7535\u5f71",
t:"\u7535\u89c6\u5267",d:"\u52a8\u6f2b",z:"\u7efc\u827a"}[e.sort]+"</i>"},getPMData:function(){return b}}}();g.getPMData=k.getPMData;return g});
__d("widget.suggest.videoHandler",["common.js.jquery","common.js.format","common.js.browser","common.js.cookie"],function(o,p,m,c){function g(b,c,d){b=c.replace(RegExp(b,"g"),"<b>"+b+"</b>");(d=h[d])&&(b+=l('<div class="suggest-video-type">#{text}<i>&gt;</i></i>',{text:d}));return b}var j=c("common.js.jquery"),l=c("common.js.format");c("common.js.browser");c("common.js.cookie");var h={movie:"\u7535\u5f71",tv:"\u7535\u89c6\u5267",comic:"\u52a8\u6f2b",show:"\u7efc\u827a"},b=j("#search");b.on("searchtabchange",
function(c,f){var d=f.currTab,a=b.find(".suggest");"video"==d?a.removeClass("suggest-search").addClass("suggest-video"):(a.removeClass("suggest-video"),a.hasClass("suggest-search")||a.addClass("suggest-search"))});b.on("suggestselect",function(b,c){var d=c.data;d&&d.videoid?i.fill(d):i.hide()});var i=function(){function c(e){a||(a=!0,d=j("<div>"),b.find(".suggest").append(d));d.get(0).className={movie:"suggest-video-detail suggest-video-detail-movie",tvplay:"suggest-video-detail suggest-video-detail-tv",
comic:"suggest-video-detail suggest-video-detail-comic",tvshow:"suggest-video-detail suggest-video-detail-tvshow"}[e.category];d.show().html(l({movie:"<div class='suggest-video-detail-pic'><a href='#{url}'><img src='#{poster}'/><div class='suggest-video-detail-pictext'>#{year}</div></a></div><div class='suggest-video-detail-content'><div class='suggest-video-detail-title'><a href='#{url}'>#{title}</a></div><div class='suggest-video-detail-info'><p><span class='label'>\u8bc4\u5206\uff1a</span><span class='rate'>#{rating}</span></p><p><span class='label'>\u4e3b\u6f14\uff1a</span>#{actors}</p><p><span class='label'>\u5bfc\u6f14\uff1a</span>#{directors}</p><p><span class='label'>\u7c7b\u578b\uff1a</span>#{genres}</p></div><a class='suggest-video-detail-link' href='#{url}'>\u67e5\u770b\u8be6\u60c5<span>&gt;&gt;</span></a></div>",
tvplay:"<div class='suggest-video-detail-pic'><a href='#{url}'><img src='#{poster}'/><div class='suggest-video-detail-pictext'>#{update}</div></a></div><div class='suggest-video-detail-content'><div class='suggest-video-detail-title'><a href='#{url}'>#{title}</a></div><div class='suggest-video-detail-info'><p><span class='label'>\u4e3b\u6f14\uff1a</span>#{actors}</p><p><span class='label'>\u5e74\u4ee3\uff1a</span>#{year}</p><p><span class='label'>\u7c7b\u578b\uff1a</span>#{genres}</p></div><a class='suggest-video-detail-link' href='#{url}'>\u67e5\u770b\u8be6\u60c5<span>&gt;&gt;</span></a></div>",
comic:"<div class='suggest-video-detail-pic'><a href='#{url}'><img src='#{poster}'/><div class='suggest-video-detail-pictext'>#{update}</div></a></div><div class='suggest-video-detail-content'><div class='suggest-video-detail-title'><a href='#{url}'>#{title}</a></div><div class='suggest-video-detail-info'><p><span class='label'>\u5e74\u4ee3\uff1a</span>#{year}</p><p><span class='label'>\u5730\u533a\uff1a</span>#{areas}</p><p><span class='label'>\u7c7b\u578b\uff1a</span>#{genres}</p></div><a class='suggest-video-detail-link' href='#{url}'>\u67e5\u770b\u8be6\u60c5<span>&gt;&gt;</span></a></div>",
tvshow:"<div class='suggest-video-detail-pic'><a href='#{url}'><img src='#{poster}'/><div class='suggest-video-detail-pictext'>#{update}</div></a></div><div class='suggest-video-detail-content'><div class='suggest-video-detail-title'><a href='#{url}'>#{title}</a></div><div class='suggest-video-detail-info'><p><span class='label'>\u4e3b\u6301\uff1a</span>#{hosts}</p><p><span class='label'>\u5730\u533a\uff1a</span>#{areas}</p><p><span class='label'>\u7c7b\u578b\uff1a</span>#{genres}</p></div><a class='suggest-video-detail-link' href='#{url}'>\u67e5\u770b\u8be6\u60c5<span>&gt;&gt;</span></a></div>"}[e.category],
e));j("#search .suggest").css({height:264})}var f={},d,a=!1,e=function(){function a(b){for(var e=[],d=0;d<b.length;d++)e.push('<span class="text">'+b[d]+"</span>");return e.join("")}function b(a){var e=a.episodes_count||a.episode_count;return a.update<e?"\u66f4\u65b0\u81f3"+a.update+"\u96c6":"\u5168"+e+"\u96c6"}return function(e){var d;switch(e.category){case "movie":d={actors:a(e.actors),directors:a(e.directors),genres:a(e.genres),url:"http://v.hao123.com/dianying/"+e.id+".htm",year:e.year};break;
case "tvplay":d={actors:a(e.actors),directors:a(e.directors),genres:a(e.genres),url:"http://v.hao123.com/dianshi/"+e.id+".htm",year:e.year,update:b(e)};break;case "comic":d={genres:a(e.genres),url:"http://v.hao123.com/dongman/"+e.id+".htm",year:e.year,areas:e.areas,update:b(e)};break;case "tvshow":d={hosts:a(e.hosts),genres:a(e.genres),url:"http://v.hao123.com/zongyi/"+e.id+".htm",year:e.year,areas:a(e.areas),update:"\u66f4\u65b0\u81f3"+e.update.replace(/(\d{4})(\d{2})(\d{2})/,"$1-$2-$3")}}d.title=
e.title;d.category=e.category;d.poster=e.poster;d.rating=e.rating;return d}}();return{show:c,hide:function(){d&&(d.hide(),j("#search .suggest").css({height:"auto"}))},fill:function(a){f[a.videoid]?c(f[a.videoid]):j.ajax({url:a.url,data:{id:a.videoid},cache:!0,dataType:"jsonp"}).done(function(b){b=e(b.video);f[a.videoid]=b;c(b)})}}}();return function(b){var c=this;j.ajax({url:"http://nssug.baidu.com/su?cb=?",data:{wd:b,sc:"hao123",prod:"video_ala",oe:"utf-8"},queryKey:"wd",scriptCharset:"gbk",cache:!1,
dataType:"jsonp"}).done(function(d){c.clear();var a=!1;window.s=d.s;j.each(d.s,function(e,d){var i=d.split("{#S+_}");if(0==i.length||5<e)return!0;a=!0;var n=j.parseJSON(i[1]);n?c.add(i[0],g(b,i[0],n.type),{videoid:n.id,url:"http://v.baidu.com/"+n.type+"_sug/?callback=?"}):c.add(i[0],g(b,i[0]))});a&&c.show()})}});
__d("widget.search.config","common.js.format,widget.suggest.nssug,widget.suggest.webHandler,widget.suggest.videoHandler,common.js.config,common.js.log,common.js.browser,common.js.query".split(","),function(o,p,m,c){function g(a){6==f.ie&&(a+="_png8");return"images/search_logo/"+a+".png"}function j(a){var b,d,c,f,h;this.clear();if(a&&!a.error&&(b=a.msg)&&(f=b.length)){h=i("#{0|e}",this.original());for(c=0;c<f;c++)a=b[c],d=k.getSuggestHTML(h,a),this.add(a,d);this.show()}}
function l(a){var b,d,c,f,h,g;this.clear();if(a&&(b=a.s)&&(f=b.length)){h=a.q||"";for(c=0;c<f;c++)if(a=b[c])a=a.split("$"),g=a[0]+a[1],a=a[2]||""+a[3]||"",a||(a=b[c].split("$"),a=a[3]?a[1]:a[0]+a[1],g=!a[3]||0!=a[3]?"":a[0]),a||(a=b[c].split("$"),a=a[3]||"",g=a[0]+a[1]),d=k.getSuggestHTML(h,a),d+=i('<i class="g-fc2">#{0}</i>',g),this.add(a,d);this.show()}}function h(){var a=document.URL,b=c("common.js.query"),i=b.tn,f=b.src,b=b.s,h;return i?i:f&&d[h=f.toLowerCase()]?d[h]:f&&f.match(/se_.+/i)?f:f?
/^.+_hao$/i.test(f)?f:f+"_hao":-1<a.indexOf("www.6164.com/?index.html")?"srcindex_hao":-1<a.indexOf("www.6164.com/?index.htm")?"srcieak_hao":-1<a.indexOf("www.6164.com/?vit=fws")?"srcvit_hao":b?b:"sogou-site-220c77af02f8ad85"}function b(a,b,d){return!a.hasOwnProperty(b)?d:a[b]}var i=c("common.js.format"),k=c("widget.suggest.nssug"),o=c("widget.suggest.webHandler"),p=c("widget.suggest.videoHandler");c("common.js.config");c("common.js.log");var f=c("common.js.browser"),d={sina:"10000401_hao",skycn_zuoce:"10018401_hao",
happynewyear123:"10018202_hao",newyear:"10018201_hao",xunlei10:"10003804_hao",jifen:"10018701_hao",jifen2:"10018702_hao",jifen3:"10018703_hao","360fixwiz":"sogou-site-220c77af02f8ad85",baidu:"sogou-site-220c77af02f8ad85",desk:"sogou-site-220c77af02f8ad85"},a={web:{alt:"\u9996\u9875",logo:g("sogou"),url:function(){var a=h();return"http://www.sogou.com/index.php?pid="+encodeURIComponent(a)}(),action:"http://www.sogou.com/sogou",query:"query",params:{pid:h(),ie:"utf-8"},sug:o,hotword:"/sugdata.js"},music:{alt:"\u767e\u5ea6\u97f3\u4e50",logo:g("yinyue"),
url:"http://music.baidu.com",action:"http://music.hao123.com/search",query:"key",params:{fr:"hao123",ie:"utf-8"},sug:k("mp3",{sc:"hao123"})},video:{alt:"\u767e\u5ea6\u89c6\u9891\u641c\u7d22",logo:g("video"),url:"http://v.baidu.com",action:"http://v.baidu.com/v",query:"word",params:{fr:"video",ie:"utf-8"},sug:p},image:{alt:"\u767e\u5ea6\u56fe\u7247",logo:g("image"),url:"http://image.baidu.com",action:"http://image.baidu.com/i",query:"word",params:{tn:"baiduimage",ct:"201326592",cl:"2",lm:"-1",ie:"utf-8",
fm:"hao123"},sug:k("image",{sc:"hao123"}),hotword:"/sugimage.js"},tieba:{alt:"\u767e\u5ea6\u8d34\u5427",logo:g("tieba"),url:"http://tieba.baidu.com",action:"http://tieba.baidu.com/f",query:"kw",params:{ie:"utf-8",sc:"hao123"},sug:function(a){var b=this;(a=a.replace(/^\s+|\s+$/g,""))?(a=i("http://tieba.baidu.com/sug?query=#{0|u}&callback=?",a),$.ajax({url:a,data:{sc:"hao123"},cache:!1,dataType:"jsonp",scriptCharset:"gbk"}).done(function(){j.apply(b,arguments);b=null})):b.clear()}},zhidao:{alt:"\u767e\u5ea6\u77e5\u9053",
logo:g("zhidao"),url:"http://zhidao.baidu.com",action:"http://zhidao.baidu.com/q",query:"word",params:{tn:"ikaslist",ct:"17",ie:"utf-8",sc:"hao123",rn:"20"},sug:k("zhidao",{sc:"hao123"})},news:{alt:"\u767e\u5ea6\u65b0\u95fb\u641c\u7d22",logo:g("news"),url:"http://news.baidu.com",action:"http://news.baidu.com/ns",query:"word",params:{tn:"news",ie:"utf-8",from:"hao123",sr:0,cl:2,rn:20,ct:1,prevct:"no"},sug:k("news",{sc:"hao123"})},map:{alt:"\u767e\u5ea6\u5730\u56fe\u641c\u7d22",logo:g("map"),url:"http://map.baidu.com",
action:"http://map.baidu.com/m",query:"word",params:{c:1,ie:"utf-8",sc:"hao123"},sug:function(a){var b=this;(a=a.replace(/^\s+|\s+$/g,""))?(a=i("http://map.baidu.com/su?wd=#{0|u}&callback=?",a),$.ajax({url:a,data:{cid:1,type:0,newmap:1,sc:"hao123"},cache:!1,dataType:"jsonp",scriptCharset:"utf-8"}).done(function(){l.apply(b,arguments);b=null})):b.clear()}}};return function(d){d=a[d];return!d?void 0:{alt:b(d,"alt"),logo:b(d,"logo"),url:b(d,"url"),action:b(d,"action"),query:b(d,"query"),params:b(d,"params"),
sug:b(d,"sug"),hotword:b(d,"hotword",!1)}}});
__d("widget.search.search","common.js.widget,widget.suggest.suggest,common.js.repeat,common.js.format,common.js.cookie,common.js.config,widget.search.config,widget.suggest.webHandler".split(","),function(o,p,m,c){function g(a,b){for(var a=a||{},d=arguments,c=d.length,f=0,i,h;++f<c;)for(h in i=d[f],i)i.hasOwnProperty(h)&&(a[h]=i[h]);return a}c("common.js.widget");c("widget.suggest.suggest");c("common.js.repeat");var j=c("common.js.format"),l=c("common.js.cookie"),h=c("common.js.config"),b=c("widget.search.config"),
i=c("widget.suggest.webHandler"),k="tp3",f=window.location.hash||"",d=function(){};$.widget("hao123.search",{options:{defaultTab:"web",currClass:"s-bg20 g-fc5 g-fc5h curr",normalClass:"g-fc0",suggestClass:"suggest-search g-bg11 g-br9 g-sd0",paramTpl:'<input type="hidden" name="#{name|e}" value="#{value|e}" />',hotURL:"/sugdata.js",hotItemTpl:'<span class="hot-icon hot-icon-index hot-icon-#{cls}">#{index}</span>#{word}#{tag}',hotNumTpl:'<span class="hot-num">#{num}</span>',yindaoTibTpl:'<div style="display:none;hotword-yindao-tip" class="g_icon hotword-yindao-tip"><span class="g_icon hot-quan"></span><span class="hot-close"></span></div>',
hotOnClass:"hotword-on",hotSugFooter:'<a class="hotword-tip g-fc2" href="http://top.baidu.com/">\u7531\u767e\u5ea6\u641c\u7d22\u98ce\u4e91\u699c\u63d0\u4f9b</a>',detailMovieTpl:'<div class="suggest-detail-w" monkey="suggestspecial-movie"><a class="suggest-detail-img" href="#{detailurl}"><img src="#{imgurl}" /></a><a class="suggest-detail-play" href="#{playurl}">\u5728\u7ebf\u89c2\u770b</a><p><a class="suggest-detail-title" href="#{detailurl}" >#{title}</a></p><p>\u8bc4\u5206\uff1a<em>#{n}</em></p><p>\u4e3b\u6f14\uff1a<span>#{actor1}</span> <span>#{actor2}</span></p><p>\u5e74\u4ee3\uff1a#{year}</p><p>\u7c7b\u578b\uff1a <span>#{type1}</span> <span>#{type2}</span></p></div>',
detailTVTpl:'<div class="suggest-detail-w"  monkey="suggestspecial-tv"><a class="suggest-detail-img" href="#{detailurl}"><img src="#{imgurl}" /></a><a class="suggest-detail-play" href="#{playurl}">\u5728\u7ebf\u89c2\u770b</a><p><a class="suggest-detail-title" href="#{detailurl}" >#{title}</a></p><p class="linenumber">#{n}</p><p>\u4e3b\u6f14\uff1a<span>#{actor1}</span> <span>#{actor2}</span></p><p>\u5e74\u4ee3\uff1a#{year}</p><p>\u7c7b\u578b\uff1a <span>#{type1}</span> <span>#{type2}</span></p></div>',
detailCartoonTpl:'<div class="suggest-detail-w"  monkey="suggestspecial-cartoon"><a class="suggest-detail-img" href="#{detailurl}"><img src="#{imgurl}" /></a><a class="suggest-detail-play" href="#{playurl}">\u5728\u7ebf\u89c2\u770b</a><p><a class="suggest-detail-title" href="#{detailurl}" >#{title}</a></p><p>\u8bc4\u5206\uff1a<em>#{n}</em></p><p>\u5e74\u4ee3\uff1a<span>#{year}</span></p><p>\u5730\u533a\uff1a#{area}</p><p>\u7c7b\u578b\uff1a <span>#{type1}</span> <span>#{type2}</span></p></div>',detailZongyiTpl:'<div class="suggest-detail-w"  monkey="suggestspecial-zongyi"><a class="suggest-detail-img" href="#{detailurl}"><img src="#{imgurl}" /></a><a class="suggest-detail-play" href="#{playurl}">\u5728\u7ebf\u89c2\u770b</a><p><a class="suggest-detail-title" href="#{detailurl}" >#{title}</a></p><p class="linenumber">#{n}</p><p>\u4e3b\u6301\uff1a<span>#{actor1}</span> <span>#{actor2}</span></p><p>\u5730\u533a\uff1a#{area}</p><p>\u7c7b\u578b\uff1a<span>#{type1}</span> <span>#{type2}</span></p></div>'},
_create:function(){var a=this.element;this.$logoLink=$(".link-hook",a);this.$logoImg=$(".img-hook",a);this.$form=$(".form-hook",a);this.$shadow=$(".shadow-hook",a);this.$wrapper=$(".wrapper-hook",a);this.$input=$(".input-hook",a);this.$params=$(".params-hook",a);this.$button=$(".button-hook",a);this.$tabs=$(".tab-hook",a);this.$currTab=$(".curr-hook",a);this.$suggest=this.$input.suggest({classes:this.options.suggestClass,eventSpace:"searchsuggest"});this.$hotword=$(".hotword-hook",a);$(".tab",a).attr("hidefocus",
"true");this.$hotword.attr("hidefocus","true");""==f&&this.$input.focus()},_init:function(){var a=this,b=a.options,d=b.currClass,c=b.normalClass;a.$detail=a.$suggest.suggest("getHeader");a.$detail.addClass("detail");a.$list=a.$suggest.suggest("getList");a.$suggest.on("suggestselect",function(b,d){d=d.data;a.$list.css({height:"auto"});var c=a.$list.height();d&&d.isSpecial?(a.$detail.show().html(j(a.options[{m:"detailMovieTpl",t:"detailTVTpl",d:"detailCartoonTpl",z:"detailZongyiTpl"}[d.sort]],d)),a._trigger("specialshow"),
a.$list.hasClass("list-special")||a.$list.addClass("list-special"),200>c&&a.$list.css({height:200})):(a.$detail.hide(),a.$list.removeClass("list-special"))});a.$tabs.click(function(){var b=a.$currTab,e=b.data("tab"),f=null;b.removeClass(d).addClass(c);b=$(this).removeClass(c).addClass(d);a.$currTab=b;f=b.data("tab");e!==f&&a._trigger("tabchange",null,{prevTab:e,currTab:f});a._selectText();return!1});a.$shadow.click(function(){a.$input.focus()});a.$shadow.hover(function(){a.$input.is(":focus")||a._selectText()});
a._initHotWord();a._bindAdvancedEvent();a._initSubmitEvent();a._trigger("init",null,{currTab:b.defaultTab});a.element.on("mouseover",".footer-hook",function(){$(".item-hook",a.element).removeClass("hover g-bg3").filter(":last").addClass("hover g-bg3")});a.element.on("mouseout",".footer-hook",function(){$(".item-hook:last",a.element).removeClass("hover g-bg3")})},_initSubmitEvent:function(){var a=this,b=!1,d="other",c="input",f=0,h=null,k=a.options.defaultTab,g;a.$suggest.on("suggestinit",function(b,
d){a.$wrapper.append(d);return!1}).on("suggestinput",function(){c="input";f=0;h=null}).on("suggestchange",function(a,d){f=d.index;h=d.data;c=0==f?"input":b?"hotword":"suggest"}).on("suggestsubmit",function(b,c){switch(c.from){case "enter":g=d="enter";break;case "click":d="select";g="click";a.$form.submit();break;default:g=d="other"}});a.$button.on("mousedown",function(){g="button";a.$button.addClass("button-active")}).on("mouseout mouseup",function(){a.$button.removeClass("button-active")}).mouseup(function(){d=
"button";a._trigger("buttonclick",null,{query:a.$input.val()})});a.element.on("searchtabchange searchinit",function(a,b){k=b.currTab;h=null}).on("searchhotwordshow",function(){b=!0}).on("searchhotwordhide",function(){b=!1});a.$form.on("submit",function(b){function e(){if(!i.getPMData())return null;var a=i.getPMData(),b=[];$("#search .list-hook li").each(function(){for(var d=$(this).data().query,c=0;c<a.length;c++)a[c].title==d&&b.push(a[c])});return 0<b.length?b:null}function j(a){if(!i.getPMData())return!1;
for(var b=i.getPMData(),d=0;d<b.length;d++)if(b[d].title==a)return!0;return!1}if((b=a._trigger("submit",b,{action:d,from:c,suggestIndex:f,suggestData:h,query:a.$input.val(),tab:k}))&&"hotword"===c&&h&&h.url)a._goUrl(h.url),b=!1;d="other";if("web"==k){var l=!1,m=0,u=0,o=e(),s=$("#search .list-hook li").eq(f-1).data();0<f&&s&&s.data&&s.data.isSpecial?(b=!1,window.open(s.data.detailurl),m=u=1,l=!0):o&&(l=!0,u=0==f&&j(a.$input.val())?1:0);l&&a._trigger("secialsubmit",null,{toerji:m,from:g,hit:u,index:f})}return b})},
_goUrl:function(a){window.open(a)},_selectText:function(){""==f&&(this.$input.focus(),this.$input.select())},_initHotWord:function(){function a(a){var b,c;if(a&&a.data){a&&a.boardurl&&(b=!0);a=a.data;f.suggest("clear");b&&f.suggest("footer",d.hotSugFooter);for(b=1;10>=b;b++){c=a[b];if(!c)break;f.suggest("add",c.word,j(d.hotItemTpl,{index:b,cls:3>=b?"orange":"dark",word:c.word,tag:c.isnew?' <span class="hot-icon hot-icon-new">\u65b0</span>':""}),{url:c.url||null})}f.suggest("show");i.addClass(d.hotOnClass)}}
var b=this,d=b.options,c=!1,f=b.$suggest,i=b.$hotword;i.click(function(){c?f.suggest("clear"):(c=!0,b._loadHotWord(a),b._trigger("hotwordshow"));b.$input.focus();return!1}).hover(function(){f.suggest("hold",!0)},function(){f.suggest("hold",!1)});f.on("suggesthide",function(){c=!1;i.removeClass(d.hotOnClass);f.suggest("footer","");b._trigger("hotwordhide")})},_loadHotWord:function(a){var b=this;b.hotURL&&(a=a||d,$.ajax({dataType:"json",url:b.hotURL,cache:!0,data:{r:~(new Date/18E5)},success:function(d){a.call(b,
d)}}))},_bindAdvancedEvent:function(){function a(a){if(a&&a.data){var b,d,e,a=a.data;for(b=1,e=0;10>=b;b++){d=a[b];if(!d)break;d.isnew&&e++}e&&(a=e,r?r.text(a).show():r=$(j(m.hotNumTpl,{num:a})).appendTo(c.$hotword).css({height:0,top:9}).animate({height:18,top:-7}))}}function d(){p&&(q?q.show():(q=$(m.yindaoTibTpl).appendTo(c.$wrapper),t=$(".hot-close",q),setTimeout(function(){q.fadeIn();v=0},v)),t&&t.click(function(){q&&q.remove();l.set(k,1,{expires:30})}))}var c=this,i=c.element,n=null,m=c.options,
o=!l.has("index_searchhint"),p=!l.has(k),r,q,t,v=1900,w=h.get("searchtip")-0;$(document).on("floatstart",function(){c.isfloat=!0});$(document).on("floatend",function(){c.isfloat=!1});i.on("searchtabchange searchinit",function(i,h){var g=b(h.currTab),k;if(g){k=g.hotword;""==f&&c.$input.focus();c.$logoImg.attr({alt:g.alt,src:g.logo});c.$logoLink.attr({title:g.alt,href:g.url});c.$form.attr({action:g.action});c.$input.attr({name:g.query});n=g.params;c.$suggest.suggest("handler",g.sug);if((c.hotURL=k)&&
o)r&&r.hide(),c._loadHotWord(a);c.$hotword.toggle(!!k);w&&(k?d():(q&&q.remove(),q=null))}}).on("searchsubmit",function(a,b){var d=g({},n),e;if("suggest"==b.from||"hotword"==b.from)g(d,{f:3,rsp:b.suggestIndex-1}),(e=b.suggestData)&&e.suggestId&&g(d,{rsv_sug5:e.suggestId});c.isfloat&&c._trigger("floatsubmit");c.params(d)}).on("searchhotwordshow",function(){o&&(r&&r.remove(),l.set("index_searchhint",1,{expires:1}),o=!1);w&&p&&(l.set(k,1,{expires:30}),q&&q.remove())})},params:function(a,b){var d=this.options.paramTpl,
c,f,i;1<arguments.length?(this._params||(this._params={}),c=this._params,c[""+a]=b):c=this._params=a;i=[];for(f in c)c.hasOwnProperty(f)&&i.push(j(d,{name:f,value:c[f]}));this.$params.html(i.join(""))}});return m});
__d("widget.logo.logo",["common.js.widget","common.js.format","common.js.fixpng","common.js.browser"],function(o,p,m,c,g){function j(b){b=parseInt(b);return isNaN(b)?0:b}c("common.js.widget");c("common.js.format");var l=c("common.js.fixpng"),h=c("common.js.browser");$.widget("hao123.logo",{options:{url:"",title:"",target:"",style:"",imgurl:"",swfurl:"",width:0,height:0,defaultWidth:210,defaultHeight:68},_create:function(){var b=this,c=b.element;b.$img=$(".img-hook",c);b.$link=$(".link-hook",c);b.$flash=
null;b.$link.click(function(c){return b._trigger("click",c)}).attr("hidefocus","true")},_init:function(){var b=this.options;b.width=j(b.width)||b.defaultWidth;b.height=j(b.height)||b.defaultHeight;this._trigger("beforeload")&&(this.$link.attr({href:b.url,title:b.title,target:b.target}),this.$img.attr({width:b.width,height:b.height,alt:b.title}),b.swfurl?!h.isIpad()&&!h.safari&&this.setFlash(b.swfurl):this.setImage(b.imgurl))},setFlash:function(b){var c=this,h,f=c.options;g(["common.js.swf"],function(d){if(h=
d.createHTML({url:b,width:parseInt(f.width),height:parseInt(f.height),wmode:"transparent"}))c.$flash||(c.$flash=$('<div class="card flash"></div>').insertBefore(c.$link),c.$flash.html(h)),c.$img.fadeOut(function(){c.$img.attr("src","http://s0.hao123img.com/img/1L/Aw/2F/mk/ch/o/blank.gif").show()})})},setImage:function(b){this.$img.attr("src",b);l(this.$img,b.replace(/^(.+)\.png(\?.*)?$/,"$1-24.png$2"))}});return m});
__d("widget.navigate.navigate",["common.js.widget","common.js.cookie","common.js.events","common.js.profile","common.js.browser"],function(o,p,m,c){c("common.js.widget");var g=c("common.js.cookie"),j=c("common.js.events"),l=c("common.js.profile"),h=c("common.js.browser");$.widget("hao123.navigate",{options:{profileKey:"navigate",hoverCls:"hover",upCls:"up",loadingCls:"loading",objID:"box-navigate",cookieTip:"tip-navmore",tipCls:"url(http://s0.hao123img.com/res/img/navmore-tip.png) no-repeat 0 0",
lastCls:"last_rollup",navmoreCls:"nav_more_rollup",moreHeight:105},_create:function(){var b=this.element;this.$navigates=$(".js_item a",b);this.$pics=$(".js_tab .icon",b);this.$ie6pics=$(".js_tab .ie6-icon",b);this.$navmore=$(".js_nav_more",b);this.$morelist=$(".js_more_list",b);this.$tip=$(".js_navmore-tip",b);this.$tipClose=$(".js_tip-close",b);this.$navlast=$(".last",b);this.moreshow=!1;this.animation={};this.navloading={};this.navMap={tab_default:0,tab_tv:1,tab_film:2,tab_news:3,tab_ent:4,tab_military:5,
tab_game:6,tab_gouwu:7,tab_novel:8,tab_short:9,tab_tuan:10};this.moreMap={tab_gouwu:0,tab_novel:1,tab_short:2,tab_tuan:3};this._bindEvent()},_init:function(){},navMoreAnimation:function(){var b=this;0==l.get("navmore")&&(b.downTimer=setTimeout(function(){b.moreshow||b._rollDown();b.upTimer=setTimeout(function(){b.moreshow&&b._rollUp()},4E3)},1E3))},_showTip:function(){var b=this.options;"1"!=g.get(b.cookieTip)&&this.$tip.show().css("background",b.tipCls).animate({top:-28,height:34})},_closeTip:function(){var b=
this.options;this.$tip.fadeOut();g.set(b.cookieTip,"1",{expires:30})},_reset:function(){var b=this,c=this.options;this.$navigates.each(function(h){if($(this).hasClass(c.loadingCls)){var f=-20*b.navMap[$(this).data("tab")];$(this).removeClass(c.loadingCls);b._isIE6()?$(this).find("s").show():$(this).find("i").css("background-position",f+"px -20px")}b.navloading[h]=!1})},_bindEvent:function(){var b=this,c=b.options,h=function(){b.$navigates.each(function(f){$(this).hasClass(c.hoverCls)&&$(this).removeClass(c.hoverCls);
b.animation[f]=!1})};this.$navigates.hover(function(){h();"current"!=$(this).data("current")&&($(this).addClass(c.hoverCls),b.animation[$(this).data("index")]=!0,b._animationLoop($(this),b._isIE6()))},function(){h()});this.$tipClose.click(function(){b._closeTip();return!1});this.$navigates.click(function(){var c;"current"!=$(this).data("current")&&(j.emit("navigate.tabchange",$(this).data("index")),void 0!==(c=b.moreMap[$(this).data("tab")])&&l.set("navmore",c))});this.$navmore.click(function(){b.moreshow?
b._rollUp():(b._closeTip(),b._rollDown());clearTimeout(b.upTimer);clearTimeout(b.downTimer);return!1});$(document).bind("click",function(){b._rollUp()});j.on("navigate.tabchange",function(f){var d,a;d=b.$navigates.eq(f);a=b._isIE6();b._reset();d.addClass(c.loadingCls);b.navloading[f]=!0;d.find("i").css("background-position","0px 0px");a&&(f=d.find("s"),f.hide())})},_rollUp:function(b){var c=this,h=c.options;c.$morelist.stop().animate({height:0},"fast",function(){c.$navlast.removeClass(h.lastCls);
c.$navmore.removeClass(h.upCls);c.$navmore.removeClass(h.navmoreCls);c.moreshow=!1;b&&b.call(c)})},_rollDown:function(){var b=this,c=b.options;b.$morelist.stop().animate({height:c.moreHeight},"fast",function(){b.$navlast.addClass(c.lastCls);b.$navmore.addClass(c.upCls);b.$navmore.addClass(c.navmoreCls);b.moreshow=!0})},_animationLoop:function(b,c){function h(){f.navloading[b.data("index")]||(10==j||!f.animation[b.data("index")]?c?e.css(g,-20):e.css(g,a+"px -20px"):(d=20*-j,c?e.css(g,d):e.css(g,a+
"px "+d+"px"),j++,setTimeout(h,50)))}var f=this,d=0,a=20*-this.navMap[b.data("tab")],e=c?b.find(".ie6-icon"):b.find("i"),g=c?"margin-top":"background-position",j=1;h()},_isIE6:function(){return 6==h.ie}});return m});
__d("widget.gvmusictip.gvmusictip",["common.js.widget","common.js.cookie","common.js.log","common.js.swf","common.js.browser"],function(o,p,m,c){c("common.js.widget");var g=c("common.js.cookie"),j=c("common.js.log"),l=c("common.js.swf"),h=c("common.js.browser");$.widget("hao123.gvmusictip",{options:{},_create:function(){var b=this.element;this.$gvmusicrecommond=$("#gvmusic-recommond",b);this.$gvmusictip=$("#gvmusictip");this.$close=$("#gvmusic-recommond i",b)},_isIE6:function(){return 6==h.ie},_init:function(){l.version&&
(this._bindEvent(),void 0==g.get("goodvoice")&&(this.options.data3[0].name!=this.options.data[0].name?(this._isIE6()&&this.$close.addClass("iepng"),this.$gvmusicrecommond.addClass("commonuse skinenter")):this.$gvmusicrecommond.addClass("commonuse changegvskin"),$("#gvmusic_tip").show()))},_bindEvent:function(){this.$close.click(function(){g.set("goodvoice",1);$("#gvmusic_tip").remove();j({type:"gvclose"});return!1})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return m});
__d("widget.navigate.tabtip",["common.js.widget","common.js.config","common.js.format","common.js.log","common.js.cookie"],function(o,p,m,c){c("common.js.widget");var g=c("common.js.config"),j=c("common.js.format"),l=c("common.js.log");c("common.js.cookie");$.widget("hao123.tabtip",{options:{data:null,pageId:""},_create:function(){var c=this.element;this._getCurIndex();var b=this._madeData(),i="",i=null;this.items=$(".js_tab li",c);i=this.options.pageId=g.get("pageId");this.tipData=i=b[i]?b[i]:b["default"];
c=(new Date).getTime();1E3*i.start<c&&c<1E3*i.stop&&this._createTipHtml(i.module.split("|")[0],i.text)},_madeData:function(){var c=this.options.data,b=null,g=0,j={};if(null!=c)for(var g=c.length,f=0;f<g;f++)b=c[f],b.module&&(b.module.split("|")[1]?j[b.module.split("|")[1]]=b:j["default"]=b);return j},_createTipHtml:function(c,b){function g(a){a=a||0;f.timer&&(clearTimeout(f.timer),f.timer=null);var b=(new Date).getTime();1E3*f.tipData.start>b&&b>1E3*f.tipData.stop||(f.timer=setTimeout(function(){k()},
a))}function k(){o=!0;a.delay(2E3).animate({top:"-8"},{duration:500,easing:"linear",step:function(a){0>=a&&d.css({overflow:"visible"})}}).delay(1E3).animate({top:"-10"},0).delay(200).animate({top:"-8"},0).delay(200).animate({top:"-10"},0).delay(200).animate({top:"-8"},0).delay(5E3).animate({top:"42"},{duration:500,easing:"swing",step:function(a){0<=a&&d.css({overflow:"hidden"})},complete:function(){o=!1;g(n)}})}var f=this,c=c||0,d=f.items[c]?$(f.items[c]):null,a=null,e=null,m={},o=!1,n=6E4;f.timer=
null;d&&!d.hasClass("option-selected")&&0>=$(".tabtip",d).length&&(d.css({position:"relative",overflow:"hidden"}),e=$(".channel",d).eq(0),0<e.length&&(m.href=e.attr("href"),m.rel=e.attr("rel"),m.imgurl=b),a=$(j('<a class="channel tabtip" href="#{href}" rel="#{rel}" hidefocus="true" style="background:url(#{imgurl}) no-repeat 0px 0px;"></a>',m)).appendTo(d),g(0),a.click(function(){l({type:"tabtip"})}),d.hover(function(){o||(f.timer&&clearTimeout(f.timer),a.stop(),a.css({top:"-8px"}),d.css({overflow:"visible"}))},
function(){o||(g(n),a.stop(),d.css({overflow:"hidden"}),a.css({top:"42px"}))}))},_getCurIndex:function(){var c=g.get("currentProfile");return c&&c.navigate?c.navigate:""},_init:function(){}});return m});window.js_bxcWAcgGbu&&window.js_bxcWAcgGbu(!0);
