__d("widget.s_gw11slider2.bigcpc",["common.js.widget","common.js.cpc","common.js.format"],function(i,j,f,c){c("common.js.widget");var a=c("common.js.cpc"),g=c("common.js.format");$.widget("hao123.bigcpc",{options:{},_create:function(){this.ctx=this.element;this.menus=$(".js_point",this.ctx);this.cts=$(".js_grid",this.ctx)},_init:function(){this._tab();this._renderCpc()},_renderCpc:function(){var b=this,d={1010101:[],1010102:[],1010103:[],1010104:[],1010105:[],1010106:[]},k={"0":"1010101",1:"1010103",
2:"1010105",3:"1010102",4:"1010104",5:"1010106"};a({at:64,w:185,h:152},function(h){if(h&&h.ad&&0<h.ad.length)for(var l=h.ad,h=h.ad.length,a,e=0;e<h;e++)(a=l[e])&&a.adtd&&d[a.adtd].push(a);for(var l=['<a class="g-ib mini" href="http://mobads.baidu.com/ad.html?url=#{url}" cls="cpc">','<img src="#{img}" width=185 height=152 /><img class="logimg"  src="#{log}" />','<span class="des g-ib">#{title}</span>',"</a>",'<div class="active_bg active_bg-hook"></div>'],c,e=0;6>e;e++)if(k&&k[e]&&(c=d[k[e]])&&0<c.length){a=
c.length;for(var f=0;f<a;f++)(h=c[f]||{})&&h.curl&&h.w_picurl&&h.tit&&h.clklogurl&&$(".item0"+(f+1),$(b.cts[e])).html(g(l.join(""),{url:encodeURIComponent(c[f].curl),img:c[f].w_picurl,log:c[f].clklogurl+"&v=pA7EnHc1g1D8nafb&extra2=nj0snjDsnj0snj0snj0sniskrHTsnjDsnH0snj0sn0Cb",title:c[f].tit||""}))}},function(){b._mask()})},_tab:function(){function b(b){d.menus.each(function(g){b==g?($(d.menus[g]).addClass("selected"),$(d.cts[g]).show()):($(d.menus[g]).removeClass("selected"),$(d.cts[g]).hide())})}
var d=this;d.menus.bind("mouseover",function(d){b($(this).attr("data-index"));d.preventDefault();return!1});d.menus.bind("click",function(b){b.preventDefault();return!1})},_mask:function(){var b=this;b.$items=$(".item-hook",b.ctx);b.$activebg=$(".active_bg-hook",b.ctx);b.$slides=$(".slides-hook",b.ctx);b.$slides.hover(function(){b.$activebg.each(function(){$.contains(b.current,this)||$(this).show().stop().animate({opacity:0.6})})},function(){b.$activebg.each(function(){$(this).stop().animate({opacity:0},
function(){$(this).hide()})})});b.$items.hover(function(){b.current=this;$(this).find(".active_bg-hook").stop().css({opacity:0}).hide()},function(){$(this).find(".active_bg-hook").show().stop().animate({opacity:0.6})})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return f});
__d("widget.s_cpc.smallcpc",["common.js.widget","common.js.cpc","common.js.format"],function(i,j,f,c){c("common.js.widget");var a=c("common.js.cpc"),g=c("common.js.format");$.widget("hao123.smallcpc",{options:{},_create:function(){this.ctx=this.element;this.cpcimgs=$(".sidepicture .item",this.ctx);this.cpctexts=$(".sidelink .item",this.ctx)},_init:function(){this._renderCpc()},_renderCpc:function(){var b=this;a({at:32,w:60,h:60},function(d){if(d&&d.ad&&0<d.ad.length)for(var d=d.ad,k=d.length,h=['<img src="#{img}" data-src="#{img}" width="60" height="60" title="#{title}" class="g-br1 pic">',
'<span class="name" href="http://www.qiushibaike.com/">#{title}</span>','<img src="#{log}" class="g-logimg" />'],a,c,e=0;e<k;e++)if(a=d[e],(c=$(b.cpcimgs[e]))&&a.curl&&a.tit&&a.w_picurl&&a.clklogurl)c.attr({href:"http://mobads.baidu.com/ad.html?url="+encodeURIComponent(a.curl),title:a.tit||""}),c.html(g(h.join(""),{img:a.w_picurl,log:a.clklogurl+"&v=pA7EnHc1g1D8nafb&extra2=nj0snjDsnj0snj0snj0sniskrHTsnjDsnH0snj0sn0Cb",title:a.tit||""}))})},destroy:function(){$.Widget.prototype.destroy.call(this)}});
return f});
__d("widget.xingzuo.xingzuo",["common.js.widget","common.js.config","common.js.cookie"],function(i,j,f,c){c("common.js.widget");var a=c("common.js.config"),g=c("common.js.cookie");$.widget("hao123.xingzuo",{options:{starClsPrefix:"star-",selectedCls:"selected",xingzuoKey:"flagStar",flagType:"flagType"},_create:function(){var b=this.element;this.$info=$(".xingzuo-info",b);this.$header=$(".js_luckyHeader",b);this.$name=$(".js_luckyName",b);this.$date=$(".js_luckyDate",b);this.$color=$(".js_luckyColor",b);
this.$num=$(".js_luckyNum",b);this.$astro=$(".js_luckyAstro",b);this.$azimuth=$(".js_luckyAzimuth",b);this.$weekLuck=$(".js_weekLuck",b);this.$monthLuck=$(".js_monthLuck",b);this.$yearLuck=$(".js_yearLuck",b);this.$allStar=$(".js_allStar",b);this.$moneyStar=$(".js_moneyStar",b);this.$loveStar=$(".js_loveStar",b);this.$select=$(".js_select",b);this.$selectText=$(".js_select .select-text",b);this.$popup=$(".js_popup",b);this.$selection=$(".js_popup li",b);this.$paragraph=$(".js_paragraph",b);this.contentShow=
!1},_init:function(){this._initStar(this.$allStar);this._initStar(this.$moneyStar);this._initStar(this.$loveStar);this._bindEvent();a.get("isStatic")&&this._fixStatic()},_fixStatic:function(){var b=g.get(this.options.xingzuoKey),d=this.options.horoscope,a,h,c,f,e,i;b&&(a=d.aries.all_star,h=d[b].all_star,c=d.aries.money_star,f=d[b].money_star,e=d.aries.love_star,i=d[b].love_star,this._showStar(this.$allStar,a,h),this._showStar(this.$moneyStar,c,f),this._showStar(this.$loveStar,e,i),this.$header.removeClass("aries").addClass(b),
this.$name.text(d[b].name),this.$date.text("\uff08"+d[b].date[0]+" - "+d[b].date[1]+"\uff09"),this.$color.text(d[b].luck_color.substr(0,3)),this.$num.text(d[b].luck_num),this.$astro.text(d[b].luck_astro),this.$azimuth.text(d[b].luck_azimuth.substr(0,2)),this.$paragraph.text(d[b].paragraph),this.$selectText.text(d[b].name),this.$select.data("key",b))},_initStar:function(b){this._showStar(b,"",b.data("star"))},_showStar:function(b,d,g){var a=this.options.starClsPrefix;b.removeClass(a+d).addClass(a+
g)},_bindEvent:function(){function b(){a.$selection.each(function(){$(this).removeClass(c.selectedCls)})}function d(b){a.$selection.each(function(){var a=$(this);a.data("key")==b&&a.addClass(c.selectedCls)})}var a=this,c=a.options;this.$select.click(function(b){if(a.contentShow)return a.$popup.hide(),a.contentShow=!1;a.contentShow=!0;a.$popup.show();d($(this).data("key"));b.stopPropagation()});this.$selection.hover(function(){b();$(this).addClass(c.selectedCls)},function(){b()});this.element.hover(function(){a.$info.show()},
function(){a.$info.hide()});this.$weekLuck.click(function(){g.set(c.flagType,"week",{domain:"current"});return!0});this.$monthLuck.click(function(){g.set(c.flagType,"month",{domain:"current"});return!0});this.$yearLuck.click(function(){g.set(c.flagType,"year",{domain:"current"});return!0});this.$header.click(function(){g.set(c.flagType,"",{domain:"current",expires:-1});return!0});this.$allStar.click(function(){g.set(c.flagType,"",{domain:"current",expires:-1});return!0});this.$moneyStar.click(function(){g.set(c.flagType,
"",{domain:"current",expires:-1});return!0});this.$loveStar.click(function(){g.set(c.flagType,"",{domain:"current",expires:-1});return!0});this.$selection.click(function(){var b=$(this).data("key"),d=a.$select.data("key"),e=c.horoscope,f,i,j,m,n,o;f=e[d].all_star;i=e[b].all_star;j=e[d].money_star;m=e[b].money_star;n=e[d].love_star;o=e[b].love_star;a._showStar(a.$allStar,f,i);a._showStar(a.$moneyStar,j,m);a._showStar(a.$loveStar,n,o);a.$header.removeClass(d).addClass(b);a.$name.text(e[b].name);a.$date.text("\uff08"+
e[b].date[0]+" - "+e[b].date[1]+"\uff09");a.$color.text(e[b].luck_color.substr(0,3));a.$num.text(e[b].luck_num);a.$astro.text(e[b].luck_astro);a.$azimuth.text(e[b].luck_azimuth.substr(0,2));a.$paragraph.text(e[b].paragraph);g.set(c.xingzuoKey,b,{domain:"current"});a.$selectText.text($(this).text());a.$select.data("key",b);a.$popup.hide();a.contentShow=!1});$(document).click(function(){a.$popup.hide();a.contentShow=!1})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return f});
__d("widget.toppicture3.toppicture3",["common.js.widget","common.js.lazy"],function(i,j,f,c){c("common.js.widget");var a=c("common.js.lazy");$.widget("hao123.toppicture3",{options:{selectCls:"selected",interval:1E4,lazy:!1},_create:function(){var a=this.element;this.$imgs=$(".js_content li",a);this.$next=$(".js_next",a);this.$pre=$(".js_pre",a)},_init:function(){this.$imgs&&(this._lazyLoad(this.$imgs.find("img")),this.imgCount=this.$imgs.length,this.currentIndex=0,this._bindEvent(),1<this.imgCount&&
this._autoPlay())},_lazyLoad:function(g){this.options.lazy&&(this.lazyKey=a.add(g))},_bindEvent:function(){var a=this;this.$imgs.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)});this.$next.click(function(){a._goNext();a._autoPlay();return!1});this.$pre.click(function(){a._goPre();a._autoPlay();return!1});this.$next.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)});this.$pre.hover(function(){clearTimeout(a.hideTimer);
a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)})},_slideHide:function(){this.$next.hide();this.$pre.hide()},_slideShow:function(){this.$next.show();this.$pre.show()},_autoPlay:function(){var a=this,b=a.options;clearInterval(this.timer);this.timer=setInterval(function(){a._goNext()},b.interval)},_goNext:function(){var a=this.currentIndex;++this.currentIndex==this.imgCount&&(this.currentIndex=0);this._display(a)},_goPre:function(){var a=this.currentIndex;0>--this.currentIndex&&
(this.currentIndex=this.imgCount-1);this._display(a)},_display:function(a){var b=this.options;this.$imgs.eq(a).removeClass(b.selectCls);this.$imgs.eq(this.currentIndex).addClass(b.selectCls);this._animateShow(a)},_animateShow:function(a){this.$imgs.eq(a).css({opacity:1}).stop().animate({opacity:0},800);this.$imgs.eq(this.currentIndex).css({opacity:0,display:"block"}).stop().animate({opacity:1},800)},destroy:function(){this.options.lazy&&a.remove(this.lazyKey);clearInterval(this.timer);$.Widget.prototype.destroy.call(this)}});
return f});
__d("widget.relax.relax",["common.js.widget","common.js.lazy"],function(i,j,f,c){c("common.js.widget");c("common.js.lazy");$.widget("hao123.relax",{options:{screenCount:3,selectedCLs:"btn-selected"},_create:function(){var a=this.element;this.$screens=$(".js_screens",a);this._initViewport();this.$pre=$(".js_pre",a);this.$next=$(".js_next",a);this.$btns=$(".js_btn",a);this.currentScreen=0},_init:function(){this._bindEvent()},_initViewport:function(){this.$screens.css("width",930*(this.options.screenCount+1))},
_bindEvent:function(){var a=this;this.$pre.click(function(){a._goPre();return!1});this.$next.click(function(){a._goNext();return!1});this.$btns.click(function(){a._goPos(a.currentScreen,$(this).data("index"))})},_goPos:function(a,c){var b=this,d;d=c-a;0!=d&&(this.currentScreen=c,this.$screens.animate({left:"-="+930*d},500,"linear",function(){b._updateBtns()}))},_goPre:function(){var a=this,c=this.options;this.$screens.is(":animated")||(this.currentScreen--,0>this.currentScreen&&(this.currentScreen=
c.screenCount-1,this.$screens.css("left",930*-c.screenCount)),this.$screens.animate({left:"+=930"},250,"linear",function(){a._updateBtns()}))},_goNext:function(){var a=this,c=this.options;this.$screens.is(":animated")||(this.currentScreen++,this.$screens.animate({left:"-=930"},250,"linear",function(){a.currentScreen==c.screenCount&&(a.currentScreen=0,a.$screens.css("left",0));a._updateBtns()}))},_updateBtns:function(){var a=this,c=this.options;this.$btns.each(function(){$(this).removeClass(c.selectedCLs);
$(this).data("index")==a.currentScreen&&$(this).addClass(c.selectedCLs)})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return f});
__d("widget.music.music",["common.js.widget","common.js.lazy","common.js.browser","common.js.cookie"],function(i,j,f,c){c("common.js.widget");var a=c("common.js.lazy"),g=c("common.js.browser"),b=c("common.js.cookie");$.widget("hao123.music",{options:{src:"http://play.baidu.com/player/hao123/index_new.html#top/dayhot",width:246,height:293,tipCls:"url(http://s0.hao123img.com/res/img/music-tip.png) no-repeat 0 0",cookieTip:"musicTip"},_create:function(){var a=this.element;this.$tip=$("#music-tip",a);
if(this.ie6=6==g.ie)this.$cover=$("#music-cover",a),this.$loading=$("#music-loading",a),this.$loadingImg=$("#music-loading img",a);this.$tipClose=$(".js_close",a)},_init:function(){var b=this;this.lazyKey=a.add(this.element,function(){b._showMuiscTip();b.ie6?b.$cover.hover(function(){$(this).hide();b._showLoading();b._createIframe();b._bindEvent()}):(b._createIframe(),b._bindEvent())})},_showLoading:function(){this.$loading.show();a.add(this.$loadingImg)},_createIframe:function(){var a=this,b=this.options,
c=document.createElement("iframe");c.id="frame-music";c.src=b.src;c.width=b.width;c.height=b.height;c.scrolling="no";c.frameBorder=0;this.element.append(c);this.ie6&&$("#frame-music").load(function(){a.$loading.fadeOut()})},_showMuiscTip:function(){var a=this.options;"1"!=b.get(a.cookieTip)&&this.$tip.show().css("background",a.tipCls).animate({top:-40,height:53})},_bindEvent:function(){var a=this,c=a.options;this.element.hover(function(){$(this).css({height:293})},function(){$(this).css({height:26})});
this.$tipClose.click(function(){a.$tip.fadeOut();b.set(c.cookieTip,"1");return!1})},destroy:function(){a.remove(this.lazyKey);$.Widget.prototype.destroy.call(this)}});return f});window.js_fXYZudXGJD&&window.js_fXYZudXGJD(!0);
