__d("widget.tabgame.tabgame",["common.js.widget","common.js.lazy"],function(l,m,h,e){e("common.js.widget");var b=e("common.js.lazy");$.widget("hao123.tabgame",{_init:function(){this.lazyKey=b.add($("#widget-tab-game img"));var e=function(a){function i(a){d.attr("tab-cur",a);d.find(".pages .item[key='"+a+"']").addClass("cur").css({opacity:0}).animate({opacity:1},function(){$(this).css({opacity:""})}).siblings(".cur").removeClass("cur");d.find(".controler .item[key='"+a+"']").addClass("cur").siblings(".cur").removeClass("cur");
d.trigger("switch",a)}var b=0,d=$(a),a=d.attr("tab-switcher")||"click",c=parseInt(d.attr("tab-interval"))||0,e=d.find(".pages>.item").length,k=!1;i(0);d.find(".controler").on(a,".item",function(){var a=$(this).attr("key");i(a)});0<c&&setInterval(function(){var a=new Date;a-b<c||(b=a,k||(a=parseInt(d.attr("tab-cur"))||0,i((a+1)%e)))},c);d.on("mouseenter",function(){k=!0}).on("mouseleave",function(){k=!1});d.find(".controler .prev").on("click",function(){var a=parseInt(d.attr("tab-cur"))||0;0<a&&i(a-
1)});d.find(".controler .next").on("click",function(){var a=parseInt(d.attr("tab-cur"))||0;a<e-1&&i(a+1)});return d};if(l.navigator.userAgent.match(/MSIE\s+[0-6]/))$("[ie6-fix=hover]").on("mouseenter",function(){$(this).addClass("hover")}).on("mouseleave",function(){$(this).removeClass("hover")});$(".slider").each(function(){e(this)})},destroy:function(){b.remove(this.lazyKey);$.Widget.prototype.destroy.call(this)}});return h});
__d("widget.ipad.ipad",["common.js.widget","common.js.cookie","common.js.log"],function(l,m,h,e){e("common.js.widget");var b=e("common.js.cookie"),o=e("common.js.log");$.widget("hao123.ipad",{options:{},_create:function(){var a=this.element;this.$ipad=$("#ipad-box");this.$ipadbtn=$("#js_ipadbtn",a);this.$ipadclose=$("#js_ipadclose",a)},_init:function(){"1"!=b.get("ipds1")&&(this.$ipad.show(),this._bindEvent())},_bindEvent:function(){var a=this;this.$ipadbtn.click(function(){o({position:"ipad"})});
this.$ipadclose.click(function(){b.set("ipds1","1");a.$ipad.slideUp()})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return h});
__d("widget.gameslider.gameslider",["common.js.widget"],function(l,m,h,e){e("common.js.widget");$.widget("hao123.gameslider",{options:{timer:null,delay:5E3,curindex:1,flag:!0},_init:function(){this.gamesliderscroll()},gamesliderscroll:function(){function b(){g=setInterval(function(){a($(".focus-pic-btns .next"))},5E3)}function e(a){if(i){var b=a.attr("class"),d=a.parent().prev().find(".item"),c=d.size(),n=1,g=d.width(),f=a.parent().attr("data-index")-0;if(1>=c)return!1;~b.indexOf("next")?n=!0:n=!1;
d.eq(f).animate({left:n?-g:g},function(){$(this).removeAttr("style");i=!0});n?f==c-1?f=0:f++:0==f?f=c-1:f--;!n&&d.eq(f).attr("style","left:-"+g+"px;");d.eq(f).animate({left:0});a.parent().attr("data-index",f);j.attr("id")&&"true"==a.parent().attr("data-focus")&&(a=d.parent().find("li").eq(f).find("a:eq(0)"),k.find("a").removeClass("cur"),a.addClass("cur"),j.html('<a href="'+a.attr("href")+'" target="_blank" data-index='+a.attr("data-index")+'><img src="'+a.attr("data-src")+'" width="400" height="224"><span class="bg"></span>'+
(a.attr("video")?'<span class="v"></span>':"")+'<span class="title '+a.attr("video")+'">'+a.attr("title")+"</span></a>"))}i=!1}function a(a){$("#widget-focus-pic").find("img");var d=j.find("a").attr("data-index")-0,b=$("#focus_pic_list a"),i=b.size()-1,c="",a=a.attr("class"),c=0;"prev"==a?c=0==d?i:d-1:"next"==a&&(c=d==i?0:d+1);0==c%4&&"next"==a?e(k.find(".next")):(0==(c+1)%4||c==i)&&"prev"==a&&e(k.find(".prev"));c=b.eq(c);c.find("img");b.removeClass("cur");c.addClass("cur");c.attr("data-src")&&j.html('<a href="'+
c.attr("href")+'" target="_blank" data-index='+c.attr("data-index")+'><img src="'+c.attr("data-src")+'" width="400" height="224"><span class="bg"></span>'+(c.attr("video")?'<span class="v"></span>':"")+'<span class="title '+c.attr("video")+'">'+c.attr("title")+"</span></a>")}var i=!0,f=$(".gameslider-wrap"),d=$("#main_focus_pic",f),c=$(".focus-pic-btns span",f),p=$(".list-btns span",f),k=$("#focus_pic_list"),j=$("#widget-focus-pic"),g=0;p.on("click",function(){e($(this))});k.find("a").on("mouseover",
function(){var a=$(this);k.find(".scroll-warp a").removeClass("cur");a.addClass("cur");j.html('<a href="'+a.attr("href")+'" target="_blank" data-index='+a.attr("data-index")+'><img src="'+a.attr("data-src")+'" width="400" height="224"><span class="bg"></span>'+(a.attr("video")?'<span class="v"></span>':"")+'<span class="title '+a.attr("video")+'">'+a.attr("title")+"</span></a>")});d.on("mouseenter",function(){c.show()}).on("mouseleave",function(){c.hide()});c.on("click",function(){a($(this))});f.on("mouseover",
function(){clearInterval(g)}).on("mouseout",function(){b()});b()}});return h});
__d("widget.menus.menus",["common.js.widget","common.js.events","common.js.format","common.js.once"],function(l,m,h,e){e("common.js.widget");e("common.js.events");var b=e("common.js.format"),o=e("common.js.once");$.widget("hao123.menus",{options:{data:null,current:"",tpl:"<div class='recommend' data-playtime='#{time}' data-key='#{key}' style='left:#{left}px;display:none'><a monkey='tabtip_#{key}' hidefocus='true' href='/api/ajax?menu=#{key}#{params}' rel='hao123-bodyct'><img width='110' height='60' src=#{url}/></a></div>"},_create:function(){this.$items=
$(".menu",this.element)},_init:function(){var a=this,i=a.options,e=i.data,d=i.current;a.urlmap={};a.$recommends={};$.each(e,function(c,e){var f,j,g=e.title,h=e.data[0].imgurl,l="",m=e.playtime;a.urlmap[g]=[];$.each(e.data,function(c,d){a.urlmap[g].push(d.imgurl)});a._proLoadImg(a.urlmap[g]);g!=d&&(f=a._getLeft(g),""!=a.element.attr("params")&&(l=a.element.attr("params")),j=$(b(i.tpl,{left:f,key:g,url:h,params:l,time:m})),j.appendTo(a.element),a.$recommends[g]=j,o("menu_animation_"+g,function(){a._show(j)}))});
a._bindEvent()},_getLeft:function(a){var b=!1;this.$items.each(function(e,d){var c=$(d);c.data("key")==a&&(b=115+110*(c.data("index")-1))});return b},_show:function(a){var b=this;a.isShow=!0;a.show().animate({top:-13,height:60},function(){b._doAnimation(a,b.urlmap[a.data("key")])})},_hide:function(a){a.animate({top:40,height:0},function(){a.hide();a.isShow=!1})},_doAnimation:function(a,b){function e(){d.disposing?g=null:k++==j?(d._hide(a),g=null):(h++==c&&(h=0),1<c&&g.attr("src",b[h]),setTimeout(e,
200))}var d=this,c=b.length,h=0,k=0,j=parseInt(5*a.data("playtime")),g=a.find("img");setTimeout(e,50)},_proLoadImg:function(a){function b(){if(d!=e){var c=new Image,h=a[d++];c.onload=c.onerror=function(){setTimeout(b,20);c=c.onload=c.onerror=null};c.src=h}}var e=a.length,d=0;b()},_bindEvent:function(){var a=this;a.$items.on("mouseover",function(){var b=$(this).data("key");(b=a.$recommends[b])&&!b.isShow&&a._show(b)})},destroy:function(){this.disposing=!0;$.Widget.prototype.destroy.call(this)}});return h});
__d("widget.placeHolder.placeHolder",["common.js.widget"],function(l,m,h,e){e("common.js.widget");$.widget("hao123.placeHolder",{options:{defaultVal:"",defaultCls:""},_create:function(){this._bindEvent()},_init:function(){this.setDefaultValue()},_bindEvent:function(){var b=this;b.element.focus(function(){0==b.state&&(b._clearValue(),b.state=1);b._trigger("focus")});b.element.blur(function(){""==b.val()&&b.setDefaultValue();b._trigger("blur")})},setDefaultValue:function(){var b=this.options;this.element.addClass(b.defaultCls).val(b.defaultVal);
this.state=0},_clearValue:function(){this.element.removeClass(this.options.defaultCls).val("")},val:function(b){var e=this.options;if(0<arguments.length)this.element.removeClass(e.defaultCls).val(b),this.state=1;else return 0==this.state?"":this.element.val()},destroy:function(){$.Widget.prototype.destroy.call(this)}});return h});window.js_gLTvCJgpcd&&window.js_gLTvCJgpcd(!0);
