__d("common.js.JSON",[],function(){"object"!==typeof JSON&&(JSON={});(function(){function m(f){return 10>f?"0"+f:f}function p(f){b.lastIndex=0;return b.test(f)?'"'+f.replace(b,function(c){var d=g[c];return"string"===typeof d?d:"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+f+'"'}function l(f,c){var d,h,a,b,n=e,g,o=c[f];o&&"object"===typeof o&&"function"===typeof o.toJSON&&(o=o.toJSON(f));"function"===typeof i&&(o=i.call(c,f,o));switch(typeof o){case "string":return p(o);case "number":return isFinite(o)?
""+o:"null";case "boolean":case "null":return""+o;case "object":if(!o)return"null";e+=j;g=[];if("[object Array]"===Object.prototype.toString.apply(o)){b=o.length;for(d=0;d<b;d+=1)g[d]=l(d,o)||"null";a=0===g.length?"[]":e?"[\n"+e+g.join(",\n"+e)+"\n"+n+"]":"["+g.join(",")+"]";e=n;return a}if(i&&"object"===typeof i){b=i.length;for(d=0;d<b;d+=1)"string"===typeof i[d]&&(h=i[d],(a=l(h,o))&&g.push(p(h)+(e?": ":":")+a))}else for(h in o)Object.prototype.hasOwnProperty.call(o,h)&&(a=l(h,o))&&g.push(p(h)+(e?
": ":":")+a);a=0===g.length?"{}":e?"{\n"+e+g.join(",\n"+e)+"\n"+n+"}":"{"+g.join(",")+"}";e=n;return a}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+m(this.getUTCMonth()+1)+"-"+m(this.getUTCDate())+"T"+m(this.getUTCHours())+":"+m(this.getUTCMinutes())+":"+m(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,j,g={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;"function"!==typeof JSON.stringify&&(JSON.stringify=function(f,c,d){var h;j=e="";if("number"===typeof d)for(h=0;h<d;h+=1)j+=" ";else"string"===typeof d&&(j=d);if((i=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return l("",
{"":f})});"function"!==typeof JSON.parse&&(JSON.parse=function(f,c){function d(a,h){var n,f,g=a[h];if(g&&"object"===typeof g)for(n in g)Object.prototype.hasOwnProperty.call(g,n)&&(f=d(g,n),void 0!==f?g[n]=f:delete g[n]);return c.call(a,h,g)}var h,f=""+f;k.lastIndex=0;k.test(f)&&(f=f.replace(k,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(f.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return h=eval("("+f+")"),"function"===typeof c?d({"":h},""):h;throw new SyntaxError("JSON.parse");})})();return JSON});
__d("common.js.cookieKeys",[],function(m,p,l){return l={BAIDUID:1,FLASHID:1,loc2:1,HUM:1,HUN:1,HCD_0:1,flagStar:1,musicTip:1,"static":1,index_searchhint:1,site_shave_hint:1,ipds1:1,site_recommend2:1,tp:1,tp0:1,tp1:1,tp2:1,tp3:1,TIMELINETYPE:1,TNTMT:1,type_msg:1,qr_notshow:1,tvtip_notshow:1,nolifetip:1,sitehint:1,sitebanner:1,topbanner:1,site_inactive:1,tipqixi:1,swaylogo:1,stip0:1,stip1:1,stip2:1,goodvoice:1,lbs:1,toptip:1,cjqjf:1,qjf:1,flagType:1,"tip-navmore":1,ftip:1,tu:1,lg:1}});
__d("common.js.cookie",["common.js.cookieKeys"],function(m,p,l,k){function b(a){a in c||f(a);a=d.cookie.match("(?:^|; )"+h.encodeURIComponent(a)+"=([^;]+)");return null===a?void 0:h.decodeURIComponent(a[1])}function e(a,d,c){return j(encodeURIComponent(a),encodeURIComponent(d),c)}function j(a,h,n){n=n||{};void 0===n.expires&&(n.expires=365);!(a in c)&&0!==n.expires&&f(a);n.path=n.path||"/";n.secure=n.secure||!1;n.domain=n.domain||".hao123.com";a=a+"="+h;if(0===n.expires)h="";else{var h=n.expires,
g=new Date;g.setTime(g.getTime()+864E5*h);h=";expires="+g.toUTCString()}a=a+h+";path="+n.path+(n.secure?";secure":"");"current"!=n.domain&&(a+=";domain="+n.domain);d.cookie=a}function g(){var a=b("BAIDUID");if(a)return a.split(":")[0]}function i(){var a=b("FLASHID");if(a)return a.split(":")[0]}function f(a){throw Error("\u8bf7\u5728/common/js/cookieKeys.js \u91cc\u6dfb\u52a0 "+a+" \u4e3a\u767d\u540d\u5355");}var c=k("common.js.cookieKeys"),d=m.document,h=m.window;return l={getRaw:function(a){a in
c||f(a);a=d.cookie.match("(?:^|; )"+a+"=([^;]+)");return null===a?void 0:a[1]},setRaw:j,get:b,set:e,remove:function(a){e(a,"",{expires:-1})},has:function(a){return void 0===b(a)?!1:!0},getBaiduId:g,getFlashId:i,getCSRFId:function(){var a=i();a||(a=g());return a}}});
__d("common.js.fixpng",["common.js.format"],function(m,p,l,k){function b(c,f){var b,e;e=!1;b=g.imgs[c];b||(e=new Image,e.onload=function(){var a,c;b.state=h;c=b.callbacks;for(a=c.length;a--;)c[a].call(window);b.callbacks=null;b.image=null},e.onerror=function(){b.state=a;b.callbacks=null;b.image=null},b={state:d,image:e,callbacks:[]},g.imgs[c]=b,e.src=c);switch(b.state){case d:b.callbacks.push(f);break;case h:f()}}function e(){var a=/msie (\d+\.\d+)/i.test(navigator.userAgent)?+RegExp.$1:void 0;e=
function(){return 6==a};return e()}function j(a,d){var h=a.src,g=d||h;"[object Function]"==q.call(g)&&(g=d(h));b(g,function(){a.src=f;a.style.filter=i(c,{src:g})})}function g(a,c){if(e()){"length"in a||(a=[a]);for(var d=0;d<a.length;d++)j(a[d],c)}}var i=k("common.js.format"),f="http://s0.hao123img.com/img/1L/Aw/2F/mk/ch/o/blank.gif",c='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="#{src}",sizingMethod="scale")',d=1,h=2,a=3,q=Object.prototype.toString;g.imgs={};return g});
__d("common.js.profile",["common.js.config","common.js.cookie","common.js.events"],function(m,p,l,k,b,e){function j(){var d=!0,h=g.get("userinfo").islanding,a;for(a in f)if(f[a]!=c[a]){d=!1;break}d&&!h?i.set("static",1):i.remove("static")}var g=k("common.js.config"),i=k("common.js.cookie");k("common.js.events");var g=k("common.js.config"),f=g.get("currentProfile",{}),c=g.get("defaultProfile",{});1!=g.get("isStatic",1)&&j();return l={get:function(c){return 0<arguments.length?f[c]:f},set:function(d,
h){var a,b;1!=g.get("isStatic",1)&&d in c&&!(f[d]&&f[d]==h)&&(b=f[d],f[d]=h,j(),a="/api/setprof?",a+="c="+i.getCSRFId()+"&key="+(new Date).getTime()+"&k="+encodeURIComponent(d)+"&v="+encodeURIComponent(h)+"&old="+encodeURIComponent(b),e(["common.js.jquery"],function(c){c.ajax({type:"GET",url:a,dataType:"json",error:function(){}})}))}}});
__d("common.js.query",[],function(){var m=location.search,m=m.replace(/^\?+/g,"");var p;p="=";var l={};if(!("string"!==typeof m||0===m.length)){var k=/\+/g,m=m.split("&"),b=m.length;1E3<b&&(b=1E3);for(var e=0;e<b;++e){var j=m[e].replace(k,"%20"),g=j.indexOf(p),i,f,c;0<=g?(i=j.substr(0,g),j=j.substr(g+1)):(i=j,j="");try{f=decodeURIComponent(i),c=decodeURIComponent(j)}catch(d){continue}Object.prototype.hasOwnProperty.call(l,f)?isArray(l[f])?l[f].push(c):l[f]=[l[f],c]:l[f]=c}}return l});
__d("common.js.repeat",["common.js.format"],function(m,p,l,k){var b=k("common.js.format");return function(e,j){var g=[];if("length"in j){for(var i=0,f=j.length;i<f;i++)g.push(b(e,j[i]));return g.join("")}e.head&&g.push(b(e.head,j.head));i=0;for(f=j.body.length;i<f;i++)g.push(b(e.body,j.body[i]));e.foot&&g.push(b(e.foot,j.foot));return g.join("")}});
__d("common.js.swf",[],function(m,p,l){function k(c){return(""+c).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function b(c){var c=c||{},d=c.ver||"6.0.0",h,a,g,b,e;b={};for(e in c)b[e]=c[e];c=b;if(f){h=f.split(".");d=d.split(".");for(b=0;3>b&&!(a=parseInt(h[b],10),g=parseInt(d[b],10),g<a);b++)if(g>a)return""}else return"";b=c.vars;h="classid,codebase,id,width,height,align".split(",");c.align=c.align||"middle";c.classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000";
c.codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0";c.movie=c.url||"";delete c.vars;delete c.url;if("string"==typeof b)c.flashvars=b;else{a=[];for(e in b)d=b[e],a.push(e+"="+encodeURIComponent(d));c.flashvars=a.join("&")}a=["<object "];for(b=0,g=h.length;b<g;b++)d=h[b],a.push(" ",d,'="',k(c[d]),'"');a.push(">");b={wmode:1,scale:1,quality:1,play:1,loop:1,menu:1,salign:1,bgcolor:1,base:1,allowscriptaccess:1,allownetworking:1,allowfullscreen:1,seamlesstabbing:1,
devicefont:1,swliveconnect:1,flashvars:1,movie:1};for(e in c)d=c[e],e=e.toLowerCase(),b[e]&&(d||!1===d||0===d)&&a.push('<param name="'+e+'" value="'+k(d)+'" />');c.src=c.movie;c.name=c.id;delete c.id;delete c.movie;delete c.classid;delete c.codebase;c.type="application/x-shockwave-flash";c.pluginspage="http://www.macromedia.com/go/getflashplayer";a.push("<embed");var i;for(e in c)if((d=c[e])||!1===d||0===d)/^salign$/i.test(e)?i=d:a.push(" ",e,'="',k(d),'"');i&&a.push(' salign="',k(i),'"');a.push("></embed></object>");
return a.join("")}function e(c,d){for(var b=c.length;b--;)b in c&&c[b]===d&&c.splice(b,1);return c}function j(c){if(null===c||void 0===c)return[];if("[object Array]"==Object.prototype.toString.call(c))return c;if("number"!==typeof c.length||"string"===typeof c||"[object Function]"==Object.prototype.toString.call(c))return[c];if(c.item){for(var d=c.length,b=Array(d);d--;)b[d]=c[d];return b}return[].slice.call(c)}var g=/opera(\/| )(\d+(\.\d+)?)(.+?(version\/(\d+(\.\d+)?)))?/i.test(navigator.userAgent)?
+(RegExp.$6||RegExp.$2):void 0,i=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:void 0,f=function(){var c=navigator;if(c.plugins&&c.mimeTypes.length){var d=c.plugins["Shockwave Flash"];if(d&&d.description)return d.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0"}else if(window.ActiveXObject&&!window.opera)for(c=12;2<=c;c--)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+c))return d.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,
".")}catch(b){}}();return l={version:f,createHTML:b,create:function(c,d){var c=c||{},e=b(c)||c.errorMessage||"";d&&"string"==typeof d&&(d=document.getElementById(d));var a=d||document.body,f="beforeEnd";a=a?"string"==typeof a||a instanceof String?document.getElementById(a):a.nodeName&&(1==a.nodeType||9==a.nodeType)?a:null:null;var i;a.insertAdjacentHTML&&!g?a.insertAdjacentHTML(f,e):(i=a.ownerDocument.createRange(),f=f.toUpperCase(),"AFTERBEGIN"==f||"BEFOREEND"==f?(i.selectNodeContents(a),i.collapse("AFTERBEGIN"==
f)):(f="BEFOREBEGIN"==f,i[f?"setStartBefore":"setEndAfter"](a),i.collapse(f)),i.insertNode(i.createContextualFragment(e)))},getMovie:function(c){var d=document[c],b;return 9==i?d&&d.length?1==(b=e(j(d),function(a){return"embed"!=a.tagName.toLowerCase()})).length?b[0]:b:d:d||window[c]}}});
__d("common.js.storage",["common.js.events"],function(m,p,l,k,b,e){function j(){o>=q||(o=q,c=[],f(function(a){if(a){d=a;o=n;var a=c.length,b,f,e;for(b=0;b<a;b++)f=c[b],e=f[0],f=f[1],g(e,f);s.done("storage.ready")}else o=t,s.done("storage.fail")}))}function g(a,c){if("[object Function]"==u.call(c)){var b=h?null:d.get(a);c.call(null,h,b)}else h||d.set(a,c)}function i(d,b){switch(o){case a:j();case q:c.push([d,b]);break;case n:g(d,b);break;default:h=!0,g(d,b)}}function f(a){function c(a){h=a;f=e;c=function(){};
d(a)}function d(a){var c,b,f;c=i.length;for(b=0;b<c;b++)f=i[b],f(a)}function b(a){var d;a<j?(d=r[a],d(function(d){d?c(d):b(a+1)})):c(!1)}function g(a){i.push(a)}function e(a){setTimeout(function(){a(h)},0)}var h=void 0,i=[],j=r.length;f=g;g(a);setTimeout(function(){b(0)},0)}var c,d,h=null,a=0,q=1,n=2,t=3,o=a,r=[function(a){e(["common.js.swf"],function(c){function d(a){var b,e;(b=i=i||c.getMovie(f))&&(e=b.call("read",[g,""+a]));return e}function b(a,d){var e;(e=i=i||c.getMovie(f))&&e.call("write",
[g,""+a,d])}var f="flashStorage",g="$hao123$",e,h,i;(e=c.createHTML({id:f,url:"http://s1.hao123img.com/index/swf/LocalStorage.swf",width:"1",height:"1",allowscriptaccess:"always",ver:"9.0.0",vars:{width:1,height:1}}))?(h=document.createElement("div"),h.style.cssText="font-size:0;line-height:0;height:1px",document.body.appendChild(h),h.innerHTML=e):a(!1);(function(a){var d,b;b=setInterval(function(){try{if((d=i=i||c.getMovie(f))&&d.flashInit&&d.flashInit())clearInterval(b),a()}catch(e){clearInterval(b)}},
50)})(function(){a({get:d,set:b})})})}],u=Object.prototype.toString,s=k("common.js.events");return l={get:function(a,c){i(a,c)},set:function(a,c){i(a,c)}}});
__d("common.js.localcookie",["common.js.events","common.js.storage","common.js.cookie"],function(m,p,l,k){function b(c){var b,a,f;for(f=0,a=e.length;f<a;f++)b=e[f],b(c,g)}var e,j,g,i=k("common.js.events"),f=k("common.js.storage"),c=k("common.js.cookie");(function(){j=0;e=[];i.on("storage.ready",function(){j=1;b(!0)});i.on("storage.fail",function(){j=2;b(!1)});f.get("FLASHID",function(b,e){var a;b||(e?(a=c.getRaw("FLASHID"),a!=e&&(c.setRaw("FLASHID",e),a=e)):(a=c.getRaw("BAIDUID"),c.setRaw("FLASHID",
a),f.set("FLASHID",a)),g=a&&a.split(":")[0])})})();return l={wait:function(c,b){var a=!1;switch(j){case 0:e.push(function(b,f){!1!==a&&(!0!==a&&clearTimeout(a),c(b,f))});a=void 0!==b?setTimeout(function(){a=!1;c(!1)},b):!0;break;case 1:setTimeout(function(){c(!0,g)},0);break;default:setTimeout(function(){c(!1)},0)}}}});__d("common.js.once",[],function(){var m={};return function(p,l){m[p]||(m[p]="1",l.call())}});
__d("common.js.effect",[],function(m,p,l){(function(){var k={};$.each(["Quad","Cubic","Quart","Quint","Expo"],function(b,e){k[e]=function(e){return Math.pow(e,b+2)}});$.extend(k,{Sine:function(b){return 1-Math.cos(b*Math.PI/2)},Circ:function(b){return 1-Math.sqrt(1-b*b)},Elastic:function(b){return 0===b||1===b?b:-Math.pow(2,8*(b-1))*Math.sin((80*(b-1)-7.5)*Math.PI/15)},Back:function(b){return b*b*(3*b-2)},Bounce:function(b){for(var e,j=4;b<((e=Math.pow(2,--j))-1)/11;);return 1/Math.pow(4,3-j)-7.5625*
Math.pow((3*e-2)/22-b,2)}});$.each(k,function(b,e){$.easing["easeIn"+b]=e;$.easing["easeOut"+b]=function(b){return 1-e(1-b)};$.easing["easeInOut"+b]=function(b){return 0.5>b?e(2*b)/2:1-e(-2*b+2)/2}})})();return l});
__d("common.js.cpc",["common.js.cookie","common.js.jquery"],function(m,p,l,k){function b(b){var e="f503a8d6",f=64,c=185,d=152,h=j||"9BB3FC9DA0FC412EE7C4062ECEF445B4",a;b&&(f=b.at||f,c=b.w||c,d=b.h||d,e=64==f?"f503a8d6":32==f?"b5039c79":"c50380b9",a=e+"_cpr");return{u:"default",id:1,n:20,tm:512,cm:512,md:1,at:f,v:"naked",cs:"",pk:"",q:a||e+"_cpr",appid:e,act:"LP",w:c,sn:h,prod:"hao123",h:d}}var m=k("common.js.cookie"),e=k("common.js.jquery"),j=m.getFlashId();return function(g,i,f){if(g&&"object"==
typeof g){var c=g.url||"http://mobads.e.shifen.com/cpro/ui/mads.php",g=b(g);e.ajax({type:"GET",url:c,data:g,dataType:"jsonp",scriptCharset:"gbk",success:function(b){i&&i(b)},complete:function(b,c){f&&f(b,c)}})}}});
__d("common.js.cpcbll",["common.js.cpc","common.js.format"],function(m,p,l,k){var b=k("common.js.cpc"),e=k("common.js.format");return l={initCpcTxt:function(j,g){g||(g='<a href="#{url}" title="#{title}">#{title}<img src="#{log}" class="g-logimg" /></a>');b({at:1},function(b){if(b&&b.ad&&0<b.ad.length)for(var b=b.ad,f=g,c=b.length,d,h,a=0;a<c;a++)d=b[a],(h=$(j[a]))&&d.curl&&d.tit&&d.clklogurl&&h.html(e(f,{url:"http://mobads.baidu.com/ad.html?url="+encodeURIComponent(d.curl),log:d.clklogurl+"&v=pA7EnHc1g1D8nafb&extra2=nj0snjDsnj0snj0snj0sniskrHTsnjDsnH0snj0sn0Cb",
title:d.tit||""}))})}}});window.js_NefSOjQzTz&&window.js_NefSOjQzTz(!0);
