__d("widget.coolsite.coolsite","common.js.widget,common.js.adjust,common.js.config,common.js.slider,common.js.cookie,common.js.log,common.js.format".split(","),function(f,e,d,b){b("common.js.widget");var c=b("common.js.adjust");b("common.js.config");var a=b("common.js.slider"),i=b("common.js.cookie"),l=b("common.js.log"),o=b("common.js.format");$.widget("hao123.coolsite",{options:{hoverCls:"g-bg1",url:"/api/youxidj"},_init:function(){this.$items=$(".coolsite-item",this.element);c.adjust();this._bindEvent();
this.options.recommend&&this._recommend()},_recommend:function(){var a=this;$.ajax({url:a.options.url,dataType:"json",data:{c:i.getCSRFId()},success:function(b){0==b.code&&a._render(b.data)}})},_render:function(b){if(b){l({type:"kzxyxtj"});var c=b[0],b=c.data,i=Math.ceil(b.length/8),c=c.no,d=$("<li class='recommend recommend-hook'><div class='viewport'><ul class='screen screen-hook'></ul></div><a monkey='gamebar-tab' href='#' class='arrow pre pre-hook'></a><a monkey='gamebar-tab' href='#' class='arrow next next-hook'></a><i class='up'></i></li>"),
f=$("li:nth-child("+c+")",this.element),h=$(".g_fr",f),c=$(".screen-hook",d),e,g,n=!1;d.insertAfter(f).slideDown(function(){$(this).css("overflow","visible")});e=$("<a monkey='gamebar-close' class='fold' href='#'>\u6536\u8d77</a>");h.html(e);h.click(function(){d.slideToggle(function(){$(this).css("overflow","visible");(n=!n)?e.text("\u5c55\u5f00"):e.text("\u6536\u8d77")});return!1});for(var m=0;m<i;m++)for(var f=$("<li monkey='gamebar-app' class='g-ib list'></li>").appendTo(c),k=0;8>k;k++)g=b[k+8*
m],h=$(o("<a class='item' href='#{url}' title='#{title}'><img src='#{img}' width='62' height='62'><span class='desc'>#{title}</span></a>",{url:g.url,img:g.imgurl,title:g.title})).appendTo(f),g.cls&&h.attr("cls",g.cls),7==k&&h.addClass("last");a({context:this.element,slider:".recommend-hook",slides:".screen-hook",prev:".pre-hook",next:".next-hook"})}},_bindEvent:function(){function a(){b.$items.each(function(){$(this).removeClass(c.hoverCls)})}var b=this,c=this.options;this.$items.hover(function(){a();
$(this).addClass(c.hoverCls)},function(){a()})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return d});
__d("widget.toppicture.toppicture",["common.js.widget","common.js.lazy"],function(f,e,d,b){b("common.js.widget");var c=b("common.js.lazy");$.widget("hao123.toppicture",{options:{selectCls:"selected",interval:1E4,lazy:!1},_create:function(){var a=this.element;this.$imglist=$(".js_content li",a);this.$hijacklinks=$(".js_content .hijackclick",a);this.$imgs=this.$imglist.find("img");this.$next=$(".js_next",a);this.$pre=$(".js_pre",a)},_init:function(){this.$imgs&&(this.options.lazy&&c.add(this.$imgs.eq(0)),
this.imgCount=this.$imglist.length,this.currentIndex=0,this.loadMore=this.options.loadMore||!1,this._bindEvent(),1<this.imgCount&&this._autoPlay())},_bindEvent:function(){var a=this;this.$imglist.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$next.click(function(){a._goNext();a._autoPlay();return!1});this.$pre.click(function(){a._goPre();a._autoPlay();return!1});this.$next.hover(function(){clearTimeout(a.hideTimer);
a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$pre.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$hijacklinks.click(function(){var b=$(this).index();a._trigger("hijackclick",null,{index:b});return!1})},_slideHide:function(){this.$next.hide();this.$pre.hide()},_slideShow:function(){this.$next.show();this.$pre.show()},_autoPlay:function(){var a=this,b=a.options;clearInterval(this.timer);
this.timer=setInterval(function(){a._goNext()},b.interval)},_goNext:function(){var a=this.currentIndex;++this.currentIndex==this.imgCount&&(this.currentIndex=0);this._display(a)},_goPre:function(){var a=this.currentIndex;0>--this.currentIndex&&(this.currentIndex=this.imgCount-1);this._display(a)},_display:function(a){var b=this.options;this.loadMore||(this.loadMore=!0,c.add(this.$imgs.not(":first")));this.$imglist.eq(a).removeClass(b.selectCls);this.$imglist.eq(this.currentIndex).addClass(b.selectCls);
this._animateShow(a)},_animateShow:function(a){this.$imglist.eq(a).css({opacity:1}).stop().animate({opacity:0},800);this.$imglist.eq(this.currentIndex).css({opacity:0,display:"block"}).stop().animate({opacity:1},800)},destroy:function(){clearInterval(this.timer);$.Widget.prototype.destroy.call(this)}});return d});
__d("common.js.microTemplate",[],function(){function f(d,b){var c=!/\W/.test(d)?e[d]=e[d]||f(document.getElementById(d).innerHTML):new Function("data","var p=[];p.push('"+d.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');return p.join('');");return b?c(b):c}var e={};return f});
__d("widget.toppicture2.toppicture2",["common.js.widget","common.js.lazy"],function(f,e,d,b){b("common.js.widget");var c=b("common.js.lazy");$.widget("hao123.toppicture2",{options:{selectCls:"selected",interval:1E4,lazy:!1},_create:function(){var a=this.element;this.$imgs=$(".js_content li",a);this.$next=$(".js_next",a);this.$pre=$(".js_pre",a)},_init:function(){this.$imgs&&(this._lazyLoad(this.$imgs.find("img")),this.imgCount=this.$imgs.length,this.currentIndex=0,this._bindEvent(),1<this.imgCount&&
this._autoPlay())},_lazyLoad:function(a){this.options.lazy&&(this.lazyKey=c.add(a))},_bindEvent:function(){var a=this;this.$imgs.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)});this.$next.click(function(){a._goNext();a._autoPlay();return!1});this.$pre.click(function(){a._goPre();a._autoPlay();return!1});this.$next.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)});this.$pre.hover(function(){clearTimeout(a.hideTimer);
a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)})},_slideHide:function(){this.$next.hide();this.$pre.hide()},_slideShow:function(){this.$next.show();this.$pre.show()},_autoPlay:function(){var a=this,b=a.options;clearInterval(this.timer);this.timer=setInterval(function(){a._goNext()},b.interval)},_goNext:function(){var a=this.currentIndex;++this.currentIndex==this.imgCount&&(this.currentIndex=0);this._display(a)},_goPre:function(){var a=this.currentIndex;0>--this.currentIndex&&
(this.currentIndex=this.imgCount-1);this._display(a)},_display:function(a){var b=this.options;this.$imgs.eq(a).removeClass(b.selectCls);this.$imgs.eq(this.currentIndex).addClass(b.selectCls);this._animateShow(a)},_animateShow:function(a){this.$imgs.eq(a).css({opacity:1}).stop().animate({opacity:0},800);this.$imgs.eq(this.currentIndex).css({opacity:0,display:"block"}).stop().animate({opacity:1},800)},destroy:function(){this.options.lazy&&c.remove(this.lazyKey);clearInterval(this.timer);$.Widget.prototype.destroy.call(this)}});
return d});
__d("widget.lbssearch.lbssearch",["common.js.jquery","common.js.format","common.js.log"],function(f,e,d,b){var c=b("common.js.jquery"),a=b("common.js.format"),i=b("common.js.log"),l="s&wd=#{word}&c=#{code}";return function(b){function d(b){g.val(a(l,{word:j.val(),code:q.val()}));p.val(b)}var b=c(b),f=c("form",b),e=c(".placeholder",b),j=c(".lbssearch-input",b),p=c(".sdetail",b),h=c(".lbssearch-btn",b),q=c(".code",b),g=c(".s",b);j.focus(function(){e.hide()});j.blur(function(){""!=j.val()?e.hide():e.show()});
j.on("keydown",function(a){13==a.keyCode&&(d("search"),f.submit(),i({type:"bendi"}))});h.click(function(){d("box");f.submit();i({type:"bendi"})})}});window.js_ngnEpxtRLa&&window.js_ngnEpxtRLa(!0);
