__d("common.js.browser",[],function(k,m,j){function a(g){return(g=b.match(RegExp(g+"\\b[ \\/]?([\\w\\.]*)","i")))?g.slice(1):["",""]}var d=window,k=document,b=navigator.userAgent.toLowerCase(),c=j=m=null,f=function(){var g=-1<b.indexOf("360chrome")?!0:!1,f;try{d.external&&d.external.twGetRunPath&&(f=d.external.twGetRunPath)&&-1<f.indexOf("360se")&&(g=!0)}catch(c){g=!1}return g}(),l=-1<b.indexOf("bidubrowser")?!0:!1,h=-1<b.indexOf("biduplayer")?!0:!1,n=-1<b.indexOf("\u7231\u5e06")?!0:!1,i;a:{try{if(/(\d+\.\d)/.test(d.external.max_version)){i=
parseFloat(RegExp.$1);break a}}catch(e){}i=void 0}var g=a("(msie|safari|firefox|chrome|opera)"),o=a("(maxthon|360se|360chrome|theworld|se|theworld|greenbrowser|qqbrowser|lbbrowser|bidubrowser)"),r=a("(windows nt|macintosh|solaris|linux)"),q=a("(webkit|gecko|like gecko)");"msie"===g[0]?f?o=["360se",""]:i?o=["maxthon",i]:","==o&&(o=a("(tencenttraveler)")):"safari"===g[0]&&(g[1]=a("version")+"."+g[1]);(m="chrome"==g[0]&&g[1])&&"track"in document.createElement("track")&&"scoped"in document.createElement("style")&&
("v8Locale"in window?j=!0:c=!0);return j={cookieEnabled:navigator.cookieEnabled,isStrict:"CSS1Compat"==k.compatMode,isShell:!!o[0],shell:o,kernel:q,platform:r,types:g,chrome:m,firefox:"firefox"==g[0]&&g[1],ie:"msie"==g[0]&&g[1],opera:"opera"==g[0]&&g[1],safari:"safari"==g[0]&&g[1],maxthon:"maxthon"==o[0]&&o[1],isTT:"tencenttraveler"==o[0]&&o[1],is360:f,is360Chrome:j,is360se:c,isBaidu:l,isHao123:function(){return!(!window.external||!window.external.GetHao123Version)},isIpad:function(){return-1<b.indexOf("ipad")||
-1<b.indexOf("iphone")},noDl:l||n||h,canvasSupport:!!document.createElement("canvas").getContext}});
__d("widget.popup.mask",["common.js.browser"],function(k,m,j,a){function d(){var c=f.body;return Math.max(f.documentElement.scrollHeight,c.scrollHeight,("BackCompat"==f.compatMode?c:f.documentElement).clientHeight)+"px"}var b=a("common.js.browser"),c=null,f=k.document;return j={show:function(){c||(c=f.createElement("div"),c.className="popup-mask",f.body.appendChild(c));6==b.ie&&(c.style.height=d());c.style.display=""},hide:function(){c&&(c.style.display="none")},refresh:function(){c&&(c.style.height=
d())},remove:function(){c&&(c.parentNode.removeChild(c),c=null)}}});
__d("common.js.refer",["common.js.config","common.js.browser"],function(k,m,j,a){function d(f){try{return h||(h=document.createElement("div"),h.style.display="none",h.style.behavior="url(#default#homePage)",document.body.appendChild(h)),h.isHomePage(f)}catch(c){return!1}}function b(){var a;if(!l)if(f.ie){a=c.get("whitelist");for(var b in a)if(d(a[b].url))return l="iechannelhome";a:{var h,g;b=["http://",""];h=["www.6164.com","3w.hao123.com","ww.hao123.com","hao123.com"];g=",/,/?from=hao123,/?f=hao123,/?f=g,/?f=sidebar1,/index.html".split(",");
a=[];for(var o=0;o<g.length;o++)for(var j=0;j<h.length;j++)for(var k=0;k<b.length;k++)a.push(b[k]+h[j]+g[o]);a.unshift(document.URL);b=-1;for(h=a.length;++b<h;)if(g=a[b],d(g)){a=!0;break a}a=!1}l=a?"iestandardhome":"ienothome"}else l="organic";return l}var c=a("common.js.config"),f=a("common.js.browser"),l=!1,h=!1;return j={isHomePage:d,isIEStandardHome:function(){return"iestandardhome"==b()},isIENotHome:function(){return"ienothome"==b()},isIEChannelHome:function(){return"iechannelhome"==b()},isOrganic:function(){return"organic"==
b()},refresh:function(){l=!1},isTN:function(){return window.location.search.match(/[?&](src|tn)=.+/)?!0:!1}}});
__d("common.js.homeLog",["common.js.log","common.js.config","common.js.refer","common.js.browser"],function(k,m,j,a){var d=a("common.js.log"),k=a("common.js.config"),b=a("common.js.refer"),m=a("common.js.browser"),a=window.location.search.match(/[?&](tn|src)=([^&<>'"]+)/)?1:0,m=m.ie?1:0;k.get("pageId");var c={pageId:k.get("pageId"),ie:m,tn:a,type:"ubclick"};return function(a){for(var l in c)c.hasOwnProperty(l)&&!(l in a)&&(a[l]=c[l]);a.ho=b.isIENotHome()?0:1;"set"in a&&(a.set=Number(a.set),a.set=
a.position+""+a.set,delete a.position);d(a)}});
__d("widget.popup.base",["widget.popup.mask","common.js.browser","common.js.pageEvents","common.js.widget"],function(k,m,j,a){function d(a){var a=a||l.getViewport(),b=a.width,d=(a.height-this.height)/2;6==f.ie&&(c.refresh(),d+=a.scrollTop);this.element&&this.element.css({left:(b-this.width)/2,top:d})}function b(){}var c=a("widget.popup.mask"),f=a("common.js.browser"),l=a("common.js.pageEvents");a("common.js.widget");b.prototype=new $.Widget;b.prototype=$.extend(b.prototype,{_baseCreate:function(){this.element.addClass(this.options.className);
this._appendToBody=!1},_baseShow:function(a){this._appendToBody||(this.element.appendTo("body"),this._appendToBody=!0);0<arguments.length&&"function"==typeof a?a(this.element):this.element.show();this.height=this.element.height();this.width=this.element.width();this.options.isModel&&c.show();l.on("viewport.deferchange",d,this);d.call(this)},_baseHide:function(a,b){this.options.isModel&&(b||c.hide());0<arguments.length&&"function"==typeof a?a(this.element):this.element.hide()},remove:function(a){this.options.isModel&&
c.remove();0<arguments.length&&"function"==typeof a?a(this.element):this.element.remove()}});return b});
__d("widget.popup.sethome",["widget.popup.base","common.js.log"],function(k,m,j,a){var k=a("widget.popup.base"),d=a("common.js.log");$.widget("hao123.sethome",k,{options:{className:"popup-sethome",isModel:!0},_create:function(){this._baseCreate();var a=this.element,c=this;$(".js_close",a).click(function(){c._baseHide();return!1});$(".js_ok",a).click(function(){c._baseHide()}).text(c.options.okText)},show:function(){this._baseShow();d({type:"sethomeshow"})}});return j});
__d("widget.popup.getTpl",["common.js.format"],function(k,m,j,a){var d=a("common.js.format"),b={head:'<div class="popup-head"><a class="js_close" href="javascript:void(0);"></a><span class="js_title"></span></div>',login:'<div class="login_left"><div id="login_holder"><div id="login_holder_1"></div></div></div><div class="login_right"><p class="reg_text">\u8fd8\u6ca1\u6709\u767e\u5ea6\u5e10\u53f7\uff1f</p><p class="reg_link"><a href="https://passport.baidu.com/v2/?reg&amp;tpl=hao123&amp;regType=1&amp;u=http%3A%2F%2F'+
window.location.host+'%2F" target="_blank" id="reg_btn"></a></p><p class="other_title">\u4f7f\u7528\u5408\u4f5c\u7f51\u7ad9\u5e10\u53f7\u767b\u5f55</p><ul class="other_list"><li><a class="other_icon other_icon_qq" href="http://passport.baidu.com/phoenix/account/startlogin?tpl=hao123&u=http%3A%2F%2Fwww.hao123.com%2F&act=implicit&type=15&xd=http%3a%2f%2fwww.hao123.com%2fcloudjump.htm%23display%3dpopup">QQ\u5e10\u53f7\u767b\u5f55</a></li><li><a class="other_icon other_icon_sina" href="http://passport.baidu.com/phoenix/account/startlogin?tpl=hao123&u=http%3A%2F%2Fwww.hao123.com%2F&act=implicit&type=2&xd=http%3a%2f%2fwww.hao123.com%2fcloudjump.htm%23display%3dpopup">\u65b0\u6d6a\u5fae\u535a\u5e10\u53f7\u767b\u5f55</a></li><li><a class="other_icon other_icon_renren" href="http://passport.baidu.com/phoenix/account/startlogin?tpl=hao123&u=http%3A%2F%2Fwww.hao123.com%2F&act=implicit&type=1&xd=http%3a%2f%2fwww.hao123.com%2fcloudjump.htm%23display%3dpopup">\u4eba\u4eba\u5e10\u53f7\u767b\u5f55</a></li></ul></div>',
confirm:"<div class='popup-body'><i></i><div><strong class='js_text'></strong> <p><button class='button js_ok'  ></button><button class='button js_cancel' >\u53d6\u6d88</button></p></div></div>",alert:"<div class='popup-alert-w'><p class='popup-alert-text js_text'></p><p class='popup-alert-control'><button class='button js_ok'>\u786e\u5b9a</button></p></div>",
upload:'<div class="popup-upload-w g_clr"><div class="g-ib popup-upload-ct"><p class="popup-upload-select"><button class="popup-upload-btns"></button><span class="btnselect js_select"></span><span class="tip js_text"></span></p><div class="popup-upload-desk js_cutter"></div><div class="popup-upload-state" style="display:none;"><span class="state-txt js_stattxt"></span></div><p class="popup-upload-caijian"><button class="popup-upload-btncj js_ok"></button></p></div></div>',sethomeNotie:"<div class='popup-sethome' monkey=sethomeNotie'><p class='popup-sethome-title-notie'></p><p class='popup-sethome-text' style='color:#F46417'>\u60a8\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u4e00\u952e\u8bbe\u4e3a\u4e3b\u9875<br/>\u5efa\u8bae\u624b\u52a8\u8bbe\u7f6e\uff0c\u4e00\u822c\u60c5\u51b5\u5728\uff1a<br/>\u201c\u5de5\u5177-\u9009\u9879-\u4e3b\u9875\u201d \u6216 \u201c\u8bbe\u7f6e-\u4e3b\u9875\u201d\u91cc<br/>\u3000\u52a8\u624b\u8bd5\u8bd5\uff01</p><a class='popup-sethome-close js_close' href='###'></a></div>",
tpl:"<div class='popup'>#{head}#{content}</div>"};return function(a){return"sethome"==a||"sethomeNotie"==a?b[a]:d(b.tpl,{head:b.head,content:b[a]})}});
__d("common.js.home","widget.popup.mask,common.js.browser,widget.popup.getTpl,common.js.refer,common.js.format,common.js.homeLog,widget.popup.sethome".split(","),function(k,m,j,a){var d=a("widget.popup.mask"),b=a("common.js.browser"),c=a("widget.popup.getTpl"),f=a("common.js.refer"),l=a("common.js.format"),h=a("common.js.homeLog"),n=null,i=null;a("widget.popup.sethome");var e={_element:null,show:function(){this._element||(this._element=document.createElement("div"),this._element.className="sethomehint");
var a,c;a=document.documentElement.clientHeight;c=document.documentElement.clientWidth;this._element.style.top=parseInt(a/2)-80+document.documentElement.scrollTop+"px";this._element.style.left=parseInt(c/2)-480+"px";1E3<c&&6<b.ie&&document.body.appendChild(this._element)},hide:function(){this._element.parentNode.removeChild(this._element)}};return j={set:function(a,b,l){h({link:l});if("length"in a){if(0>=a.length)return!1;a=a[0]}var i;try{d.show(),e.show(),a.style.behavior="url(#default#homepage)",
a.setHomePage(b),d.hide(),e.hide(),i=a.isHomePage(b)}catch(j){i=!1}h({set:i,position:l});f.refresh();f.isIENotHome()&&(n||(n=$(c("sethome")).sethome()),n.sethome("show"));return!0},setNotie:function(a){i||(i=$(l(c("sethomeNotie"),a)).sethome());i.sethome("show")},is:function(a){try{return homePageDom||(homePageDom=document.createElement("div"),homePageDom.style.display="none",homePageDom.style.behavior="url(#default#homePage)",document.body.appendChild(homePageDom)),homePageDom.isHomePage(a)}catch(c){}}}});
__d("widget.baiduIcon.baiduIcon",["common.js.widget","common.js.browser","common.js.log"],function(k,m,j,a){a("common.js.widget");var d=a("common.js.browser"),b=a("common.js.log");$.widget("hao123.baiduIcon",{_create:function(){if(d.isBaidu){d=window.location.search.match(/[?&]browser=([^&<>'"]+)/);var a=this;d&&"baidu"==d[1]&&$(function(){var f=a.element;$(".hao123-header-right",f).css({position:"absolute",right:100});$(f).before(" <a id='baidubrowser' href='bdbrowser://tabpage/#source=hao123' target='_self' style='position:absolute; z-index:999;left:50%;margin-left:412px;top:6px;width:58px; font-size:12px;background:url(http://s0.hao123img.com/res/img/baidulink.png) no-repeat; padding-left:20px;line-height:18px'>\u6700\u5e38\u8bbf\u95ee</a>");
$("#baidubrowser").click(function(){b({level:1,page:window.pageId,type:"baidubrowser"})})})}}});return j});
__d("widget.hao123Startup.hao123Startup",["common.js.widget"],function(k,m,j,a){a("common.js.widget");$.widget("hao123.hao123Startup",{_create:function(){if(!(0>window.location.search.indexOf("browser=startup"))){var a=$('<div class="hao123startup-welcome"></div>').appendTo(this.element),b=$('<div class="hao123startup-hint"></div>');$("body div:first").before(b);window.setTimeout(function(){a.animate({height:0},1E3,function(){})},3E3);window.setTimeout(function(){b.fadeOut()},33E3)}}});return j});
__d("widget.ad2012.ad2012",["common.js.widget"],function(k,m,j,a){a("common.js.widget");$.widget("hao123.ad2012",{_create:function(){function a(){e-=n;-e>l*i&&(e=-l*i,i++,window.clearInterval(g),g=null,i>c&&(i=1,e=0));f.element.css({top:e})}function b(){null===g&&(g=window.setInterval(a,h))}var c=this.element.children().length-1,f=this;if(!(2>c)){var l=30,h=16,n=1,i=1,e=0,g=null,o=null;f.element.append($("<div></div>").append(f.element.get(0).children[0].innerHTML));o=window.setInterval(b,5E3);f.element.find("a").hover(function(){window.clearInterval(o);
o=null},function(){null===o&&(o=window.setInterval(b,5E3))})}}});return j});
__d("site.searchLog",["common.js.log","common.js.config"],function(k,m,j,a){var d=a("common.js.log"),b=a("common.js.config");return function(a){a.on("searchfloatsubmit",function(){d({type:"floatsubmit"})});a.on("searchspecialshow",function(){d({type:"suggestspecialshow"})});a.on("searchsecialsubmit",function(a,b){d({type:"special",hit:b.hit,from:b.from,toerji:b.toerji,index:b.index})});a.on("searchsubmit",function(a,c){var h={type:"submit",position:c.tab,title:c.query,pageId:b.get("pageId")};switch(c.action){case "button":h.btnclick=
1;break;case "select":h.sug=1}d(h)}).on("searchsubmit",function(a,c){var h={type:"clicksug",flag:1,pageId:b.get("pageId")};h.src={input:2,suggest:2,hotword:{web:1,image:3}}[c.from][c.tab]||2;h.sugposition=c.suggestIndex;h.title=c.query;d(h)}).on("searchhotwordshow",function(){d({sugposition:1,pageId:b.get("pageId")})})}});
__d("widget.credit.credit",["common.js.widget","common.js.log","common.js.events","common.js.refer"],function(k,m,j,a){a("common.js.widget");var d=a("common.js.log"),b=a("common.js.events"),c=a("common.js.refer");$.widget("hao123.credit",{options:{tipmsg:"",creditUrl:"http://zhuanla.hao123.com/jifen.html",homeUrl:"http://www.6164.com/?src=jifen",tipCls:"tipicon",delay:1E4},_create:function(){var a=this.element;this.$tipicon=$("i",a);this.$tipmsg=$(".js_tipmsg",a);this.$tipclose=$(".js_tipclose",
a);this.$sethome=$("#sethome");this.$sethomeText=$("#sethome .js_text");this.hover=!1;this._bindEvent()},_init:function(){var a=this,d=a.options;d.tipmsg=c.isIEChannelHome()?"\u4fdd\u6301hao123\u4e3a\u4e3b\u9875\uff0c\u5929\u5929\u90fd\u80fd\u9886\u53d6\u79ef\u5206\uff0c\u6362\u597d\u793c >>":"\u8bbehao123\u4e3a\u4e3b\u9875\uff0c\u5373\u53ef\u62bd\u5956 >>";b.on("setHome.before",function(){return!1});this.$tipmsg.text(d.tipmsg);this.$tipicon.addClass(d.tipCls);this.$sethomeText.text("\u8bbe\u9996\u6709\u793c");
this.element.fadeIn();this.timer=setTimeout(function(){a.element.fadeOut()},a.options.delay)},_bindEvent:function(){var a=this;a.$sethome.mouseover(function(){a.hover||(a.hover=!0,a.element.fadeIn(),clearTimeout(a.timer))});a.$sethome.click(function(){a._processAction();return!1});a.$tipmsg.click(function(){a._processAction();return!1});a.$tipclose.click(function(){a.element.fadeOut();a.hover=!1})},_processAction:function(){var a=this,b=a.options,h=a.element.get(0);c.isIEChannelHome()?(window.open(b.creditUrl),
a.element.fadeOut(),a.hover=!1):(h.style.behavior="url(#default#homepage)",h.setHomePage(b.homeUrl),c.isHomePage(b.homeUrl)?(b.tipmsg="\u606d\u559c\u60a8\u6210\u529f\u8bbe\u7f6ehao123\u4e3a\u4e3b\u9875\uff0c\u83b7\u5f97\u62bd\u5956\u673a\u4f1a >>",a.$tipmsg.text(b.tipmsg),d({type:"tempstatistics",pageId:"iehome"})):(a.element.fadeOut(),setTimeout(function(){a.hover=!1},1E3)))}});return j});
__d("site.swayLogo",["common.js.home","common.js.cookie","common.js.refer"],function(k,m,j,a){var d=a("common.js.home"),b=a("common.js.cookie"),c=a("common.js.refer"),f=null;return j={init:function(a,c){f=a;var d=c.height()-12,i=$('<span  style="background:url(http://s0.hao123img.com/res/images/swayLogo.gif);position:absolute;cursor:pointer; width:169px; height:90px; top:'+d+'px; left:-20px;"></span>');f.append(i);var e=$('<span style="background:url(http://s0.hao123img.com/res/images/swaylogo-close.png?r=1) no-repeat;cursor:pointer; width:16px; height:16px; position:absolute; top:'+
(d+19)+'px; right:30px;"></span>');f.append(e);e.click(function(){i.hide();e.hide();b.set("swaylogo",1);return!1});e.mousedown(function(){return!1})},onClick:function(){d.set(f,"http://www.6164.com/?f=amusing",4);return!1},check:function(){return b.has("swaylogo")||!c.isIENotHome()?!1:!0}}});
__d("common.js.dns",["common.js.log","common.js.jquery","common.js.cookie"],function(k,m,j,a){var d,b;function c(){var a="";1>=Math.ceil(100*Math.random())&&(a=i("html").html()||"",setTimeout(function(){i.ajax({url:"/api/postcontent",type:"POST",data:{c:e,content:a||""}})},1E4))}function f(){i.ajax({url:d,type:"GET",headers:{KTN:"ck"},success:function(a,b,c){a=c.getResponseHeader("KTN");c=b="";a?("string"==typeof a&&(b=a.match(/[?&]tn=([^&<>'"]+)/),c=a.match(/[?&]src=([^&<>'"]+)/),b=b&&b[1],c=c&&
c[1],b||(b=""),c||(c="")),a==d?n({type:"KTN",code:"0",tn:b,src:c}):n({type:"KTN",code:"1",b2:a,tn:b,src:c})):n({type:"KTN",code:"2"})},error:function(){n({type:"KTN",code:"2"})}})}function l(a){var c=a||document,a=c.getElementsByTagName("iframe"),c=c.getElementsByTagName("script"),d=[],e=[],f={type:"KFC"};i(a).each(function(){var a=i(this).attr("src")||"";if(a){var c;c=h(a);for(var g=b.iframes,e=g.length,f=!1,n=0;n<e;n++)if(-1<c.indexOf(g[n])){f=!0;break}f||(-1<a.indexOf("://")||-1<a.indexOf("htpp")||
-1<a.indexOf("htpps"))&&d.push(a)}});i(c).each(function(){var a=i(this).attr("src")||"";if(a){var c;c=h(a);for(var d=b.scripts,g=d.length,f=!1,n=0;n<g;n++)if(-1<c.indexOf(d[n])){f=!0;break}f||(-1<a.indexOf("://")||-1<a.indexOf("htpp")||-1<a.indexOf("htpps"))&&e.push(a)}});0>=d.length&&0>=e.length?f.code=0:(f.code=1,0<d.length&&(f.f=d.join("|")),0<e.length&&(f.s=e.join("|")));return f}function h(a){-1<a.indexOf("#")&&(a=a.substr(0,a.indexOf("#")));-1<a.indexOf("?")&&(a=a.substr(0,a.indexOf("?")));
return a}var n=a("common.js.log"),i=a("common.js.jquery"),k=a("common.js.cookie"),e=k.getFlashId()||k.getBaiduId();window.location.search.match(/[?&]tn=([^&<>'"]+)/);d="/";b={scripts:["hao123.com","hao123img.com","baidu.com"],iframes:"120.209.128.29,baidu.com,hao123.com,anjuke.com,58.com,daohang.114so.cn".split(",")};return function(){f();var a={},b={},a=l();top!=window&&(parent.document?(a.p_t=0,b=l(parent.document),a.p_code=b.code,b&&b.s&&(a.p_s=b.s),b&&b.f&&(a.p_f=b.f)):a.p_t=1);n(a);(1==a.code||
1==a.p_code)&&c()}});__d("widget.popup.sethomeNotie",["widget.popup.base","common.js.log"],function(k,m,j,a){var k=a("widget.popup.base"),d=a("common.js.log");$.widget("hao123.sethomeNotie",k,{options:{},_create:function(){this._baseCreate();var a=this.element,c=this;$(".js_close",a).click(function(){c._baseHide();return!1});$(".js_ok",a).click(function(){c._baseHide()})},show:function(){this._baseShow();d({type:"sethomeshowNotie"})}});return j});
__d("common.js.count","common.js.config,common.js.refer,common.js.browser,common.js.load,common.js.localcookie,common.js.log,common.js.format".split(","),function(k,m,j,a){function d(){var a=c.get("userinfo"),b="",b=a.iscuser?b+"1":b+"0",b=a.recommendData?b+"1":b+"0";return b=a.isauser?b+"1":b+"0"}function b(){var a={urls:1,skin:1,fms:1,navigate:1,moviealbum:1,tvalbum:1,uir:1,ua:1,ns:1,tf:1,mf:1,sitead:1,myremind:1},b=c.get("currentProfile"),d="",e;for(e in b)a&&!a[e]&&b[e]&&"string"==typeof b[e]&&
(d+=";gx_"+e+":"+(20>b[e].length?b[e]:""));return d}var c=a("common.js.config"),f=a("common.js.refer"),l=a("common.js.browser");return function(){var h=a("common.js.load"),j=a("common.js.localcookie"),i=a("common.js.log"),e=c.__config__,g=a("common.js.format"),k=d(),m="http://s0.hao123img.com/res/js/track.js?"+(+new Date/36E5|0),q=window.location.search.match(/[?&]tn=([^&<>'"]+)/)?1:0,p={pageId:e.pageId,pf_fms:e.currentProfile.fms,pf_nav:e.currentProfile.navigate,pf_bd:""+e.currentProfile.t0+e.currentProfile.t1+
e.currentProfile.t2+e.currentProfile.t3,pf_gw:""+e.currentProfile.t4,pf_mf:e.currentProfile.mf&&e.currentProfile.mf.substr(0,1),pf_tf:e.currentProfile.tf&&e.currentProfile.tf.substr(0,1),pf_relax:e.currentProfile.relax||0,menu:e.currentProfile.menu||"index",navmore:c.get("currentProfile").navmore,skin:e.currentProfile.skin,isSiteUser:k,ostype:e.userinfo.ostype,ie:0<l.ie?1:0,home:l.ie&&!f.isIENotHome()?1:0,rp:q,mw:e.staticuser,gxzq:e.currentProfile.uir};h.loadScript(m,function(){},{"data-log-config":g("level:1;page:index;pageId:#{pageId};pf_fms:#{pf_fms};pf_bd:#{pf_bd};pf_gw:#{pf_gw};pf_mf:#{pf_mf};pf_tf:#{pf_tf};pf_nav:#{pf_nav};rp:#{rp};navmore:#{navmore};skin:#{skin};isSiteUser:#{isSiteUser};ostype:#{ostype};menu:#{menu};mw:#{mw};gxzq:#{gxzq}",
p)+b()});j.wait(function(){p.type="flash";i(p)})}});
__d("widget.append.append",["common.js.format","common.js.profile"],function(k,m,j,a,d,b){a("common.js.format");a("common.js.profile");return function(){b(["common.js.jquery","common.js.adjust","common.js.lazy"],function(a,b,d){var h=a("#append");h.hide();b.adjustQuick();d.add(a("#append-location"),function(){h.hide();var d=a("#layout-side"),i=a("#layout-content"),e=a("#box-navigate"),g=a("#js_nlb");e.css({height:"auto"});g.css({height:"auto"});d=d.height()-i.height();if(!(50>d)){a("#append-links");
i=0;h.removeClass("append-simple");76>d?(h.addClass("append-simple"),i=3):102>d?(h.addClass("append-simple"),i=6):(i=Math.floor((d-14-12-12-12)/26),i*=3);d=i;i=$("#append-links");e=null;$("li",i).addClass("item");for(g=0;g<d;g++)e=$(".item"+g,i),e.removeClass("item");h.show()}b.adjust()})})}});
__d("widget.joke.joke",["common.js.widget"],function(k,m,j,a){a("common.js.widget");$.widget("hao123.joke",{options:{jokes:null,current:0},_create:function(){var a=this.element;this.$jokeChange=$(".joke-change",a);this.$joke=$(".joke-text",a);this._bindEvent()},_init:function(){this.current=this.options.current},_bindEvent:function(){var a=this;this.$jokeChange.click(function(){a._ranJoke();return!1});this.$joke.click(function(){setTimeout(function(){a._ranJoke()},0)})},_ranJoke:function(){var a=
this.options.jokes,b=this.current+1,c;b>=a.length&&(b=0);c=a[b];this.$joke.addClass(a[0].style);this.$joke.attr("href",c.url);this.$joke.text(c.title);this.current=b},destroy:function(){$.Widget.prototype.destroy.call(this)}});return j});window.js_OMHsjRnToD&&window.js_OMHsjRnToD(!0);
