__d("widget.newindex_movie.newindex_video_adjust",[],function(q,w,r){return r={adjust:function(){var a=$("#hao123-bodyct .js-adjust-l:eq(0)"),d=$("#hao123-bodyct .r-widget:eq(0)"),e=$("#video_ranking_list",d);a.css("height","auto");e.css("height","auto");setTimeout(function(){var f=a[0].offsetHeight-d[0].offsetHeight;0<f?e.css("height",e.height()+f+"px"):a.css("height",a.height()-f+"px")},0)}}});
__d("common.js.adjust",[],function(q,w,r,a,d,e){function f(){var a,d,c,k;e(["common.js.jquery","common.js.pageEvents"],function(f,j){var u,g,s,m;a=a||f("#box-navigate");c=c||f("#layout-side");k=k||f(".js_nlb");d=d||f("#layout-content");a.css("height","auto");k.css("height","auto");u=a.height();m=k.height();g=d.height();s=c.height();g<=s?a.height(s-g+u):k.height(g-s+m);j.emitPageChange()})}var h=0;return r={adjust:function(){clearTimeout(h);h=setTimeout(function(){f()},200)},adjustQuick:function(){f()}}});
__d("widget.site.config",[],function(q,w,r){return r={css:{siteNormal:"site-normal",siteEdit:"site-edit",hdNormal:"site-hd-normal",hdEdit:"site-hd-edit",itemNormal:"site-item-normal",itemMove:"site-item-move",itemEdit:"site-item-edit",itemCurrent:"site-item-current",itemDashed:"site-item-dashed",itemAdd:"site-item-add",itemAddUp:"site-item-add-up",itemAddDown:"site-item-add-down",item:"site-item",js_item:"js_site-item",bdNormal:"site-bd-normal",itemText:"site-text",itemTpl:"site-tpl",sugError:"error"},
sug:{requestQuery:"wd",url:"http://nssug.baidu.com/su",callbackFn:"baidu.sug",callbackDataKey:"s",requestParas:{prod:"superpage"},n:5,noSubmit:!0},error:{500:'\u51fa\u73b0\u9519\u8bef\uff0c\u8bf7\u70b9 <a href="http://www.hao123.com" target="_self">\u8fd9\u91cc</a> \u5237\u65b0\u9875\u9762',501:"\u8be5\u7f51\u5740\u5df2\u5b58\u5728",510:'\u51fa\u73b0\u9519\u8bef\uff0c\u8bf7\u70b9 <a href="http://www.hao123.com"  target="_self">\u8fd9\u91cc</a> \u5237\u65b0\u9875\u9762',503:'\u51fa\u73b0\u9519\u8bef\uff0c\u8bf7\u70b9 <a href="http://www.hao123.com"  target="_self">\u8fd9\u91cc</a> \u5237\u65b0\u9875\u9762',
511:"\u8bf7\u8f93\u5165\u6b63\u786e\u683c\u5f0f\uff0c\u5982http://www.abc.com",512:"\u7f51\u7ad9\u540d\u79f0\u8fc7\u957f",513:"\u7f51\u5740\u8fc7\u957f",515:"\u8bf7\u8f93\u5165\u7f51\u7ad9\u540d\u79f0",516:"\u8bf7\u8f93\u5165\u7f51\u5740",507:"\u8bf7\u60a8\u5148\u767b\u5f55",514:"\u7f51\u5740\u5df2\u6ee1\uff0c\u8bf7\u5220\u9664\u4e0d\u5e38\u7528\u7684\u7f51\u5740"},info:{loading:"\u6b63\u5728\u8bf7\u6c42\uff0c\u8bf7\u7a0d\u5019",ok:"\u64cd\u4f5c\u6210\u529f\uff01",refresh:"\u6b63\u5728\u5237\u65b0\uff0c\u8bf7\u7a0d\u5019"},
url:{init:"/url/init",add:"/url/add",modify:"/url/modify",doDelete:"/url/delete",recover:"/url/reset",needImport:"/url/isneedimport",doImport:"/url/import",sort:"/url/sort",cr:"/api/paneldata",delRecommend:"/api/delrecom",delRecombyid:"/api/delrecombyid",user:"/api/username",adds:"/url/recomadds"},retry:2,recommendN:3,recommendMaxWord:5,showSaveMax:5,nameMaxLength:40,urlMaxLength:200,siteMaxlength:48,guestMaxLength:10,guestStatus:2,dragHint:"\u62d6\u52a8\u6392\u5e8f",confirmTitle:"\u63d0\u793a",confirmText:"\u767b\u5f55\u540e\u53ef\u7f16\u8f91\u66f4\u591a\u7f51\u5740\uff0c\u968f\u65f6\u968f\u5730\u6536\u85cf\uff0c\u4e0d\u518d\u62c5\u5fc3\u7f51\u5740\u4e22\u5931\uff01",
alertTitle:"\u63d0\u793a",recoverTitle:"\u6062\u590d\u9ed8\u8ba4",recoverText:"\u662f\u5426\u8981\u6062\u590d\u4e3a\u9ed8\u8ba4\u7f51\u5740\uff1f",adddedText:"\u5df2\u6dfb\u52a0\uff0c\u70b9\u51fb\u53d6\u6d88",emptyText:"\u6e05\u7a7a\u5386\u53f2\u8bb0\u5f55\uff01",guestHint:"\u7f51\u5740\u8fc7\u591a\uff0c\u5efa\u8bae\u767b\u5f55\u540e\u6c38\u4e45\u4fdd\u5b58",baiduCookie:"BAIDUID",flashCookie:"FLASHID",dataIdAttr:"data-id",iconBaseUrl:"hao123.com/urlicon/",defaultIconUrl:"http://img1.hao123.com/urlicon/6000.png",
jsItem:".js_site-item",tpl:{sugMain:'<ol class="site-sugwrap">#{content}<ol>',sugItem:'<li site="#{site}" q="#{q}"><span class="name">#{title}</span><span class="url">#{text}</span></li>',sugSplitChar:"0{#S+_}",recommend:"<li><a class='item item-add js_recommend' data-id='#{id}' hidefocus='true'  data-type='recommend' href='#{url}'>#{name}</a></li>",cms:"<dl class='g_clr'><dt><span class='popup-site-cms-title'>#{name}</span></dt>#{content}</dl>",cmsContent:"<dd #{itemStyle}><a href='#{url}' data-id='#{id}' hidefocus='true' data-type='cms' class='#{className}'>#{name}</a></dd>",
itemTag:"<ul>",editItem:"<li title='\u62d6\u52a8\u6392\u5e8f' class='js_site-item' data-id='#{id}' data-name='#{rawName}'  data-url='#{url}'><span class='js_text text' >#{name}</span><a  class='js_modify modify'  href='#' title='\u4fee\u6539' hidefocus='true'></a><a class='js_delete delete'  href='#'  title='\u5220\u9664' hidefocus='true'></a></li>",item:'<li class="js_site-item g-ib site-item site-item-normal #{style}" data-status="#{status}" title="#{title}" data-id="#{id}"><a class="js_text" href="#{url}" style="background-image:url(#{icon})" hidefocus="true">#{name}</a></li>',
recommendNone:'<div class="popup-site-recommend-sidenone"><h5>\u60a8\u5e38\u70b9\u7684\uff1a</h5><span>\u8fd8\u6ca1\u6709\u53d1\u73b0\u60a8\u5e38\u70b9\u7684\u7f51\u5740\uff0c\u5efa\u8bae\u60a8\u591a\u4f7f\u7528hao123</span></div>',noData:'<li class="js_no-data nodata">\u6ca1\u6709\u5e38\u7528\u7f51\u5740\uff0c\u8bf7\u60a8<a href="javascript:void(0)">\u6dfb\u52a0</a></li>',addNormalBtn:'<li class="js_item-add g-ib site-item site-item-add site-item-add-normal"><i></i><span class="site-item-add-text">\u6dfb\u52a0\u7f51\u5740</span>#{recommend}</li>',
addShortBtn:'<li title="\u6dfb\u52a0\u7f51\u5740" class="js_item-add g-ib site-item site-item-add site-item-add-short"><i></i>#{recommend}</li>',addRecommend:"",tipTpl:'<div class="popup-site-tip-add"><i class="popup-site-tip-close js_add-tip-close">\u5173\u95ed</i></div>'}}});
__d("widget.site.drag",["widget.site.config","common.js.jquery","common.js.browser","common.js.format","common.js.events"],function(q,w,r,a){function d(c,a){this.container=c;this.placeHolder=a;this._events={sorted:[]};this.activeIndex=-1}function e(c){if(c.pageX||c.pageY)return{x:c.pageX,y:c.pageY};if(document.documentElement&&document.documentElement.scrollTop)return{x:c.clientX+document.documentElement.scrollLeft-document.documentElement.clientLeft,y:c.clientY+document.documentElement.scrollTop-
document.documentElement.clientTop};if(document.body)return{x:c.clientX+document.body.scrollLeft-document.body.clientLeft,y:c.clientY+document.body.scrollTop-document.body.clientTop}}var f=a("widget.site.config"),h=a("common.js.jquery"),n=a("common.js.browser");a("common.js.format");var l=a("common.js.events"),c=null,k=f.jsItem;k.substring(1);var v="item-move";d.prototype={setIsCanDrag:function(c){this._isCanDrag=c},dragable:function(){var c=this;this.container.delegate(f.jsItem,"mousedown",function(a){function g(a){var m=
e(a),a=m.x,m=m.y,o=a-y+f,A=m-b+x;0<o&&o+p.offsetWidth<c.container.width()+10&&(f=o);0<A&&A<c.container.height()&&(x=A);p.style.left=f+"px";p.style.top=x+"px";y=a;b=m;c._dealMeet(p);return!1}function d(){h(document).off("mousemove",g);h(document).off("mouseup",d);n.ie?p.releaseCapture():p.style.opacity="";c._moveTo(p,function(){h(p).insertBefore(c.placeHolder).removeClass(v);c.placeHolder.hide();var b=h(k).index(p);c.activeIndex!=b&&(c.activeIndex=b,l.emit("sorted"))});return!1}function m(){return c._isCanDrag?
!1:!0}c.container.on("click",m);if(!(0<=a.target.className.indexOf("js_modify")||0<=a.target.className.indexOf("js_delete"))){c.activeIndex=h(k).index(this);n.ie?this.setCapture():this.style.opacity=0.8;this.style.left=this.offsetLeft+"px";this.style.top=this.offsetTop+"px";this.className=this.className+" "+v;c.placeHolder.insertBefore(this);c.placeHolder.show();var f=parseInt(this.style.left),x=parseInt(this.style.top),a=e(a),y=a.x,b=a.y;c._registePosition();var p=this;h(document).on("mousemove",
g);h(document).on("mouseup",d);h(document).off("mouseup",m);return!1}})},_registePosition:function(){c=[];h(k,this.container).each(function(a){c.push({left:this.offsetLeft,top:this.offsetTop,index:a,thisObj:this})});this.placeHolder.index=h("li,",this.container).index(this.placeHolder)},_dealMeet:function(a){for(var k=a.offsetLeft,g=a.offsetTop,d=0;d<c.length;d++)if(c[d].thisObj!==a&&Math.abs(c[d].left-k)<0.5*a.offsetWidth&&Math.abs(c[d].top-g)<0.3*a.offsetHeight){this.placeHolder.index>c[d].index?
this.placeHolder.insertBefore(c[d].thisObj):this.placeHolder.insertAfter(c[d].thisObj);this._registePosition();break}},_moveTo:function(c,a){function d(){y+=(n-k)/f;b+=(x-m)/f;c.style.left=y+"px";c.style.top=b+"px";l++<f?window.setTimeout(d,i):a()}var k=c.offsetLeft,m=c.offsetTop,n=this.placeHolder.get(0).offsetLeft,x=this.placeHolder.get(0).offsetTop,y=k,b=m,f=6,i=20,l=0;10>Math.abs(n-k)&&10>Math.abs(x-m)?a():window.setTimeout(d,i)}};return d});
__d("common.js.placeholder",["common.js.browser"],function(q,w,r,a){a("common.js.browser");return function(a,e,f){"length"in a||(a=Array(a));for(var h=0,n=a.length;h<n;h++){"id"in a[h]||(a[h].id="p"+(new Date).getTime());var l=document.createElement("label");l.setAttribute("for",a[h].id);l.innerHTML=e;l.style.cssText="position:absolute;color:#999;z-index:999; background-color: #FFFFFF; ";l.className=f;a[h].parentNode.appendChild(l);a[h].setAttribute("autoComplete","off");a[h].onkeydown=a[h].onmousedown=
function(){l.style.display="none"};l.onclick=function(c){return function(){this.style.display="none";c.focus()}}(a[h]);var c=function(c,a){return function(){""==a.value&&(c.style.display="")}}(l,a[h]);window.addEventListener?a[h].addEventListener("blur",c,!1):a[h].attachEvent("onblur",c)}}});
__d("common.js.timeHint",[],function(){function q(q,r){this.duration=r||3E3;this.timeHandler=null;this.elem=q}q.prototype={show:function(q,r){var a=this,r=r||{};a.timeHandler&&window.clearTimeout(a.timeHandler);r.text&&a.elem.html(r.text);a.elem.css(q);a.elem.show();a.timeHandler=window.setTimeout(function(){a.elem.hide()},a.duration)},hide:function(){this.timeHandler&&(window.clearTimeout(this.timeHandler),this.timeHandler=null);this.elem.hide()}};return q});
__d("widget.popup.confirm",["widget.popup.base"],function(q,w,r,a){q=a("widget.popup.base");$.widget("hao123.confirm",q,{options:{className:"popup-confirm",isModel:!0,okText:"\u786e\u5b9a"},_create:function(){this._baseCreate();var a=this.element,e=this;$(".js_title",a).html(this.options.title);$(".js_text",a).html(this.options.text);$(".js_close",a).click(function(){e._baseHide();e._trigger("close");return!1});$(".js_ok",a).click(function(){e._baseHide();e._trigger("ok")}).text(e.options.okText);
$(".js_cancel",a).click(function(){e._baseHide();e._trigger("cancel")})},show:function(){this._baseShow()}});return r});
__d("common.js.login",["common.js.events","common.js.browser","common.js.placeholder","common.js.log"],function(q,w,r,a){var d=a("common.js.events");a("common.js.browser");a("common.js.placeholder");a("common.js.log");var e=q.document,f={g:function(a){return e.getElementById(a)},extend:function(a,d,c){var a=a||{},k;for(k in d)c?a[k]=d[k]:a.hasOwnProperty(k)||(a[k]=d[k]);return a},addClass:function(a,d){var c=a.className.split(/\s+/);c.push(d);a.className=c.join(" ")},removeClass:function(a,d){for(var c=
a.className.split(/\s+/),k=0;k<c.length;k++)d==c[k]&&c.splice(k,1);a.className=c.join(" ")},format:function(a){var d=Array.prototype.slice.call(arguments,1);return a.replace(/{\d}/g,function(c){c=c.charAt(1);return d[c]})},imageRequest:function(a,d){var c="imageRequest"+(new Date).getTime(),k=new Image;window[c]=k;k.onload=function(){window[c]=null;d("success")};k.onerror=function(){window[c]=null;d("error")};k.src=a}};f.loginConfig={passUrl:"",outerDomId:"popup-login",
loginType:1,staticpage:"https://"+window.location.host+"/jump.htm",tpl:"hao123",phoneText:"\u624b\u673a\u53f7",userNameText:"\u5e10\u3000\u53f7",userNameTextShort:"\u5e10\u53f7",passWordText:"\u5bc6\u3000\u7801",passWordText1:"\u5bc6\u3000\u7801",passWordTextShort:"\u5bc6\u7801",veryfyCodeText:"\u9a8c\u8bc1\u7801",errorText6:"\u9a8c\u8bc1\u7801\u4e0d\u5339\u914d\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165",errorText4:"\u7528\u6237\u540d\u6216\u5bc6\u7801\u9519\u8bef\uff01",errorText1:"\u7528\u6237\u540d\u683c\u5f0f\u9519\u8bef",
errorText2:"\u6b64\u5e10\u53f7\u4e0d\u5b58\u5728",errorText3:"\u624b\u673a\u53f7\u4e0d\u6b63\u786e",errorText110024:'\u6b64\u5e10\u53f7\u8fd8\u672a\u6fc0\u6d3b\uff0c\u8bf7\u5230\u9a8c\u8bc1\u90ae\u4ef6\u4e2d\u6fc0\u6d3b\uff0c\u6216\u8005<a href="{0}">\u91cd\u53d1\u9a8c\u8bc1\u90ae\u4ef6</a>',errorText00:"\u7cfb\u7edf\u9519\u8bef",errorText01:"\u8bf7\u8f93\u5165{0}",veryfyEmailBack:"http://www.hao123.com/",cookieUrl:"http://hao123.baidu.com/static/getcookie.php?noredirect=1",signoutTpl:'<a href="{0}" class="{1}" target="_self">\u767b\u5f55</a><a target="_self" class="{2}" href="http://'+
window.location.host+'/registe.htm">\u6ce8\u518c</a>',signinTpl:'<span class="{2}">\u60a8\u597d\uff0c</span><span class="{3}">{0}</span><a class="{4}" target="_self" href="http://www.hao123.com/api/logout?gotourl={1}">\u9000\u51fa</a>',getUserUrl:"http://www.hao123.com/api/user?key=100&c={0}",loginUrl:"http://www.hao123.com/login.htm?gotourl={0}"};var h=!1;f.loginModel={signin:function(a){h=!0;d.emit("login.signin",a)},otherSignin:function(a){h=!0;d.emit("login.otherSignin",a)},get:function(){return h}};
f.loginView=function(a,d){var c=f.loginConfig;return{onCommonReady:function(){d.g("TANGRAM__PSP_4__userNameLabel").innerHTML=c.userNameText;d.g("TANGRAM__PSP_4__passwordLabel").innerHTML=c.passWordText;d.g("TANGRAM__PSP_4__userName").value="";d.g("TANGRAM__PSP_4__userName").onfocus=d.g("TANGRAM__PSP_4__password").onfocus=d.g("TANGRAM__PSP_4__verifyCode").onfocusin=function(){d.removeClass(this,"login_input_err");d.addClass(this,"login_input_focus")};d.g("TANGRAM__PSP_4__userName").onblur=d.g("TANGRAM__PSP_4__password").onblur=
d.g("TANGRAM__PSP_4__verifyCode").onfocusout=function(){d.removeClass(this,"login_input_focus")}},onLoginSuccess:function(a){d.imageRequest(d.g("TANGRAM__PSP_4__memberPass").checked?"http://hao123.baidu.com/static/getcookie.php?noredirect=1&is_remember=1":"http://hao123.baidu.com/static/getcookie.php?noredirect=1",function(){a&&a()})}}}(window,f);return r={model:f.loginModel,view:f.loginView,config:f.loginConfig}});
__d("widget.popup.login",["widget.popup.base","common.js.login","common.js.events","common.js.profile","common.js.cookie"],function(q,w,r,a){var q=a("widget.popup.base"),d=a("common.js.login"),e=a("common.js.events");a("common.js.profile");var f=a("common.js.cookie"),h="",n;$.widget("hao123.login",q,{options:{className:"popup-login",title:"\u7528\u767e\u5ea6\u5e10\u53f7\u767b\u5f55",isModel:!0},_create:function(){this._baseCreate();var a=this.element;n=this;n._isInit=!1;$(".js_title",a).html(this.options.title);
$(".js_close",a).click(function(){n.hide();e.emit("login.hide");return!1});$(".other_list",a).find("a").click(function(){window.open(this.href,"\u5408\u4f5c\u5e10\u53f7\u767b\u5f55","height=400,width=600,top=0,left=0,toolbar=no,menubar=no,scrollbars=no,resizable=no,location=no,status=no");return!1});e.on("login.show",n.show)},_isOpen:!1,checkIsOpen:function(){return this._isOpen},hide:function(){"quanjiafu"==h?(this._baseHide(null,!0),e.emit("login.closequanjiafu",null,{})):this._baseHide()},show:function(a){function c(c){n.hide();
n._isOpen=!1;"site"==a?$.getJSON("/api/getprof",{c:f.getCSRFId(),key:(new Date).getTime()},function(){window.location.href=window.location.href}):"pan"==a?(d.model.signin({userName:v(c.rsp.data)}),BigPipe.request("/api/ajax?menu=video",["hao123-bodyct"])):"quanjiafu"==a?e.emit("login.quanjiafu",null,{}):window.location.href=window.location.href}function k(){$.getScript(j.passUrl,function(){passport.use("login",{tangram:!0},function(a){var m=new a.passport.login({u:"http://"+window.location.host,tpl:"hao123",
staticPage:"http://"+window.location.host+"/jumpv3.htm",loginMerge:!0,defaultCss:!1,hasPlaceholder:!0,charset:"utf-8"});m.on("loginSuccess",function(a){a.returnValue=!1;c(a)});m.on("render",function(){u.onCommonReady()});m.on("beforeJump",function(a){"400032"===a.rsp.errInfo.no?c(a):m.setGeneralError('\u60a8\u7684\u5e10\u53f7\u56e0\u5b58\u5728\u5b89\u5168\u98ce\u9669\u88ab\u9650\u5236\u767b\u5f55\uff0c\u60a8\u53ef\u4ee5<a href="http://passport.baidu.com/v2/?ucenterfeedback#login">\u53cd\u9988</a>\u7ed9\u6211\u4eec\u3002');
a.returnValue=!1});m.render("login_holder_1")})})}function v(a){if(a.userName){for(var a=a.userName,c=0,d=0;d<a.length;d++)if(a.charAt(d).match(/[u4E00-u9FA5]/)?c++:c+=2,26<c){a=a.substring(0,d-3)+"...";break}return a}return a.phoneNumber||a.mail}h=a;n._baseShow();if(!n._isInit){n._isInit=!0;var j=d.config,u=d.view,g;window.imggetcookie=g=new Image;g.onload=g.onerror=function(){k();window.imggetcookie=void 0};g.src="http://passport.baidu.com/img/v.gif?r="+(new Date).getTime()}}});return r});
__d("widget.popup.alert",["widget.popup.base"],function(q,w,r,a){q=a("widget.popup.base");$.widget("hao123.alert",q,{options:{className:"popup-alert",isModel:!0,okText:"\u786e\u5b9a"},_create:function(){this._baseCreate();var a=this.element,e=this;$(".js_title",a).html(this.options.title);$(".js_text",a).html(this.options.text);$(".js_close",a).click(function(){e._baseHide();return!1});$(".js_ok",a).click(function(){e._baseHide();e._trigger("ok")}).text(e.options.okText)},show:function(){this._baseShow()}});
return r});
__d("widget.site.siteModel","widget.site.config,common.js.events,common.js.cookie,common.js.login,common.js.JSON,common.js.config,common.js.jquery".split(","),function(q,w,r,a){function d(){(new Date).getTime();return e()?{key:(new Date).getTime(),c:e()}:null}function e(){var a=k.getBaiduId();return(a=k.getFlashId()||a)?window.encodeURIComponent(a):null}function f(a){var c=window.location.search.match(/[?&]tn=([^&<>'"]+)/);1==u.get("tnuser")&&(a=a+"?tn="+c[1]);return a}function h(a){if(a)for(var c=0;c<
m.length;c++)m[c].id=a[m[c].id],m[c].style=""}function n(a){return a.replace(/(.*)\/$/,"$1").toLowerCase()}var l=a("widget.site.config"),c=a("common.js.events"),k=a("common.js.cookie"),v=a("common.js.login"),j=a("common.js.JSON"),u=a("common.js.config"),g=a("common.js.jquery"),s=l.url,m=[],t={setData:function(a){m=a},checkLimit:function(a){if(a&&this.getItemById(a).status==l.guestStatus)return 0;for(var c=a=0;c<m.length;c++)m[c].status==l.guestStatus&&a++;return a>=l.guestMaxLength?517:0},getUserDataCount:function(){for(var a=
0,c=0;c<m.length;c++)m[c].status==l.guestStatus&&a++;return a},getData:function(){return m},checkIsShowSave:function(){if(v.model.get())return!1;var a=this.getUserDataCount();return a>=l.showSaveMax?a:!1},checkIsShowRecover:function(){return 0==m.length||500<m[0].id?!0:!1},checkFull:function(){return m.length>=l.siteMaxlength?514:0},checkAddDuplicate:function(a){for(var c=0;c<m.length;c++)if(m[c].url==a)return 501;return 0},checkModifyDuplicate:function(a){if(a.url==this.getItemById(a.id).url)return 0;
for(var c=0;c<m.length;c++)if(m[c].url==a.url)return 501;return 0},init:function(a){m=a},setRecommend:function(){},getModifyItem:function(a){return modifyItem=this.getItemById(a)},getItemById:function(a){for(var c=0;c<m.length;c++)if(m[c].id==a)return m[c]},deleteItemById:function(a){for(var c=0;c<m.length;c++)m[c].id==a&&m.splice(c,1)},getUser:function(){var a=d();g.ajax({url:s.user,success:function(a){switch(a.code){case 200:c.emit("getUser",{userName:a.name,code:200});break;default:c.emit("getUser",
{userName:"",code:a.code})}},error:function(){c.emit("getUser",{userName:"",code:"900"})},data:a,dataType:"json",type:"GET"})},sort:function(a){g.post(s.sort,g.extend({ids:a},d()),function(a){c.emit("operated");switch(a.code){case 200:break;case 201:h(a.data.map);c.emit("firsted",a.data.map);break;default:c.emit("error",{code:a.code,src:"sort"})}},"json")},recover:function(){g.getJSON(s.recover,d(),function(a){switch(a.code){case 200:m=a.data.sites;c.emit("recovered",a.data.sites);break;default:c.emit("error",
{code:a.code,src:"recover"})}})},addTwo:function(a){var j=t.checkAddDuplicate(a.url);0<j?c.emit("error",{code:j,src:"feadd"}):(a.key=(new Date).getTime(),g.post(s.add,g.extend(a,d(),{type:"recommend"}),function(b){c.emit("operated");var d=null;switch(b.code){case 200:d={icon:b.data.icon,name:a.name,url:a.url,id:b.data.id,status:b.data.status,obj:a.obj};m.push(d);c.emit("addtwoed",d);break;default:c.emit("error",{code:b.code,src:"addtwo"})}},"json"))},add:function(a){var j=t.checkAddDuplicate(a.url);
0<j?c.emit("error",{code:j,src:"feadd"}):(a.key=(new Date).getTime(),g.post(s.add,g.extend(a,d()),function(b){c.emit("operated");var d=null;switch(b.code){case 201:h(b.data.map),c.emit("firsted",b.data.map);case 200:d={isRecommend:a.isRecommend,icon:b.data.icon,name:a.name,url:a.url,id:b.data.id,status:b.data.status,type:a.type,obj:a.obj};m.push(d);c.emit("added",d);break;default:d="add",a.isSynadd&&(d="synadd"),c.emit("error",{code:b.code,src:d})}},"json"))},addBanner:function(a,j){g.post(s.add,
g.extend(a,d()),function(b){c.emit("operated");var d=null;switch(b.code){case 200:d={icon:b.data.icon,name:a.name,url:a.url,id:b.data.id,status:b.data.status};m.push(d);j(!0,d);break;default:j(!1,b.code)}},"json")},updateBanner:function(a,m){var b=this;g.post(s.modify,g.extend(a,d()),function(d){c.emit("operated");switch(d.code){case 201:h(d.data.map);var j=b.getItemById(d.data.id);j.name=a.name;j.url=a.url;j.oldId=j.id;j.id=d.data.id;j.status=d.data.status;j.icon=d.data.icon;m(!0,j);break;default:m(!1,
d.code)}},"json")},adds:function(a){var k=j.parse(a);g.post(s.adds,g.extend(d(),{urls:a}),function(a){c.emit("operated");switch(a.code){case 200:m=m.concat(k),h(a.data.map),c.emit("addsed",m)}},"json")},addClickSync:function(a){g.post(s.add,g.extend(a,d(),{type:"recommend"}),function(d){c.emit("operated");var b=null;switch(d.code){case 201:h(d.data.map),c.emit("firsted",d.data.map);case 200:b={icon:d.data.icon,name:a.name,url:a.url,id:d.data.id,status:d.data.status};m.push(b);c.emit("addClickSynced",
b);break;default:c.emit("error",{code:d.code,src:"addClickSync"})}},"json")},doDelete:function(a,j){g.getJSON(s.doDelete,g.extend({id:a},d()),function(b){c.emit("operated");switch(b.code){case 201:t.deleteItemById(a);h(b.data.map);j||c.emit("firsted",b.data.map);c.emit("delete");break;case 200:t.deleteItemById(a);c.emit("delete");break;default:c.emit("error",{code:b.code,src:"del"})}})},delRecommend:function(){g.getJSON(f(s.delRecommend),d(),function(a){500<=a.code&&c.emit("error",{code:a.code,src:"delRecommend"})})},
delRecombyid:function(a){g.getJSON(f(s.delRecombyid),g.extend({id:a},d()),function(a){500<=a.code&&c.emit("error",{code:a.code,src:"delRecombyid"})})},modify:function(a,j){var b=t.checkModifyDuplicate(a);if(0<b)c.emit("error",{code:b,src:"femodify"});else{var m=this;g.post(s.modify,g.extend(a,d()),function(b){c.emit("operated");switch(b.code){case 201:h(b.data.map),j||c.emit("firsted",b.data.map);case 200:var d=m.getItemById(201==b.code?b.data.map[b.data.oldid]:b.data.oldid);d.name=a.name;d.url=a.url;
d.id=b.data.id;d.status=b.data.status;d.icon=b.data.icon;j||c.emit("modified",d);break;default:c.emit("error",{code:b.code,src:"modify"})}},"json")}},refresh:function(){var a=d();if(!a)return!1;g.ajax({url:s.init,success:function(a){switch(a.code){case 200:a.data.isuser?(m=a.data.sites,c.emit("refreshed",!0)):c.emit("refreshed",!1);break;default:c.emit("error",{code:a.code,src:"refreshSuccess"})}},error:function(){g.ajax({url:s,data:d(),success:function(a){c.emit("error",{code:"588",src:"refresh"+
a.substring(0,500)})},dataType:"text",type:"GET"})},data:a,dataType:"json",type:"GET"})},sortData:function(a){var c={};g.each(m,function(){c[this.id]=this});m=[];g.each(a,function(){m.push(c[this])});return m},getCRdata:function(){var a=d();a.n=6;var j={};g.each(m,function(){j[n(this.url)]=this.id});0<document.URL.indexOf("sitepopuppreview")&&(a.preview=1);g.ajax({url:f(s.cr),success:function(a){g.each(a.data.cms,function(){this.isTitle||(this.isAdded=Boolean(j[n(this.url)]),this.id=j[n(this.url)])});
c.emit("cred",a)},error:function(a,d,j){c.emit("error",{code:599,src:"cr"+d+j})},data:a,dataType:"json",type:"GET"})}};return t});
__d("widget.site.siteView","widget.site.config,common.js.events,common.js.cookie,common.js.format,common.js.browser,common.js.JSON,common.js.config,common.js.widget,widget.suggest.suggest,widget.suggest.nssug".split(","),function(q,w,r,a){function d(){e("");f("")}function e(a){b.sugName.val(a);""==a?p.sugNamePlaceholder.show():p.sugNamePlaceholder.hide()}function f(a){b.sugUrl.val(a);""==a?p.sugUrlPlaceholder.show():p.sugUrlPlaceholder.hide()}function h(a){a=$.trim(a);/^.+:\/\/.*$/i.test(a)||(a="http://"+
a);a=a.replace(/^(.+:\/\/)([^\/?]+)(.*)$/,function(a,b,A,o){return/^(https?|ftp)/i.test(b)?b.toLowerCase()+A.toLowerCase()+o:"http://"+A.toLowerCase()+o});a=a.replace(/^(.+:\/\/[^\/?]+)[\/?]$/,"$1");return a=a.replace(/\x3c/g,"").replace(/\x3E/g,"").replace(/\x22/g,"").replace(/\x27/g,"")}function n(a){return a?"http://img"+(a.split(".")[0]%2+1)+"."+g.iconBaseUrl+a:g.defaultIconUrl}function l(a){a=$.trim(a);a=a.replace(/^(.+:\/\/[^\/?]+)[\/?]$/,"$1");return j(a)}function c(a){return 6>a.length?"":
k(a)}function k(a){for(var a=$.trim(a),b=0,o=0;o<a.length;o++)if(b=/\w/.test(a.charAt(o))?b+8:b+14,80<b){a=a.substring(0,o)+"...";break}2==a.length?a=a.charAt(0)+"&#12288;"+a.charAt(1):3==a.length&&(a=a.charAt(0)+" "+a.charAt(1)+" "+a.charAt(2));return j(a,!0)}function v(a){return a.replace("&#12288;","").replace(/ /g,"").replace("\u3000","")}function j(a){return a=a.replace(/\x3c/g,"&lt;").replace(/\x3E/g,"&gt;").replace(/\x22/g,"&quot;").replace(/\x27/g,"&#39;")}function u(a,b){return!a||!b?!1:
a.replace(/(.*)\/$/,"$1").toLowerCase()==b.replace(/(.*)\/$/,"$1").toLowerCase()}var g=a("widget.site.config"),s=a("common.js.events"),m=a("common.js.cookie"),t=a("common.js.format");a("common.js.browser");var x=a("common.js.JSON"),y=a("common.js.config");a("common.js.widget");a("widget.suggest.suggest");var q=a("widget.suggest.nssug"),b,p,i=g.jsItem,z=null,o=null;return r={onBannerAdd:function(a){a=$(t(g.tpl.item,{id:a.id,name:k(a.name),url:l(a.url),icon:n(a.icon),title:c(a.name),status:a.status}));
a.width(108);a.insertBefore(b.bd.find(".js_item-add"));b.bd.find(".js_item-add").remove();this._addAddBtn()},updateBanner:function(a,b,o){var c=$("#site .site-hot-w");$(".site-hot-relink",c);var d=$(".site-hot-link",c),j=$(".site-hot-link2",c),m=n(a.icon),g=d.offset().top-b.offset.top,i=d.offset().left-b.offset.left;(function(){j.show().animate({left:"-="+i,top:"-="+g,opacity:1},500,function(){j.hide();$(".js_text",b.link).html(k(a.name));$(".js_text",b.link).attr("style","background:url("+m+") no-repeat 0px 2px;");
$(".js_text",b.link).attr("href",d.attr("href"));o._hideBanner();o._trigger("bannerlink",null,{iu:0})})})()},onSecondAdd:function(a){$(t(g.tpl.item,{id:a.id,name:k(a.name),url:l(a.url),icon:n(a.icon),title:c(a.name),status:a.status})).insertBefore(b.bd.find(".js_item-add"));b.bd.find(".js_item-add").remove();this._addAddBtn()},doBlink:function(){var a=0,o=["#f3f3f3","#f7f7f7"];window.setTimeout(function(){b.blink.css("background-color",o[a%2]);a++;8>a&&window.setTimeout(arguments.callee,200)},200)},
_getPosition:function(a){for(var b={left:a.offsetLeft,top:a.offsetTop},a=a.offsetParent;a&&!$(a).hasClass("popup-site");)b.left+=a.offsetLeft,b.top+=a.offsetTop,a=a.offsetParent;b.top-=34;return b},on517:function(){d();b.modify.hide();b.add.show()},getRecommends:function(){var a=[];b.recommends.each(function(){var b=$(this).find("a");a.push({name:b.html(),url:b.get(0).getAttribute("href",2),id:$(this).attr("data-id"),icon:$(this).attr("data-icon"),status:1})});return x.stringify(a)},onAddClickSynced:function(a){$(t(g.tpl.item,
{id:this.id,name:k(a.name),url:l(a.url),icon:n(a.icon),title:c(a.name),status:a.status})).insertBefore(b.topRecommend);b.topRecommend.remove();b.topRecommendHint.remove()},clearHint:function(){b.hintSug.hide();b.hintSave.hide();b.hintNoicon.hide();b.hintAdded.hide()},onRcommendDeleteOver:function(a){a=p._getPosition(a);a.left-=45;a.top-=6;b.hintNoicon.show(a,{text:g.emptyText})},onRcommendDeleteOut:function(){b.hintNoicon.hide()},onImported:function(a){if("none"!=b.psite.get(0).style.display){p.updatePopup(a);
p.clearError();d();var o={};$.each(a,function(){o[this.url]=this.id});b.psite.find(".item").each(function(){var a=this.href.replace(/(.*)\/$/,"$1");o[a]&&(this.className="item item-added",this.setAttribute("data-id",o[a]))})}else this.update(a)},onRefreshed:function(a){a?(b.refresh.show(),b.manage.hide(),b.bd.find(".js_item-add").hide()):(b.refresh.hide(),b.manage.show(),b.bd.find(".js_item-add").show())},onRefreshClick:function(a){b.refresh.hide();b.manage.show();p.update(a)},onAddedClick:function(a){p._recoverAdded(a.href);
d();b.modify.hide();b.add.show();b.sites.find(i).each(function(){if(this.getAttribute("data-id")==a.getAttribute("data-id"))return $(this).remove(),!1});this.clearError();b.hintNoicon.hide();b.hintAdded.hide();b.hintSave.hide();b.hintSug.hide();b.recover.show();return a.getAttribute("data-id")},onAddedItemOut:function(){b.hintNoicon.hide()},onAddedItemOver:function(a){b.hintAdded.hide();b.hintNoicon.show(p._getPosition(a),{text:g.adddedText})},onItemClick:function(a){var b=a.innerHTML,c=a.getAttribute("href",
2);return""!=$.trim(b)&&""!=$.trim(c)?(o=a,{name:$.trim(b),url:h(c),type:a.getAttribute("data-type")}):!1},onFirsted:function(a){b.sites.find(i).each(function(){var b=this.getAttribute("data-id");this.setAttribute("data-id",a[b])})},onRecovered:function(a){b.noDataHint.hide();b.recover.hide();b.saveForeverHint.hide();p.updatePopup(a);b.cms.find(".item-added").each(function(){this.className="js_recommend item item-normal"});b.recommendContent.find(".item-added").each(function(){this.className="js_recommend item item-add"});
$.each(a,function(){});this.clearError();d();b.add.show();b.modify.hide();b.hintAdded.hide()},onRecommendControlClick:function(){b.recommend.html(g.tpl.recommendNone);b.options.recommendCount=0;b.hintNoicon.hide()},onSorted:function(){var a=[];b.recover.show();$(i,b.sites).each(function(){var b=this.getAttribute("data-id");""!=$.trim(b)&&a.push(b)});return a},onCred:function(a){b.recommendContent.html("");if(0<b.recommendData.length){b.recommendCount.html(b.recommendData.length);var o=g.tpl.recommend;
$.each(b.recommendData,function(){b.recommendContent.append(t(o,{name:j(this.title),url:l(this.url),id:this.id}))});b.recommend.show()}else b.recommend.hide();var c=[];b.cms.html("");m.get("stip0")?m.get("stip1")?b.tipDel.hide():b.tipDel.show():b.cms.html(g.tpl.tipTpl);!m.get("stip2")&&!b._tipsave?b.tipSave.show():b.tipSave.hide();b._tipsave2=!0;$.each(a.data.cms,function(){this.isTitle?(b.cms.append(t(g.tpl.cms,{name:this.name,content:c.join("")})),c=[]):c.push(t(g.tpl.cmsContent,{className:this.isAdded?
"item item-added":"js_recommend item item-normal",name:this.name,url:this.url,id:this.id,itemStyle:this.isImportant?"class='important'":""}))})},onItemModifyClick:function(a){b.modify.show();b.add.hide();z=a=$(a);b.sugName.get(0).focus();e(a.attr("data-name"));f(a.attr("data-url"));p.clearError()},_recoverAdded:function(a){b.psite.find(".item-added").each(function(){u(a,this.href)&&(this.className="cms"==this.getAttribute("data-type")?"js_recommend item item-normal":"js_recommend item item-add")})},
onItemDeleteClick:function(a){b.psite.find(".item-added").each(function(){var b=this.getAttribute("data-id");if(b&&b==a.getAttribute("data-id"))return p._recoverAdded(this.href),!1});$(a).remove();b.recover.show();d();b.add.show();b.hintAdded.hide();b.modify.hide();0==b.sites.find(".js_site-item").length&&(b.noDataHint.show(),b.sites.hide())},onAdded:function(a){b.noDataHint.hide();b.hintSave.hide();b.recover.show();b.sites.show();b.sites.append(t(g.tpl.editItem,{id:a.id,url:l(a.url),name:k(a.name),
rawName:a.name}));d();a.type&&(b.hintAdded.show(p._getPosition(o),{text:g.addedText}),o=null);$(".js_recommend",b.psite).each(function(){u(this.getAttribute("href",2),a.url)&&(this.className="item item-added",this.setAttribute("data-id",a.id))})},onModified:function(a){b.add.show();b.recover.show();b.modify.hide();$(t(g.tpl.editItem,{id:a.id,url:l(a.url),name:k(a.name),rawName:a.name})).insertBefore(z);z.remove();d();$(".item-added",b.psite).each(function(){u(this.href,z.attr("data-url"))&&(this.className=
"cms"==this.getAttribute("data-type")?"js_recommend item item-normal":"js_recommend item item-add")});z=null},_refreshState:function(a){$(".js_recommend",b.psite).each(function(){u(this.href,a.url)&&(this.className="item item-added",this.setAttribute("data-id",a.id))})},onAddClick:function(){if(!this._check())return!1;this.clearError();return{name:$.trim(b.sugName.val()),url:h(b.sugUrl.val())}},onModifyClick:function(){if(!this._check())return!1;this.clearError();return{name:$.trim(b.sugName.val()),
url:h(b.sugUrl.val()),id:z.attr("data-id")}},init:function(a){b=a;1==y.get("isStatic")&&(b.manage.hide(),b.bd.find(".js_item-add").hide());a=!1;p=this;p.sugNamePlaceholder=$("#js_placeholder-name");p.sugUrlPlaceholder=$("#js_placeholder-url");b.sugName.bind("focus keydown",function(){p.sugNamePlaceholder.hide()});b.sugUrl.bind("focus keydown",function(){p.sugUrlPlaceholder.hide()});b.sugName.blur(function(){""==this.value&&p.sugNamePlaceholder.show()});b.sugUrl.blur(function(){""==this.value&&p.sugUrlPlaceholder.show()});
var o=m.getFlashId();!b.isLanding&&null==o&&(a=!0,b.bd.find(".js_item-add").hide(),b.manage.hide());b.isLanding&&b.save.hide();return a},showRefresh:function(){b.refresh.show()},onManageClick:function(a,o){a?b.recover&&b.recover.show():b.recover&&b.recover.hide();d();o?p.showSaveMessage():b.saveForeverHint.hide()},showSaveMessage:function(){m.get(b.saveHintCookie)||(b.saveForeverHint.show(),b._tipsave=!0,b._tipsave2&&b.tipSave.hide())},getSiteData:function(){var a=[],o=this;$(i+':not(".site-item-recommend")',
b.bd).each(function(){var b=this.children[0];a.push({id:this.getAttribute("data-id"),name:v(b.getAttribute("data-title")),url:b.getAttribute("href",2),status:this.getAttribute("data-status"),icon:o._getIcon(b),style:this.getAttribute("data-style")})});return a},_getIcon:function(a){var b=a.parentNode.getAttribute("data-icon");return b?b:""!=a.style.backgroundImage?a.style.backgroundImage.match(/^.*\/([^)]+)/)[1]:"6000.png"},update:function(a){if(0>=a.length)b.bd.html(g.tpl.noData);else{var o=[];$.each(a,
function(){var a=t(g.tpl.item,{id:this.id,name:k(this.name),url:l(this.url),icon:n(this.icon),title:c(this.name),status:this.status,style:this.style});1==this.status&&"\u4f18\u9177\u7f51"==this.name&&(a=t('<li class="js_site-item g-ib site-item site-item-normal " data-id="#{id}" data-status="1"><a class="js_text " href="http://www.youku.com" style="background-image:url(http://img2.hao123.com/urlicon/10605.png)" data-title="\u4f18\u9177\u7f51" hidefocus="true">\u4f18\u9177</a>&nbsp;\u2022&nbsp;<a href="http://v.hao123.com/dianying/ " style="background: none;padding-left: 0;">\u7535\u5f71</a></li>',
{id:this.id}));1==this.status&&"\u817e\u8baf"==this.name&&(a=t('<li class="js_site-item g-ib site-item site-item-normal " data-id="#{id}" data-status="1"><a class="js_text " href="http://www.qq.com" style="background-image:url(http://img1.hao123.com/urlicon/7082.png)" data-title="\u817e\u8baf\u7f51" hidefocus="true">\u817e\u8baf</a>&nbsp;\u2022&nbsp;<a href="http://qzone.qq.com/ " style="background: none;padding-left: 0;" class="g_red">\u7a7a\u95f4</a></li>',{id:this.id}));1==this.status&&"\u65b0\u534e"==
this.name&&(a=t('<li class="js_site-item g-ib site-item site-item-normal " data-id="#{id}" data-status="1"><a class="js_text " href="http://www.xinhuanet.com/" style="background-image:url(http://img2.hao123.com/urlicon/10435.png)" data-title="\u65b0\u534e" hidefocus="true">\u65b0\u534e</a>&nbsp;\u2022&nbsp;<a href="http://www.people.com.cn/" style="background: none;padding-left: 0;">\u4eba\u6c11</a></li>',{id:this.id}));1==this.status&&"\u5f71\u89c6"==this.name&&(a=t('<li class="js_site-item g-ib site-item site-item-normal " data-id="#{id}" data-status="1"><a class="js_text " href="http://www.people.com.cn/" style="background-image:url(http://img1.hao123.com/urlicon/8604.png)" data-title="\u5f71\u89c6" hidefocus="true">\u5f71\u89c6</a>&nbsp;\u2022&nbsp;<a href="http://live.hao123.com/" style="background: none;padding-left: 0;">\u76f4\u64ad</a></li>',
{id:this.id}));o.push(a)});b.bd.html(o.join(""));this._addAddBtn();b.add.show();b.modify.hide();d()}},_addAddBtn:function(){var a=b.bd.find(".js_site-item").length;if(6!=a){var o="";0<b.recommendData.length&&(o=t(g.tpl.addRecommend,{count:b.recommendData.length}));if(0==a%6){var a=";max-width:60px;_width:60px;min-width:56px; overflow:hidden; text-overflow: ellipsis;white-space: nowrap;",c=b.bd.find("li:last a").get(0);if(1==b.bd.find("li:last").data("status")&&("\u4f18\u9177"==c.innerHTML||"\u817e\u8baf"==
c.innerHTML||"\u65b0\u534e"==c.innerHTML||"\u5f71\u89c6"==c.innerHTML))a="";c.style.cssText+=a;b.bd.append(t(g.tpl.addShortBtn,{recommend:o}))}else b.bd.append(t(g.tpl.addNormalBtn,{recommend:o}))}},updatePopup:function(a){var o=[];$.each(a,function(){o.push(t(g.tpl.editItem,{id:this.id,url:l(this.url),name:k(this.name),rawName:this.name}))});0==o.length?(b.noDataHint&&b.noDataHint.show(),b.sites&&b.sites.hide()):(b.noDataHint&&b.noDataHint.hide(),b.sites&&b.sites.html(o.join("")).show())},initSug:function(){b.sugName.suggest({classes:"suggest-site",
eventSpace:"sitesuggest"}).suggest("handler",this._nssug).on("suggestinput",function(){if(""!=$.trim(b.sugUrl.val()))return!1});b.sugUrl.suggest({classes:"suggest-site",eventSpace:"sitesuggest"}).suggest("handler",this._nssug).on("suggestinput",function(){if(""!=$.trim(b.sugName.val()))return!1});s.on("sitesuggest.change",function(a){if(0==a.index)return!0;e(a.data[0]);f(a.data[1]);return!1});s.on("sitesuggest.submit",function(){"none"!=b.add.get(0).style.display?b.add.click():b.modify.click();return!1})},
_nssug:q("superpage",{sc:"hao123"},function(a){var b=a.s,o={},a=a.q;if(0==b.length)this.hide();else{this.clear();for(var c=0,d=0;c<b.length&&5>d;c++){var j=$.parseJSON(b[c].split("0{#S+_}")[1]);j&&(j[1]=j[1]||"",j[4]&&(j[4]=j[4]||"",o[j[4]]||(d++,o[j[4]]=!0,this.add(j[4],t('<span class="name">#{title}</span><span class="url">#{text}</span>',{title:j[4].replace(a,"<strong>"+a+"</strong>"),text:j[1].replace(a,"<strong>"+a+"</strong>")}),[j[4],j[1]]))))}this.show()}}),clearError:function(){b.sugName.removeClass(g.css.sugError);
b.sugUrl.removeClass(g.css.sugError);b.hintSug.hide()},showError:function(a){switch(a){case 515:case 512:b.hintSug.show(p._getPosition(b.sugName.get(0)),{text:g.error[a]});b.sugName.addClass(g.css.sugError).get(0).focus();b.sugUrl.removeClass(g.css.sugError);break;case 516:case 513:case 501:b.hintSug&&(b.hintSug.show(p._getPosition(b.sugUrl.get(0)),{text:g.error[a]}),b.sugUrl.addClass(g.css.sugError).get(0).focus(),b.sugName.removeClass(g.css.sugError));break;case 514:b.hintSave.show(p._getPosition(b.sugUrl.get(0)),
{text:g.error[a]});break;case 507:break;case 599:break;case 588:break;case 600:case 601:case 602:case 603:b.hintSug.show(p._getPosition(b.sugUrl.get(0)),{text:"\u51fa\u73b0\u9519\u8bef\uff0c\u8bf7\u7a0d\u4faf\u91cd\u8bd5\uff01"});break;case 900:break;case 500:break;default:b.hintSave&&b.hintSave.show(p._getPosition(b.sugUrl.get(0)),{text:g.error[a]})}},_check:function(){var a=$.trim(b.sugName.val()),o=$.trim(b.sugUrl.val());if(""==a)return this.showError(515);if(0>=o.length||/^(https?:\/\/|ftp:\/\/)$/i.test(o))return this.showError(516);
if(a.length>g.nameMaxLength)return this.showError(512);if(o.length>g.urlMaxLength)return this.showError(513);this.clearError();return!0}}});
__d("widget.site.log",["common.js.login","common.js.log","common.js.config"],function(q,w,r,a){function d(a,d){var a=a||{},c;for(c in d)a[c]=d[c];return a}var e=a("common.js.login"),f=a("common.js.log"),h=a("common.js.config");return function(a){function l(){return e.model.get()}var c={level:1,page:h.get("pageId")};0<$('#site .js_site-item[data-status="0"]').length&&f(d({type:"rpuser2",ut:"haveadd"},c));!h.get("userinfo").iscuser&&h.get("userinfo").recommendData&&f(d({type:"rpuser2",ut:"defadd"},
c));a.bind("sitemanageclick",function(){var a=d({type:"manage",isLogin:l()},c);f(a)});a.bind("siteintoaddclick",function(){var a=d({type:"intoadd",isLogin:l()},c);f(a)});a.bind("sitenoneaddclick",function(){var a=d({type:"noneadd"},c);f(a)});a.bind("sitelogin",function(a,e){var j=d({type:e.login,twicetype:e.twicelogin},c);f(j)});a.bind("sitedefaultlogin",function(){var a=$.parseJSON(h.get("userinfo").cinfo),a=d({type:"defaultLogin",cinfo:a?a.loginFrom:""},c);f(a)});a.bind("siteadd",function(a,e){f(d({type:"add",
siteId:e.id,siteUrl:e.url,isLogin:l()},c))});a.bind("siteaddsync",function(a,e){f(d({type:"addsync",siteId:e.id,siteUrl:e.url,isLogin:l()},c))});a.bind("siterecommend",function(a,e){var j=d({type:"recommend",siteId:e.id,siteUrl:e.url,isLogin:l()},c);f(j)});a.bind("siteaddclicksync",function(a,e){var j=d({type:"addclicksync",siteId:e.id,siteUrl:e.url,isLogin:l()},c);f(j)});a.bind("sitecms",function(a,e){var j=d({type:"cms",siteId:e.id,siteUrl:e.url,isLogin:l()},c);f(j)});a.bind("sitemodify",function(a,
e){var j=d({type:"modify",siteId:e.id,siteUrl:e.url,isLogin:l()},c);f(j)});a.bind("sitedeletesync",function(){var a=d({type:"syncdelete"},c);f(a)});a.bind("sitedodelete",function(a,e){var j=d({type:"delete",siteId:e.id,siteUrl:e.url,isLogin:l()},c);f(j)});a.bind("siterecovered",function(){var a=d({type:"recover",isLogin:l()},c);f(a)});a.bind("sitetextclick",function(a,e){var j=d({type:"textclick",siteId:e.id,siteUrl:e.url,status:e.status,isLogin:l()},c);f(j)});a.bind("siterefresh",function(){var a=
d({type:"refresh"},c);f(a)});a.bind("siteerror",function(a,e){var j=d({type:"siteerror",code:e.code},c);e.info&&(j.info=e.info);f(j)});a.bind("siteerrorflash",function(){var a=d({type:"siteerrorflash"},c);f(a)});a.bind("sitemanagerecommend",function(){var a=d({type:"managerecommend"},c);f(a)});a.bind("sitedeleteallrecommend",function(){var a=d({type:"deleteallrecommend"},c);f(a)});a.bind("sitegetusererror",function(a,e){var j=d({type:"getusererror",code:e},c);f(j)});a.bind("sitehintclose",function(){var a=
d({type:"sitehintclose"},c);f(a)})}});
__d("widget.site.siteRecord",["common.js.JSON"],function(q,w,r,a){function d(){n=(n=window.localStorage.getItem(l))?h.parse(n):n}function e(a){null===n&&(n={});a in n||(n[a]=0);n[a]+=1;window.localStorage.setItem(l,h.stringify(n))}function f(){}var h=a("common.js.JSON"),n=null,l="index_sites",q=null,q={get:function(a){if(null===n)return a[0];var d=Number.MAX_VALUE,e;$.each(a,function(a,c){if(d>(n[c]?n[c]:0))d=n[c],e=c});return e}};window.localStorage?(q.add=e,q.init=d):(q.add=f,q.init=f);return q});
__d("widget.site.siteBanner","common.js.config,common.js.events,common.js.format,common.js.cookie,widget.site.siteModel,common.js.adjust,widget.site.siteRecord".split(","),function(q,w,r,a){var d;function e(a,c){var j;j=$(l(d,{title:a.title,url:a.url}));var g=u.find(".js_link").offset();j.css({top:g.top-20,left:g.left});g=$('#site li[data-id="'+a.id+'"]').offset();j.animate({top:g.top,left:g.left},1E3,function(){j.remove();c()});$("body").append(j)}function f(a){var c=/(https?|ftp):\/\/[^\/]+/,d=
a.match(c);if(!d)return!1;var d=d[0],j=!0;$("#site .js_text").each(function(a,m){if(0<=m.getAttribute("href",2).match(c).indexOf(d))return j=!1,!0});return j}var h=a("common.js.config"),n=a("common.js.events"),l=a("common.js.format"),c=a("common.js.cookie"),k=a("widget.site.siteModel"),v=a("common.js.adjust").adjust,j=a("widget.site.siteRecord"),u;d='<div class="site-move-item" style="background-image:url(http://img2.hao123.com/urlicon/#{icon})">#{title}</div>';var g,s=null;return r={excute:function(a){if(!h.get("userinfo").iscuser&&
!c.has("sitebanner")&&1===a.isShow){var d=h.get("userinfo").recommendData;if(!(d&&2<=d.length)){d&&1==d.length?s=d[0]:j.init();u=$("#site .site-hot-w");switch(a.type){case "replace":g=j.get(a.filterReplace);a.info2=k.getItemById(g).name;if(s&&(a.title=s.title,a.url=s.url,a.id=s.id,!f(a.url)))return;u.html(l('<div class="site-hot"><span>#{info}</span><span class="site-hot-relink">#{info2}</span><span class="site-hot-label">\u63a8\u8350\u66ff\u6362\u4e3a\uff1a</span><a class="site-hot-link site-hot-link-add js_link" href="#{url}"  hidefocu="true">#{title}</a><a class="site-hot-more js_more"  hidefocu="true">#{more}&nbsp;&gt;&gt;</a><a class="site-hot-close js_close" href="###"  hidefocu="true">\u5173\u95ed</a></div>',
a)).show();break;case "del":g=j.get(a.filterDelete),a.info2=k.getItemById(g).name,u.html(l('<div class="site-hot"><span>#{info}</span><span class="site-hot-relink">#{info2}</span><span class="site-hot-label">\u5efa\u8bae\u60a8\uff1a</span><a class="site-hot-link site-hot-link-del js_link" href="#" hidefocu="true">\u4e00\u952e\u5220\u9664</a><a class="site-hot-more js_more"  hidefocu="true">#{more}&nbsp;&gt;&gt;</a><a class="site-hot-close js_close" href="###"  hidefocu="true">\u5173\u95ed</a></div>',
a)).show()}u.find(".js_close").click(function(){c.set("sitebanner",1,{expires:30});u.slideUp();n.emit("banner.close",a.type);return!1});u.find(".js_more").click(function(){n.emit("banner.other",a.type);a.moreHandler()});u.find(".js_link").click(function(){var c={title:this.innerHTML,url:this.href,id:g,icon:a.icon};switch(a.type){case "replace":e(c,function(){a.replaceHandler(c);u.slideUp()});break;case "del":a.deleteHandler(c,u)}n.emit("banner.link",a.type);return!1});v();n.emit("banner.show",a.type)}}},
hide:function(){u&&u.hide(v)},slideUp:function(){u&&u.slideUp(v)},add:function(a){j.add(a)}}});
__d("widget.site.siteBannerLog",["common.js.events","common.js.log"],function(q,w,r,a){var d=a("common.js.events"),e=a("common.js.log");return function(){d.on("banner.show",function(a){e({type:"sitebannershow",sort:a})});d.on("banner.close",function(a){e({type:"sitebannerclose",sort:a})});d.on("banner.other",function(a){e({type:"sitebannerother",sort:a})});d.on("banner.link",function(a){e({type:"sitebannerlink",sort:a})})}});
__d("widget.site.site","common.js.format,common.js.events,common.js.cookie,common.js.config,common.js.profile,widget.popup.getTpl,common.js.adjust,common.js.timeHint,common.js.browser,widget.site.siteBanner,widget.site.siteBannerLog,widget.popup.mask,widget.append.append,widget.popup.confirm,widget.popup.alert,widget.site.siteModel,common.js.login,widget.site.config,widget.site.siteView,widget.site.log,common.js.log,common.js.localcookie,widget.site.drag,common.js.widget".split(","),function(q,w,
r,a){var d=a("common.js.format"),e=a("common.js.events"),f=a("common.js.cookie"),h=a("common.js.config"),n=a("common.js.profile"),l=a("widget.popup.getTpl"),c=a("common.js.adjust").adjust,k=a("common.js.timeHint"),v=a("common.js.browser"),j=a("widget.site.siteBanner"),u=a("widget.site.siteBannerLog"),g=a("widget.popup.mask"),s=a("widget.append.append");a("widget.popup.confirm");a("widget.popup.alert");var m=a("widget.site.siteModel"),t=a("common.js.login"),x=a("widget.site.config"),y=a("widget.site.siteView");
a("widget.site.log");a("common.js.log");var b=a("common.js.localcookie"),p=a("widget.site.drag"),i,z=!1;a("common.js.widget");$.widget("hao123.site",{options:{},_initTask:function(){function a(){f.set(b,1,{expires:0})}var b,c=window.location.search.match(/\?key=([^<>&]+)&taskid=5/);c&&c[1]&&(this.isTask=!0,b=c[1],this._onManageClick(),e.on("added",a),e.on("modified",a),e.on("delete",a))},_initBanner:function(){u();i.siteBannerConfig=$.extend(i.options.banner,{replaceHandler:function(a){i.bd.find('[data-id="'+
a.id+'"]').find("a").text(a.title).attr("href",a.url).get(0).style.background="url(http://img2.hao123.com/urlicon/"+a.icon+") no-repeat 0 0";i.model.modify({name:a.title,url:a.url,id:a.id},!0)},deleteHandler:function(a){i.bd.find('[data-id="'+a.id+'"]').slideUp(800,function(){i.model.doDelete(a.id,!0);j.slideUp()})},moreHandler:function(){i._onManageClick();j.hide()},filterReplace:i.options.banner.filterReplace.split(","),filterDelete:i.options.banner.filterDelete.split(",")});var a=$("#site");a.on("click",
".js_item-add",function(){j.hide()});$(".js_manage",a).click(function(){j.hide()});$(".js_text",a).click(function(){var a=this.parentNode.getAttribute("data-id");j.add(a)})},_init:function(){var a=this.element;i=this;i.config=x;i.recommendData=h.get("userinfo").recommendData||[];for(var b=[];5<i.recommendData.length;)i.recommendData.pop();i.recommend2Text=b.title;i.recommend2Url=b.url;i.retried=0;i.isFromTopLogin=!1;i.view=y;i.model=m;i.login=t.model;i.confirmPopup=$(l("confirm")).confirm({title:i.config.confirmTitle,
text:i.config.confirmText});i.recoverPopup=$(l("confirm")).confirm({title:i.config.recoverTitle,text:i.config.recoverText});i.alertPopup=$(l("alert")).alert({title:i.config.alertTitle,text:i.config.alertText});i.recommends=$(".site-item-recommend",a);i.loading=$(".popup-site-loading",a);i.popContent=$(".popup-site-content",a);i.refresh=$(".js_refresh",a);i.refreshButton=$(".js_refresh-button",a);i.manage=$(".js_manage",a);i.add=$(".js_psite-add",a);i.modify=$(".js_psite-modify",a);i.psite=$(".js_psite",
a);i.sugName=$(".js_sug-name",a);i.sugUrl=$(".js_sug-url",a);i.save=$(".js_psite-save",a);i.saveForeverHint=$(".js_hint-saveForever",a);i.bd=$(".js_bd",a);i.dash=$("<li></li>");i.addCount=$(".js_add-count",a);i.topRecommend=$(".site-item-recommend",a);i.topRecommendLink=i.topRecommend.find(".js_text");i.topRecommendDelete=$(".js_recommend_delete",a);i.topRecommendHint=$(".site-item-recommend-hint",a);i.context=$("#popup-site-holder");i.psite.appendTo(i.context);i.recommend2Js=$(d("<div class='rpjs'><div class='rp'><em class='left'></em><span>\u63a8\u8350:</span><a data-max-width='90' href='#{url}'>#{text}</a><i></i></div>",
{text:i.recommend2Text,url:i.recommend2Url}));i.recommend2=i.recommend2Js.find(".rp");i.recommend2Em=i.recommend2Js.find("em");i.recommend2Link=i.recommend2.find("a");i.recommend2key="site_recommend2";i._bind();z||(i._eventBind(),z=!0);i.init();i.saveHintCookie="site_shave_hint";$(function(){window.setTimeout(i._hint,100);var a=h.get("userinfo").iscuser,b=0;$("li",i.bd).each(function(a,o){if(0==o.getAttribute("data-status"))return b=1,!1});i._trigger("rp",null,{iszdyuser:a,isrpuser:b})});i._initTask()},
_initRecommend:function(){i.recommends.click(function(){i.model.adds(i.view.getRecommends());i.recommends.removeClass("site-item-recommend")})},init:function(){var a=this;a.isLanding=h.get("userinfo").islanding;a.userName=h.get("userinfo").username;a._initRecommend();a._initBanner();a.isLanding&&(a._trigger("defaultlogin",null),a.login.signin({isInit:!0,userName:a.userName}),a.userName||a.model.getUser());var c;0<a.recommend2Link.length&&(c=a.recommend2Link.get(0).getAttribute("href",2));c=a.view.init(a,
c);a.model.init(a.view.getSiteData());if(c){a.needRefresh=!0;var d=f.getBaiduId();b.wait(function(b,c){b&&c&&c!=d?a.model.refresh():(a.bd.find(".js_item-add").show(),a.manage.show(),j.excute(a.siteBannerConfig))},2E3)}else j.excute(a.siteBannerConfig);this._ajust();this._delete1();this._delete2()},_initPopupVariable:function(){var a=this.context;this.close=$(".js_psite-close",a);this.sites=$(".js_psite-sites",a);this.recover=$(".js_psite-recover",a);this.recommendContent=$(".js_psite-recommend-content",
a);this.recommendControl=$(".js_psite-recommend-control",a);this.recommendCount=$(".js_psite-recommend-count",a);this.cms=$(".js_psite-cms",a);this.recommend=$(".js_psite-recommend",a);this.recover=$(".js_psite-recover",a);this.sug=$(".js_psite-sug",a);this.tipDel=$(".popup-site-tip-del",a);this.tipSave=$(".popup-site-tip-save",a);this.hintSug=new k($(".js_hint-sug",a));this.hintAdded=new k($(".js_hint-added",a));this.hintNoicon=new k($(".js_hint-noicon",a));this.hintSave=new k($(".js_hint-save",
a),6E3);this.noDataHint=$(".js_nodata-hint",a);this.blink=$(".popup-site-blink",a)},_initPopupPopup:function(){var a=this;a.confirmPopup.bind("confirmok",function(){e.emit("login.show","site");a._hidePsite()});a.confirmPopup.bind("confirmcancel",function(){a._showPopup()});a.confirmPopup.bind("confirmclose",function(){a._showPopup()});a.recoverPopup.bind("confirmok",function(){a.model.recover()});a.recoverPopup.bind("confirmcancel",function(){a._showPopup()});a.recoverPopup.bind("confirmclose",function(){a._showPopup()})},
_initPopupEvent:function(){var a=this;a.save.click(function(){a._hidePsite();e.emit("login.show","site");a.saveForeverHint.hide();return!1});a.saveForeverHint.click(function(){f.set(a.saveHintCookie,1);a.saveForeverHint.hide();f.get("stip2")||a.tipSave.show()});a.psite.on("mouseover",".item-added",function(){a.view.onAddedItemOver(this)});a.psite.on("mouseout",".item-added",function(){a.view.onAddedItemOut(this)});a.psite.on("click",".js_recommend",function(){a._showTip();if(!a._checkAdd())return!1;
var b=a.view.onItemClick(this);b&&a.model.add(b);return!1});a.psite.on("click",".js_add-tip-close",function(){$(this).parent(".popup-site-tip-add").hide();f.set("stip0",1,{expires:30});f.get("stip1")||$(".popup-site-tip-del",a.context).show()});a.psite.on("click",".js_del-tip-close",function(){$(this).parent(".popup-site-tip-del").hide();f.set("stip1",1,{expires:30})});a.psite.on("click",".js_save-tip-close",function(){a.tipSave.hide();f.set("stip2",1,{expires:30})});a.psite.on("click",".item-added",
function(){var b=a.view.onAddedClick(this);a.model.doDelete(b);a._trigger("dodelete",null,{id:b,url:this.parentNode.getAttribute("data-url")});return!1});a.recover.click(function(){a._hidePsite();a.recoverPopup.confirm("show");return!1});a.close.click(function(){var b=a.view.onSorted();a.view.clearError();a.view.update(a.model.sortData(b));g.hide();a._hidePsite();a._trigger("backclick");a.tipSave.hide();f.set("stip2",1,{expires:30});s();return!1});a.add.click(function(){if(a._checkAdd()){var b=a.view.onAddClick();
b&&a.model.add(b)}return!1});a.modify.click(function(){var b=a.view.onModifyClick();if(!b)return!1;var c=0;if(!a.login.get()&&(c=a.model.checkLimit(b.id),517==c))return a.confirmPopup.confirm("show"),a._hidePsite(),a.view.on517(),!1;if(0<c)return a.view.showError(c),!1;b&&a.model.modify(b);return!1});a.sites.on("click",".js_modify",function(){a.view.onItemModifyClick(this.parentNode);return!1});a.sites.on("click",".js_delete",function(){a._showTip(1);a.view.onItemDeleteClick(this.parentNode);var b=
this.parentNode.getAttribute("data-id");a.model.doDelete(b);a.model.checkIsShowSave()<a.config.showSaveMax&&a.saveForeverHint.hide();a._trigger("dodelete",null,{id:b,url:this.parentNode.getAttribute("data-url")});return!1})},_showTip:function(a){a?($(".popup-site-tip-del",i.context).hide(),f.set("stip1",1,{expires:30})):($(".popup-site-tip-add",i.context).hide(),f.set("stip0",1,{expires:30}),f.get("stip1")||$(".popup-site-tip-del",i.context).show())},_initPopup:function(){this._initPopupVariable();
this._initPopupPopup();this._initPopupEvent();this.siteDrag=new p(this.sites,this.dash);this.siteDrag.dragable();this.view.initSug();this.model.getCRdata()},_showPopup:function(){this.psite.show();g.show();this.recommend2Js.remove()},_checkAdd:function(){var a=0;this.login.get()||(a=this.model.checkLimit());if(0<a)return this.confirmPopup.confirm("show"),this._hidePsite(),!1;a=this.model.checkFull();return 0<a?(this.view.showError(a),!1):!0},_hidePsite:function(){this.view.clearHint();this.psite.hide()},
_bind:function(){var a=this;$(document).bind("getprof",function(b,c){if(c&&c.urls)switch(result=c.urls,result.code){case 200:c=result.data.sites;a.view.onImported(c);a.model.init(c);break;default:a._trigger("error",null,{code:result.code+"getrof"})}});6==v.ie&&(this.bd.on("mouseover",".js_item-add",function(){$(this).addClass("site-item-add-hover")}),this.bd.on("mouseout",".js_item-add",function(){$(this).removeClass("site-item-add-hover")}));a.bd.on("click",".js_item-add",function(){a._trigger("intoaddclick");
a._onManageClick()});a.bd.on("click",".js_no-data",function(){a._onManageClick();a._trigger("noneaddclick");return!1});a.manage.click(function(){a._onManageClick();return!1});a.bd.delegate(".js_text","mousedown",function(){var b={};b.url=this.href;b.id=this.parentNode.getAttribute("data-id");b.status=this.parentNode.getAttribute("data-status");a._trigger("textclick",null,b)})},_eventBind:function(){var a=this;e.on("firsted",function(b){a.view.onFirsted(b);n.set("urls","true")});e.on("recovered",function(b){a.view.onRecovered(b);
a._showPopup();n.set("urls","false");a._trigger("recovered")});e.on("modified",function(b){a.view.onModified(b);a._trigger("modify",null,b)});e.on("cred",function(b){a.view.onCred(b)});e.on("sorted",function(){a.model.sort(a.view.onSorted().join(","))});e.on("site.update",function(b){a.model.setData(b.data.sites);a.view.update(b.data.sites)});e.on("site.updatePopup",function(b){a._showPopup();a.model.setData(b.data.sites);a.view.updatePopup(b.data.sites)});e.on("getUser",function(b){b.userName?a.login.otherSignin(b):
a.retried<a.config.retry?(a.retried++,a._trigger("getusererror",null,a.retried+"_"+b.code),a.model.getUser()):(a.login.otherSignin({userName:""}),a.retried++,a._trigger("getusererror",null,a.retried+"_"+b.code))});e.on("operated",function(){n.set("urls","true")});e.on("addtwoed",function(b){a.view.onSecondAdd(b)});e.on("addsed",function(b){a.view.onManageClick(!0,!1);a.view.updatePopup(b);a.loading.hide();a.popContent.show()});e.on("addClickSynced",function(b){a.isAddingClickSync||(a._addSecondRecommend(),
a.isAddingClickSync=!1);a._trigger("addclicksync",null,b)});e.on("added",function(b){a.view.onAdded(b);a.model.checkIsShowSave()>=x.showSaveMax&&a.view.showSaveMessage();b.type?a._trigger(b.type,null,b):a._trigger("add",null,b)});e.on("refreshed",function(b){a.view.onRefreshed(b);b?a._trigger("showrefresh"):j.excute(a.siteBannerConfig)});e.on("imported",function(b){a.view.onImported(b)});e.on("error",function(b){a._trigger("error",null,{code:b.code+b.src,info:b.info});a.view.showError(b.code)});a.refreshButton.click(function(){a.view.onRefreshClick(a.model.getData());
a._trigger("refresh");return!1});e.on("login.signin",function(b){a.save.hide();a.saveForeverHint.hide();b.isInit||(a._trigger("login",null,{login:"login"}),a.recommend2Js.remove(),a.recommendData=[])})},_onManageClick:function(){this._hideHint();this.isManageClicked||(this.isManageClicked=!0,$("#popup-site").get(0).className="popup-site",this._initPopup());0<this.element.find(".site-item-recommend").length&&!this.isTask?(this.loading.show(),this.popContent.hide(),this._showPopup(),this.model.adds(this.view.getRecommends())):
(this.view.onManageClick(this.model.checkIsShowRecover(),this.model.checkIsShowSave()),this.view.updatePopup(this.model.getData()),this.loading.hide(),this.popContent.show(),this._showPopup(),this._trigger("manageclick"),0>=$("#popup-site-holder .popup-site-recommend-sidenone").length&&this._trigger("managerecommend"))},_ajust:function(){$("#site").bind("sitebackclick siterecovered siterefresh siteshowrefresh sitelogin",function(){c()})},_delete1:function(){$(function(){$("#site .js_text").each(function(a,
b){if(null!==window.location.search.match(/[?&]tn=([^&<>'"]+)/)&&"http://www.baidu.com/index.php?tn=10018801_hao"==b.getAttribute("href",2))return b.href="http://www.baidu.com/index.php?tn=10018802_hao",!1})})},_hideHint:function(){i.hint&&(i.hint.hide(),f.set("sitehint",1,{expires:30}))},_hint:function(){},_delete2:function(){for(var a={g_green:function(a){if(a.hasClass("g_reen"))return!1;a.addClass("g_green");return!1},g_red:function(a){if(a.hasClass("g_red"))return!1;a.addClass("g_red");return!1},
g_hot:function(a,b){if(a.hasClass("g_hot")||a.hasClass("g_tips-r"))return!1;if(70<a.width()||5==b%6)return!0;a.addClass("g_hot");a.append('<i class="g_icon"></i>');return!1},"g_tips-r":function(a,b,c){b=(new Date).getTime();if(c.stimer&&c.etimer){if(parseInt(c.stimer)<b&&parseInt(c.etimer)>b){if(a.hasClass("g_hot")||a.hasClass("g_tips-r"))return!1;if(60<a.width())return!0;c&&c.url2?(b=a.html(),c='<a monkey="tips" class="tips_link g_tips-r" href="'+(c.url2||"")+'">&nbsp;<i class="g_icon">'+c.tip+"</i></a>",
a.parent().append(c)):(a.addClass("g_tips-r"),b=a.html(),a.html("<b>"+b+"</b>"),a.append('<i class="g_icon">'+c.tip+"</i>"));return!1}}else{if(a.hasClass("g_hot")||a.hasClass("g_tips-r"))return!1;if(60<a.width())return!0;c&&c.url2?(a.html(),c='<a monkey="tips" class="tips_link g_tips-r" href="'+(c.url2||"")+'">&nbsp;<i class="g_icon">'+c.tip+"</i></a>",a.parent().append(c)):(a.addClass("g_tips-r"),b=a.html(),a.html("<b>"+b+"</b>"),a.append('<i class="g_icon">'+c.tip+"</i>"));return!1}}},b=h.get("sitestyle"),
c={},d,j=0;j<b.length;j++)d=b[j].url.replace(/(.*)\/$/,"$1"),c[d]=b[j];$("a.js_text",this.element).each(function(b){var d=this.href.replace(/(.*)\/$/,"$1");c[d]&&a[c[d].style]&&(a[c[d].style]($(this),b,c[d])||delete c[d])});$("#box-famoussite span>a").each(function(){var b=this.href.replace(/(.*)\/$/,"$1");c[b]&&a[c[b].style]&&(a[c[b].style]($(this),void 0,c[b]),delete c[b])})}});return r});
__d("widget.notice.notice","common.js.widget,common.js.config,common.js.home,common.js.format,common.js.refer,widget.popup.sethome".split(","),function(q,w,r,a){a("common.js.widget");a("common.js.config");var d=a("common.js.home"),e=a("common.js.format"),f=a("common.js.refer");a("widget.popup.sethome");$.widget("hao123.notice",{_create:function(){var a=this.options.data,n=[],l;!f.isTN()&&f.isIENotHome()?(l="b",this.element.on("click","a",function(){d.set(this,"http://www.hao123.com/?f=g",2);return!1})):
l="a";for(var c=0;c<a.length;c++)if(a[c].type==l){var k='<a href="#{url}" class="#{style}">#{title}#{icon}</a>';0<=a[c].style.indexOf("g_icon_hot")?a[c].icon='<i class="g_icon"></i>':0<=a[c].style.indexOf("g_icon_down")?(a[c].icon='<i class="g_icon"></i>',k='<a href="#{url}" class="#{style} gong-down">#{icon}#{title}</a>'):a[c].icon="";n.push(e(k,{url:a[c].url,style:a[c].style,title:a[c].title,icon:a[c].icon}))}this.element.html(n.join(""))}});return r});
__d("common.js.setHome","common.js.widget,common.js.browser,common.js.home,common.js.events,common.js.refer,widget.popup.sethome".split(","),function(q,w,r,a){function d(){if(e.isShell)return{helpText:l[e.shell[0]],openUrl:k+"#"+n[e.shell[0]]};if(!e.ie&&e.types[0]){if(e.chrome){if(e.is360Chrome)return{helpText:l["360"],openUrl:k+"#02"};if(e.is360se)return{helpText:l["360se"],openUrl:k+"#13"}}return{helpText:l[e.types[0]],openUrl:k+"#"+c[e.types[0]]}}return{helpText:"\u60a8\u7684",openUrl:k}}a("common.js.widget");
var e=a("common.js.browser"),f=a("common.js.home"),h=a("common.js.events");a("common.js.refer");a("widget.popup.sethome");var n={"360se":"02",maxthon:"03",se:"04",qqbrowser:"05",tencenttraveler:"06",theworld:"10",greenbrowser:"12",lbbrowser:"16",bidubrowser:"17"},l={msie:"IE",firefox:"Firefox",chrome:"chrome",opera:"opera",safari:"safari","360se":"360\u6781\u901f",360:"360",maxthon:"\u9068\u6e38",se:"\u641c\u72d7",qqbrowser:"qq",tencenttraveler:"TT",theworld:"\u4e16\u754c\u4e4b\u7a97",greenbrowser:"\u7eff\u8272",
lbbrowser:"\u730e\u8c79",bidubrowser:"\u767e\u5ea6"},c={firefox:"ff",chrome:"08",opera:"09",safari:"11",msie:"01"},k="http://www.hao123.com/redian/sheshouyef.htm";$.widget("hao123.setHome",{options:{url:"http://www.hao123.com",position:void 0,isShowMask:!0},_create:function(){var a=this;a.element.click(function(){a._onclick();return!1})},_onclick:function(){var a=this.options;if("http://www.hao123.com/?from=hao123"==this.options.url&&!h.emit("setHome.before"))return!1;if(e.ie)return void 0!=a.position&&
f.set(this.element,a.url,a.position),!1;if(e.isBaidu)return window.open(k+"#17"),!1;a=d();f.setNotie(a);return!1}});return r});
__d("widget.starbar.starbar","common.js.widget,common.js.format,common.js.profile,common.js.cookie,common.js.events,common.js.adjust,common.js.log".split(","),function(q,w,r,a){a("common.js.widget");var d=a("common.js.format"),e=a("common.js.profile"),f=a("common.js.cookie"),h=a("common.js.events"),n=a("common.js.adjust"),l=a("common.js.log"),d=a("common.js.format");$.widget("hao123.starbar",{options:{posMap:[-1,1,1,3,3,3,3,5,5,5,5,7,7,7,7,9,9,9,9],logtype:"starbar_tvtip",tpl:'<li class="tvtip"><div class="g_clr tipitem"><i class="pos#{pos}"></i><a data-pos="#{pos}" class="clz" hidefocus="true" title="\u4e0d\u518d\u63d0\u9192"></a><div id="tvtip_ph" class="tip"><span class="tipname">#{tipname}</span><span class="tipinfo">#{tipinfo}</span></div></div></li>'},
_create:function(){var a=this.element,d=this.options;this._norptip=!1;this._tiptype=0;var h=f.get("tvtip_notshow");e.get("navigate");this.notvtip=h;0>h||1<h||(this.$lis=$("li",a),a=d.data,this._bindEvents(),this._makeTip(a,0,a.pos))},_bindEvents:function(){var a=this,d=a.element,e=a.options.logtype;h.on("norptip",function(){$(".tvtip",d).length?a._showTip(a._tiptype):a._norptip=!0});d.bind("starbartipshow",function(j,h){var g=$(".tip-name",d),s=$(".tip-info",d),m=$(".clz",d),t=$(".tvtip",d),x=h.t;
l({type:e,v:0,f:x});g.live("click",function(){l({type:e,v:1,f:x})});s.live("click",function(){l({type:e,v:2,f:x})});m.live("click",function(d){d=$(d.target).data("pos");l({type:e,v:3,f:x});1==a.notvtip&&1<d||1<a.notvtip&&1==d?f.set("tvtip_notshow",-1,{expires:7}):f.set("tvtip_notshow",d,{expires:7});t.slideUp(function(){n.adjust()});return!1})})},_makeTip:function(a,e,f){var j=this.element,h=this.options,g,s,m,l,n,q;if(-1!=h.posMap[f]){if(0==e){g=s=a.title;m=a.url;l=n=a.title2;q=a.url2;var b=parseInt(+new Date/
1E3),p=a.show?parseInt(a.show):0,a=a.hide?parseInt(a.hide):b+86400;if(b<p||b>a)return}0<$(".tvtip",j).length||(j=s&&m?d('<a class="tip-name" href="#{url}" title="#{title}">#{text}</a>',{url:m,title:s,text:g}):"",l=n&&q?d('<a class="tip-info" href="#{url}" title="#{title}">#{text}</a>',{url:q,title:n,text:l}):"",l=d(h.tpl,{pos:f,tipname:j,tipinfo:l}),$(l).insertAfter(this.$lis[h.posMap[f]]).hide(),!0===this._norptip?this._showTip(e):this._tiptype=e)}},_showTip:function(a){var d=this,e=$(".tvtip",d.element),
a=a||0;e.attr("style","").slideDown(300,function(){n.adjust();d._trigger("tipshow",null,{t:a})})}});return r});
__d("widget.rptip.rptip","common.js.widget,widget.popup.login,common.js.adjust,widget.newindex_movie.newindex_video_adjust,common.js.browser,common.js.config,common.js.cookie,common.js.events,common.js.format,common.js.log,common.js.profile".split(","),function(q,w,r,a){a("common.js.widget");a("widget.popup.login");var d=a("common.js.adjust"),e=a("widget.newindex_movie.newindex_video_adjust"),f=d,w=a("common.js.browser"),q=a("common.js.config"),h=a("common.js.cookie"),n=a("common.js.events"),l=a("common.js.format"),
c=a("common.js.log"),k=a("common.js.profile"),v=!!$("body").css("-webkit-transition")||"25"<w.chrome,a=+new Date/36E5|0;$.widget("hao123.rptip",{options:{gameApi:"http://s0.hao123img.com/res/js/xyx_api.js?_="+a,rpApi:"/api/getinterest?c="+h.getCSRFId()+"&_="+ +new Date,rpDelete:"/api/delinterestbyid?c="+h.getCSRFId()+"&id=",vApi:"http://v.hao123.com/",vRp:"http://v.hao123.com/recommend/",videoApi:"http://video.baidu.com/playrecord/?callback=?&id=",videoScript:"http://list.video.baidu.com/pc_static/open/record/bdv-record-api.js?_="+
a,itemTpl:"<li class='rptip-item g-br3 #{cls}' #{attr} style='_border:0px;'><a class='clz js_clz' title='\u4e0d\u518d\u63d0\u793a' monkey='#{monkeyclose}'></a><a class='g-ib g_clr item' href='#{url}' title='#{title}' monkey='#{monkeylink}'><i class='g-ib s-sicon item-icon'></i>#{text}</a></li>",welcomeTpl:'<li class="rptip-item g-br3 rpwelcome" monkey="login" style="_border:0px;"><a class="rptip-login item" href="http://www.hao123.com/login.htm?gotourl='+q.get("userinfo").gotourl+'">\u767b\u5f55\u540e\uff0c\u4e3a\u60a8\u63a8\u8350\u7684\u5185\u5bb9\u66f4\u7cbe\u51c6\uff01</a></li>',
interval:5E3,timeout:3500,videoTimeout:3E3,logType:"rptip",isDataOnly:!1},_create:function(){var a=h.get("tvtip_notshow"),c=k.get("navigate");$.cacheScript=function(a,c){return $.ajax({url:a,success:c,dataType:"script",cache:!0})};this._timeoutErr="";this.hasVideoData=!1;this._bindEvents();if(0==a||1==c||2==c)this.hasVideoData=!0,this._getVideoData();this._getGameData();this._getRpData()},_bindEvents:function(){var a=this,l=a.element,g=a.options,k,m,t;f="tv"===g.type||"movie"===g.type?e:d;a.$rptip=
l;a.$list=$(".rptip-list",l);a.$login=$(".rptip-login",l);l.bind("rptipgametimeout",function(){}).bind("rptipvideotimeout",function(){}).bind("rptiprptimeout",function(){}).bind("rptipvideoready",function(c,d){var b=d.data;b.length?h.set("tvtip_notshow",0,{expires:7}):"0"===h.get("tvtip_notshow")&&h.remove("tvtip_notshow");k&&m?a._cookData(m,k,b):t=b}).bind("rptipgameready",function(c,d){var b=d.data;a.hasVideoData?t&&m?a._cookData(m,b,t):k=b:m?a._cookData(m,b,[]):k=b}).bind("rptiprpready",function(c,
d){a.hasVideoData?t&&k?a._cookData(d,k,t):m=d:k?a._cookData(d,k,[]):m=d}).bind("rptiptipshow",function(d,e){function b(){clearInterval(h);a.$list.removeClass("running");var b=$(".rpwelcome",l);v&&!a.hoverfix&&a.$list.children("li").eq(0).appendTo(a.$list);b.length&&b.eq(0).prev("li").length&&b.eq(0).appendTo(a.$list);a.hoverfix=!0;a.$rptip.addClass("rptip_hover")}function m(){a.$rptip.removeClass("rptip_hover");v&&a.$list.children("li").last().prependTo(a.$list);a.hoverfix=!1;i()}function i(){clearInterval(h);
1>=$("li",l).length||(h=setInterval(function(){a.$rptip.removeClass("rptip_trans0");v||a.$list.hide();a.$list.children("li").eq(0).appendTo(a.$list);a.$list.addClass("running");v||a.$list.fadeIn()},g.interval))}var h;a.$item=$(".rptip-item",l);a.$clz=$(".js_clz",l);a.hoverfix=!1;i();c({type:g.logType,v:e.logStr,e:e.errStr});a.$login.live("click",function(){n.emit("login.show");return!1});a.$rptip.hover(b,m);v&&($(window).focus(function(){i()}),$(window).blur(function(){clearInterval(h)}));a.$item.hover(function(){$(this).addClass("rptip-item_hover")},
function(){$(this).removeClass("rptip-item_hover")});a.$clz.hover(function(){$(this).addClass("clz_hover")},function(){$(this).removeClass("clz_hover")});a.$clz.live("click",function(){var c=$(this).parent("li"),d=0===c.next("li").length,e=c.data("v"),i=c.data("o"),h=c.data("g")+"";e?bdvRecordAPI.remove(e,function(){}):i?$.getJSON(g.rpDelete+i,null,function(){}):xyxRecordAPI.remove(h,function(){});c.remove();d?m():b();c=$("a.js_clz",l).length;2>c&&a.$rptip.removeClass("rptipdown");v&&(2===c?(d=a.$list.html(),
a.$list.html(d+g.welcomeTpl)):1===c&&(a.$rptip.removeClass("rptip3d"),$(".rpwelcome",l).remove()));c||(""===g.welcomeTpl?(a.$rptip.remove(),f.adjust()):(a.$list.html(g.welcomeTpl),$(".rpwelcome",l).append('<a class="clz js_welcomeclz"></a>'),$(".js_welcomeclz",l).click(function(){a.$rptip.remove();f.adjust()})));return!1})})},_cookData:function(a,d,e){function f(a,b){var c={},b=b||"id",d=a||[{}];return d=$.grep(d,function(a){var a=a[b],d=!c[a];c[a]=!0;return d})}var m=this.options,h=[],l=[],k=[],
b=m.type||"";a.tvtip=e.concat(a.tvtip||[]);"tv"===b?l=l.concat(a.tvtip||[]):"movie"===b?k=k.concat(a.filmrp||[]):(l=l.concat(a.tvtip||[],a.comictip||[],a.zongyitip||[]),k=k.concat(a.filmrp||[],d,a.tvrp||[]));l=f(l,"id");k=f(k,"pid");5<l.length&&k.length?(h=l.slice(0,5),h.splice(2,0,k[1])):h=h.concat(l,k).slice(0,6);h.length?(this._showTip(h),this._trigger("dataready",null,h)):(this._timeoutErr&&c({type:m.logType,e:this._timeoutErr}),n.done("norptip"))},_showTip:function(a){function c(a,b,d){if(b>=
2*a.length)return a;var b=b+2,d=d||"\u2026",e=a.slice(0,b).replace(/([^x00-xff])/g,"$1a").slice(0,b).replace(/([^x00-xff])a/g,"$1");return e===a?e:e.substr(0,b/2-1)+d}var d=this,e=d.options,m=a.length,h,k=[],n="";for(h=0;h<m;h++){var b=a[h],p,i;switch(b.type){case "tvplay":p=b.title+" "+("1"==b.finish?"\u5168":"\u66f4\u65b0\u81f3")+b.update+"\u96c6 \u770b\u5230"+b.watched.pop()+"\u96c6";i=("1"==b.finish?c(b.title,16)+" \u5168":c(b.title,12)+" \u66f4\u65b0\u81f3")+b.update+"\u96c6";b.cls="0";b.url=
e.vApi+"dianshi/"+b.id.substr(2)+".htm";b.attr='data-v="'+b.id+'"';break;case "101":p=b.title+" "+("1"==b.finish?"\u5168":"\u66f4\u65b0\u81f3")+b.update+"\u96c6";i=("1"==b.finish?c(b.title,16)+" \u5168":c(b.title,12)+" \u66f4\u65b0\u81f3")+b.update+"\u96c6";b.cls="1";b.url=e.vApi+"dianshi/"+b.pid+".htm";break;case "103":p=b.title+" "+("1"==b.finish?"\u5168":"\u66f4\u65b0")+b.episode+"\u671f";i=c(b.title,10)+" "+("1"==b.finish?"\u5168":"\u66f4\u65b0")+b.episode+"\u671f";b.cls="2";b.url=e.vApi+"zongyi/"+
b.pid+".htm";break;case "102":p=b.title+" "+("1"==b.finish?"\u5168":"\u66f4\u65b0\u81f3")+b.update+"\u96c6";i=("1"==b.finish?c(b.title,16)+" \u5168":c(b.title,12)+" \u66f4\u65b0\u81f3")+b.update+"\u96c6";b.cls="3";b.url=e.vApi+"dongman/"+b.pid+".htm";break;case "4":p='\u7c7b\u4f3c"'+b.title+'"\u7684\u7535\u89c6\u5267';i='\u7c7b\u4f3c"'+c(b.title,10)+'"\u7684\u7535\u89c6\u5267';b.cls="4";break;case "1":p='\u7c7b\u4f3c"'+b.title+'"\u7684\u7535\u5f71';i='\u7c7b\u4f3c"'+c(b.title,12)+'"\u7684\u7535\u5f71';
"m"===b.pid.charAt(0)&&(b.url=e.vRp+"movie/?id="+b.pid.match(/\d+/)[0]+"&fr=video");b.cls="5";break;default:p='\u66f4\u591a"'+b.title+'"\u7c7b\u5c0f\u6e38\u620f',i='\u66f4\u591a"'+c(b.title,12)+'"\u7c7b\u5c0f\u6e38\u620f',b.type="6",b.cls="6",b.gid=b.pid}n+=b.cls;k.push(l(e.itemTpl,{cls:"item"+h+" rptype"+b.cls,attr:(b.attr||"")+(b.oid?' data-o="'+b.oid+'"':"")+(b.gid?' data-g="'+b.gid+'"':""),monkeyclose:"close-t"+b.cls,monkeylink:"link-t"+b.cls,title:p,text:i,url:b.url}))}v&&(1<k.length&&(k.unshift(k.pop()),
d.$rptip.addClass("rptip3d")),2===k.length&&k.push(e.welcomeTpl));d.$list.html(k.join(""));1<m&&d.$rptip.addClass("rptipdown");d.$rptip.show();d.$rptip.slideDown(400,function(){f.adjust();d._trigger("tipshow",null,{logStr:n,errStr:d._timeoutErr})})},_getVideoData:function(){var a=this,c=a.options,d,e;d=!1;$.cacheScript(c.videoScript,function(){bdvRecordAPI.init({proxy:"/proxy.htm"});bdvRecordAPI.getVideos(function(c){d||(clearTimeout(e),c=c||[],c=$.grep(c,function(a){return"tvplay"===a.type}),c=c.reverse().slice(0,
6),a._trigger("videoready",null,{data:c}))})});e=setTimeout(function(){d=!0;a._timeoutErr+="1";a._trigger("videoready",null,{data:[]})},c.videoTimeout)},_getGameData:function(){var a=this,c=a.options,d,e;d=!1;$.cacheScript(c.gameApi,function(){xyxRecordAPI.init({proxy:"xyx_proxy.htm"});xyxRecordAPI.get(function(c){if(!d){clearTimeout(e);var c=c||{},f,h=[];for(f in c)h.push({pid:f,title:c[f],url:"http://xyx.hao123.com/pic_0_0_1_"+f+"_1.html"});h=h.slice(0,6);a._trigger("gameready",null,{data:h})}})});
e=setTimeout(function(){d=!0;a._timeoutErr+="2";a._trigger("gameready",null,{data:[]})},c.timeout)},_getRpData:function(){var a=this,c=a.options,d=c.rpApi,e="3",f,h;f=!1;$.getJSON(d,void 0,function(d){if(!f)if(e="4",d&&200==d.code&&d.data&&d.data.n&&d.data.n.length){var d=d.data.n,g=d.length,b=[],l,i={},k={tvtip:[],zongyitip:[],comictip:[],tvrp:[],filmrp:[]};for(l=0;l<g;l++){var n=d[l];n.type=n.ptype;n.oid=n.id;n.url=n.purl;n.title=n.ptitle;switch(n.type){case "101":b.push("TV"+n.pid);i[b[b.length-
1]]=n;break;case "103":b.push("T"+n.pid);i[b[b.length-1]]=n;break;case "102":b.push("C"+n.pid);i[b[b.length-1]]=n;break;case "4":k.tvrp.push(n);break;case "1":k.filmrp.push(n)}}b=b.join(",");""===b?f||(clearTimeout(h),a._trigger("rpready",null,k)):$.getJSON(c.videoApi+b,void 0,function(b){if(!f){clearTimeout(h);var c=b.length,d;for(d=0;d<c;d++){var e=b[d],g=i[e.id];e.oid=g.oid;e.type=g.type;e.pid=g.pid;switch(e.type){case "101":k.tvtip.push(e);break;case "103":k.zongyitip.push(e);break;case "102":k.comictip.push(e)}}a._trigger("rpready",
null,k)}})}else clearTimeout(h),a._trigger("rpready",null,{})});h=setTimeout(function(){f=!0;a._timeoutErr+=e;a._trigger("rpready",null,{})},c.timeout)}});return r});window.js_vFbJgeFmKj&&window.js_vFbJgeFmKj(!0);
