__d("widget.shortcut1.shortcut1","common.js.widget,common.js.browser,common.js.format,common.js.profile,common.js.cookie,common.js.config,common.js.animation,common.js.pageEvents".split(","),function(h,g,e,d){d("common.js.widget");var c=d("common.js.browser"),a=d("common.js.format"),f=d("common.js.profile"),m=d("common.js.cookie");d("common.js.config");var k=d("common.js.animation"),i=d("common.js.pageEvents"),b,z=!1,q=!1,n=70;6==c.ie&&(n=10);$.widget("hao123.shortcut1",{options:{tip:"",title:"",
tpl:'<a monkey="righttip" href="#{url}" target="_bank" class="tip"><img width=120 height=110 src="#{img}"/></a>',shoppingMap:["-71 10","-159 10","-247 10","-335 10"],lifeMap:["-71 -27","-159 -27","-247 -27","-335 -27"],relaxMap:["-72 -67","-160 -67","-248 -67"],gobottomMap:["-73 -136","-161 -136","-249 -136"],gotopMap:["-73 -103","-161 -103","-249 -103"],gameMap:["-71 -167","-159 -167","-247 -167"],videoMap:["-71 -199","-159 -199","-247 -199","-335 -199","-407 -199"]},_init:function(){b=this;b.hidden=
!1;b.shortcut=$("#shortcut-box");b.goshop=$("#shortcut-shop");b.golife=$("#shortcut-life");b.gorelax=$("#shortcut-relax");b.gogame=$("#shortcut-game");b.govideo=$("#shortcut-video");b.toptoggle=$("#shortcut-toptoggle");b.newindex=$("#shortcut-indexnew");b.goerwei=$("#shortcut-goerwei");b.goerweiclz=$("#shortcut-goerwei .clz");b.qrnotshow=m.has("qr_notshow");b.shortcutImage=$("#shortcut-image");i.on("viewport.deferchange",b._onscroll);i.on("navigate.tabchange",b._ontabchange);i.on("viewport.change",
b._onchange);b.toptoggle.click(b._ontoptoggle);b.goshop.click(b._ongoshop);b.gorelax.click(b._ongorelax);b.golife.click(b.ongolife);b.gogame.click(b._ongogame);b.govideo.click(b._ongovideo);b.attop=b._isAtTop();b.goerweiclz.click(b._hideQrCode);6!=c.ie&&b._showOrHideGoErwei();$(document).on("toppicturehijackclick",function(){b._ongoshop()});var a=f.get("navigate");b._setNavShow(a);b._showNav();b._initHoverAnimation();b._onscroll();b._triggerNewYear()},_triggerNewYear:function(){var b=window.location.search.match(/\?goto=([^<>&]+)/),
a=this,c="";b&&b[1]&&(c=b[1]||"",setTimeout(function(){switch(c){case "gw":a._ongoshop();break;case "yx":a._ongogame();break;case "sp":a._ongovideo();break;case "sh":a.ongolife();break;case "wl":a._ongorelax()}},1E3))},_initHoverAnimation:function(){var b=this,a=b.options,c=k().changePosition(b.goshop.get(0),a.shoppingMap).repeat(),d=k().changePosition(b.golife.get(0),a.lifeMap).repeat(),f=k().changePosition(b.gorelax.get(0),a.relaxMap).repeat(),i=k().changePosition(b.gogame.get(0),a.gameMap).repeat(),
m=k().changePosition(b.govideo.get(0),a.videoMap).repeat();b.gogame.hover(function(){i.start(200)},function(){i.pause();this.style.backgroundPosition="15px -167px"});b.govideo.hover(function(){m.start(200)},function(){m.pause();this.style.backgroundPosition="15px -199px"});b.goshop.hover(function(){c.start(200)},function(){c.pause();this.style.backgroundPosition="15px 10px"});b.golife.hover(function(){d.start(200)},function(){d.pause();this.style.backgroundPosition="15px -28px"});b.gorelax.hover(function(){f.start(200)},
function(){f.pause();this.style.backgroundPosition="15px -67px"});b.toptoggle.hover(function(){var a=this,c=b.options;b.toggleAnimate=k().enterFrame(function(d,f){var i=f/200|0,k=b.attop?c.gobottomMap:c.gotopMap;3<=i?d():(i=k[i].split(" "),a.style.backgroundPosition=i[0]+"px "+i[1]+"px")}).repeat().start(200)},function(){b.toggleAnimate.dispose();this.style.backgroundPosition=b.attop?"15px -136px":"15px -103px"})},_showTip:function(){var b=this.options,c=b.tip,d=b.title,f=b.url||"";if(""!=c&&!this.$tip&&
(this.$tip=$(a(b.tpl,{img:c,url:f})),this.$tip.appendTo(this.shortcut).animate({top:-110,height:110}),""==f))switch(d){case "gw":this.$tip.click(this._ongoshop);break;case "yx":this.$tip.click(this._ongogame);break;case "sp":this.$tip.click(this._ongovideo);break;case "sh":this.$tip.click(this.ongolife);break;case "wl":this.$tip.click(this._ongorelax);break;default:this.$tip.click(this._ongorelax)}},_showOrHideGoErwei:function(){if(b.qrnotshow||1230>$(window).width())b.goerwei.hide();else{var a=b.shortcutImage.attr("data-class");
a&&b.shortcutImage.addClass(a).attr("data-class","");b.goerwei.show()}},_hideQrCode:function(){m.set("qr_notshow",1);b.qrnotshow=!0;b.goerwei.hide()},_isAtTop:function(){return 1E3>$(window).scrollTop()?!0:!1},_showTopToggle:function(){b.attop=b._isAtTop();b.attop&&!z?b.toptoggle.fadeOut():b.attop?(b.toptoggle.removeClass("gotop gotop-hook").addClass("gobottom gobottom-hook").attr("title","\u8df3\u8f6c\u5230\u9875\u5e95").show().find(".text").text("\u5230\u5e95\u90e8"),b.toptoggle.get(0).style.backgroundPosition=
"15px -136px"):(b.toptoggle.removeClass("gobottom gobottom-hook").addClass("gotop gotop-hook").attr("title","\u8fd4\u56de\u9876\u90e8").show().find(".text").text("\u56de\u9876\u90e8"),b.toptoggle.get(0).style.backgroundPosition="15px -103px")},_showShortcut:function(){1200<$(window).width()?6==c.ie?b.shortcut.show():b.shortcut.fadeIn():6==c.ie?b.shortcut.hide():b.shortcut.fadeOut()},_showNav:function(){z?6==c.ie?(b.goshop.show(),b.newindex.show(),b._showTip(),b.golife.show(),b.gorelax.show(),b.gogame.show(),
b.govideo.show()):(b.toptoggle.fadeIn(),b.newindex.fadeIn(),b.gogame.fadeIn(function(){b._showTip()}),b.govideo.fadeIn(),b.goshop.fadeIn(),b.golife.fadeIn(),b.gorelax.fadeIn()):6==c.ie?(b.goshop.hide(),b.golife.hide(),b.gorelax.hide(),b.gogame.hide(),b.govideo.hide()):(b.goshop.fadeOut(),b.golife.fadeOut(),b.gorelax.fadeOut(),b.gogame.fadeOut(),b.govideo.fadeOut())},_setNavShow:function(){z=!0},_ontabchange:function(a){b._setNavShow(a);b._showNav();b._showTopToggle()},_onchange:function(){b._showOrHideGoErwei();
b._showTopToggle();b._showShortcut()},_windowGoTo:function(b,a){$("html,body").animate({scrollTop:b+"px"},function(){window.setTimeout(function(){a&&$(window).scrollTop(a.offset().top-n)},20)})},_ontoptoggle:function(){b.attop?b._windowGoTo(document.body.scrollHeight-$(window).height()):b._windowGoTo(0);return!1},_ongoshop:function(){var a=$("#hao123-gw11");b._windowGoTo(a.offset().top-n,a);return!1},ongolife:function(){var a=$("#hao123-lbspanel");b._windowGoTo(a.offset().top-n,a);return!1},_ongorelax:function(){var a=
$("#hao123-wuliao");b._windowGoTo(a.offset().top-n,a);return!1},_ongogame:function(){var a=0;q||(q=!0,a=94);b._windowGoTo($("#hao123-game").offset().top-n-a);return!1},_ongovideo:function(){b._windowGoTo($("#hao123-video").offset().top-n);return!1},_onscroll:function(){if(6==c.ie){var a=document.documentElement.scrollTop+document.documentElement.clientHeight-311,d=document.documentElement.scrollTop+document.documentElement.clientHeight-186;b.shortcut.stop(!0,!0);b.goerwei.stop(!0,!0);b.shortcut.animate({top:a},
200);b.goerwei.animate({top:d},200)}b._showTopToggle();b._showShortcut()},destroy:function(){$.Widget.prototype.destroy.call(this)}});return e});
__d("common.js.slider",["common.js.jquery"],function(h,g,e,d){var c=d("common.js.jquery");return function(a){function d(){if("fade"==q)0==j?e(r-1):e(j-1);else{if(l.is(":animated"))return!1;j--;0>j&&(j=r-1,l.css("left",-r*t));i();l.stop(!0,!0).animate({left:"+="+t},250,"linear",function(){j==r-1&&l.css("left",-j*t);b()})}}function m(){if("fade"==q)j+1==r?e(0):e(j+1);else{if(l.is(":animated"))return!1;j++;j==r&&(j=0);i();l.stop(!0,!0).animate({left:"-="+t},250,"linear",function(){0==j&&l.css("left",
0);b()})}}function k(a){var c;c=a-j;0!=c&&(j=a,i(),l.stop(!0,!0).animate({left:"-="+c*t},500,"linear",function(){b()}))}function i(){0!=x.length&&x.each(function(){c(this).removeClass(s);c(this).data("index")==j&&c(this).addClass(s)})}function b(){o&&(clearInterval(y),y=setInterval(function(){m()},D))}function e(a){a!=j&&(g.eq(j).removeClass(s).css({opacity:1}).stop().animate({opacity:0},800),g.eq(a).addClass(s).css({opacity:0}).stop().animate({opacity:1},800),j=a,i(),b())}var q=a.type||"l2r",n=a.trigger||
"click",s=a.selectCls||"selected",h=a.gridhoverCls||"grid_hover",o=a.auto||!1,p=a.context?c(a.slider,a.context):c(a.slider),l=c(a.slides,p),g=c(a.slides,p).children(),v=c(a.prev,p),w=c(a.next,p),x=c(a.points,p).children(),B=c(a.grid,p),A=g.eq(0),t=a.width||A.width();A.height();var r=g.length,j=0;"l2r"==q&&(A.clone().insertAfter(g.eq(r-1)),l.css({width:t*(r+1)+"px"}));(function(){v.click(function(){d();return!1});v.mousedown(function(b){b.preventDefault()});w.click(function(){m();return!1});w.mousedown(function(b){b.preventDefault()});
"click"==n?x.click(function(){"fade"==q?e(c(this).data("index")):k(c(this).data("index"))}):"hover"==n&&x.hover(function(){"fade"==q?e(c(this).data("index")):k(c(this).data("index"))},function(){});B.hover(function(){c(this).addClass(h)},function(){c(this).removeClass(h)});o&&B.hover(function(){clearInterval(y)},function(){b()});"fade"==q&&p.hover(function(){v.show();w.show()},function(){v.hide();w.hide()})})();if(o){var y,D=a.interval||1E4;b()}return{dispose:function(){clearInterval(y)}}}});
__d("widget.gw11slider.gouwu",["common.js.widget","common.js.slider"],function(h,g,e,d){d("common.js.widget");$.widget("hao123.gouwu",{options:{len:1,hoverCls:"grid_hover",selectCls:"selected",curCls:"current"},_create:function(){var c=this.element;this.$items=$(".item-hook",c);this.$activebg=$(".active_bg-hook",c);this.$grid=$(".grid-hook",c);this.$slides=$(".slides-hook",c);this.$point=$(".point",c)},_init:function(){var c=this.options,a,f,e=this.$grid.length;this.slider=[];for(f=0;f<e;f++)1<$(".screen",
this.$grid.eq(f)).length&&(a=d("common.js.slider"),this.slider[f]=a({slider:".grid-hook"+f,slides:".slides-hook",prev:".prev-hook",next:".next-hook",auto:1,interval:1E4}),this.$grid.eq(f).hover(function(){$(this).addClass(c.hoverCls)},function(){$(this).removeClass(c.hoverCls)}));this._bindEvent()},_bindEvent:function(){var c=this,a=c.options;c.$slides.hover(function(){c.$activebg.each(function(){$.contains(c.current,this)||$(this).show().stop().animate({opacity:0.6})})},function(){c.$activebg.each(function(){$(this).stop().animate({opacity:0},
function(){$(this).hide()})})});c.$point.click(function(){return!1});c.$point.mouseenter(function(){var d=$(this).data("index"),e=$("img",c.$grid.eq(d)),k=e.length;$(this).hasClass(a.selectCls)||(c.$point.removeClass(a.selectCls),$(this).addClass(a.selectCls),c.$grid.removeClass(a.curCls),c.$grid.eq(d).addClass(a.curCls));if(!e.eq(0).attr("src"))for(d=0;d<k;d++){var i=e[d];i.setAttribute("src",i.getAttribute("data-src"))}});c.$items.hover(function(){c.current=this;$(this).find(".active_bg-hook").stop().css({opacity:0}).hide()},
function(){$(this).find(".active_bg-hook").show().stop().animate({opacity:0.6})})},destroy:function(){if(this.slider){var c=this.slider.length,a;for(a=0;a<c;a++)this.slider[a].dispose()}$.Widget.prototype.destroy.call(this)}});return e});
__d("widget.coolsite.coolsite","common.js.widget,common.js.adjust,common.js.config,common.js.slider,common.js.cookie,common.js.log,common.js.format".split(","),function(h,g,e,d){d("common.js.widget");var c=d("common.js.adjust");d("common.js.config");var a=d("common.js.slider"),f=d("common.js.cookie"),m=d("common.js.log"),k=d("common.js.format");$.widget("hao123.coolsite",{options:{hoverCls:"g-bg1",url:"/api/youxidj"},_init:function(){this.$items=$(".coolsite-item",this.element);c.adjust();this._bindEvent();
this.options.recommend&&this._recommend()},_recommend:function(){var a=this;$.ajax({url:a.options.url,dataType:"json",data:{c:f.getCSRFId()},success:function(b){0==b.code&&a._render(b.data)}})},_render:function(c){if(c){m({type:"kzxyxtj"});var b=c[0],c=b.data,d=Math.ceil(c.length/8),b=b.no,f=$("<li class='recommend recommend-hook'><div class='viewport'><ul class='screen screen-hook'></ul></div><a monkey='gamebar-tab' href='#' class='arrow pre pre-hook'></a><a monkey='gamebar-tab' href='#' class='arrow next next-hook'></a><i class='up'></i></li>"),
e=$("li:nth-child("+b+")",this.element),g=$(".g_fr",e),b=$(".screen-hook",f),h,o,p=!1;f.insertAfter(e).slideDown(function(){$(this).css("overflow","visible")});h=$("<a monkey='gamebar-close' class='fold' href='#'>\u6536\u8d77</a>");g.html(h);g.click(function(){f.slideToggle(function(){$(this).css("overflow","visible");(p=!p)?h.text("\u5c55\u5f00"):h.text("\u6536\u8d77")});return!1});for(var l=0;l<d;l++)for(var e=$("<li monkey='gamebar-app' class='g-ib list'></li>").appendTo(b),u=0;8>u;u++)o=c[u+8*
l],g=$(k("<a class='item' href='#{url}' title='#{title}'><img src='#{img}' width='62' height='62'><span class='desc'>#{title}</span></a>",{url:o.url,img:o.imgurl,title:o.title})).appendTo(e),o.cls&&g.attr("cls",o.cls),7==u&&g.addClass("last");a({context:this.element,slider:".recommend-hook",slides:".screen-hook",prev:".pre-hook",next:".next-hook"})}},_bindEvent:function(){function a(){b.$items.each(function(){$(this).removeClass(c.hoverCls)})}var b=this,c=this.options;this.$items.hover(function(){a();
$(this).addClass(c.hoverCls)},function(){a()})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return e});
__d("widget.toppicture.toppicture",["common.js.widget","common.js.lazy"],function(h,g,e,d){d("common.js.widget");var c=d("common.js.lazy");$.widget("hao123.toppicture",{options:{selectCls:"selected",interval:1E4,lazy:!1},_create:function(){var a=this.element;this.$imglist=$(".js_content li",a);this.$hijacklinks=$(".js_content .hijackclick",a);this.$imgs=this.$imglist.find("img");this.$next=$(".js_next",a);this.$pre=$(".js_pre",a)},_init:function(){this.$imgs&&(this.options.lazy&&c.add(this.$imgs.eq(0)),
this.imgCount=this.$imglist.length,this.currentIndex=0,this.loadMore=this.options.loadMore||!1,this._bindEvent(),1<this.imgCount&&this._autoPlay())},_bindEvent:function(){var a=this;this.$imglist.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$next.click(function(){a._goNext();a._autoPlay();return!1});this.$pre.click(function(){a._goPre();a._autoPlay();return!1});this.$next.hover(function(){clearTimeout(a.hideTimer);
a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$pre.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$hijacklinks.click(function(){var c=$(this).index();a._trigger("hijackclick",null,{index:c});return!1})},_slideHide:function(){this.$next.hide();this.$pre.hide()},_slideShow:function(){this.$next.show();this.$pre.show()},_autoPlay:function(){var a=this,c=a.options;clearInterval(this.timer);
this.timer=setInterval(function(){a._goNext()},c.interval)},_goNext:function(){var a=this.currentIndex;++this.currentIndex==this.imgCount&&(this.currentIndex=0);this._display(a)},_goPre:function(){var a=this.currentIndex;0>--this.currentIndex&&(this.currentIndex=this.imgCount-1);this._display(a)},_display:function(a){var d=this.options;this.loadMore||(this.loadMore=!0,c.add(this.$imgs.not(":first")));this.$imglist.eq(a).removeClass(d.selectCls);this.$imglist.eq(this.currentIndex).addClass(d.selectCls);
this._animateShow(a)},_animateShow:function(a){this.$imglist.eq(a).css({opacity:1}).stop().animate({opacity:0},800);this.$imglist.eq(this.currentIndex).css({opacity:0,display:"block"}).stop().animate({opacity:1},800)},destroy:function(){clearInterval(this.timer);$.Widget.prototype.destroy.call(this)}});return e});
__d("common.js.microTemplate",[],function(){function h(e,d){var c=!/\W/.test(e)?g[e]=g[e]||h(document.getElementById(e).innerHTML):new Function("data","var p=[];p.push('"+e.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');return p.join('');");return d?c(d):c}var g={};return h});
__d("widget.toppicture2.toppicture2",["common.js.widget","common.js.lazy"],function(h,g,e,d){d("common.js.widget");var c=d("common.js.lazy");$.widget("hao123.toppicture2",{options:{selectCls:"selected",interval:1E4,lazy:!1},_create:function(){var a=this.element;this.$imgs=$(".js_content li",a);this.$next=$(".js_next",a);this.$pre=$(".js_pre",a)},_init:function(){this.$imgs&&(this._lazyLoad(this.$imgs.find("img")),this.imgCount=this.$imgs.length,this.currentIndex=0,this._bindEvent(),1<this.imgCount&&
this._autoPlay())},_lazyLoad:function(a){this.options.lazy&&(this.lazyKey=c.add(a))},_bindEvent:function(){var a=this;this.$imgs.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)});this.$next.click(function(){a._goNext();a._autoPlay();return!1});this.$pre.click(function(){a._goPre();a._autoPlay();return!1});this.$next.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)});this.$pre.hover(function(){clearTimeout(a.hideTimer);
a._slideShow()},function(){a.hideTimer=setTimeout(function(){},100)})},_slideHide:function(){this.$next.hide();this.$pre.hide()},_slideShow:function(){this.$next.show();this.$pre.show()},_autoPlay:function(){var a=this,c=a.options;clearInterval(this.timer);this.timer=setInterval(function(){a._goNext()},c.interval)},_goNext:function(){var a=this.currentIndex;++this.currentIndex==this.imgCount&&(this.currentIndex=0);this._display(a)},_goPre:function(){var a=this.currentIndex;0>--this.currentIndex&&
(this.currentIndex=this.imgCount-1);this._display(a)},_display:function(a){var c=this.options;this.$imgs.eq(a).removeClass(c.selectCls);this.$imgs.eq(this.currentIndex).addClass(c.selectCls);this._animateShow(a)},_animateShow:function(a){this.$imgs.eq(a).css({opacity:1}).stop().animate({opacity:0},800);this.$imgs.eq(this.currentIndex).css({opacity:0,display:"block"}).stop().animate({opacity:1},800)},destroy:function(){this.options.lazy&&c.remove(this.lazyKey);clearInterval(this.timer);$.Widget.prototype.destroy.call(this)}});
return e});
__d("widget.lbssearch.lbssearch",["common.js.jquery","common.js.format","common.js.log"],function(h,g,e,d){var c=d("common.js.jquery"),a=d("common.js.format"),f=d("common.js.log"),m="s&wd=#{word}&c=#{code}";return function(d){function e(b){o.val(a(m,{word:h.val(),code:C.val()}));n.val(b)}var d=c(d),b=c("form",d),g=c(".placeholder",d),h=c(".lbssearch-input",d),n=c(".sdetail",d),s=c(".lbssearch-btn",d),C=c(".code",d),o=c(".s",d);h.focus(function(){g.hide()});h.blur(function(){""!=h.val()?g.hide():g.show()});
h.on("keydown",function(a){13==a.keyCode&&(e("search"),b.submit(),f({type:"bendi"}))});s.click(function(){e("box");b.submit();f({type:"bendi"})})}});
__d("widget.guesslike.guesslike",["common.js.widget","common.js.config","common.js.profile","common.js.events"],function(h,g,e,d){d("common.js.widget");var c=d("common.js.config"),a=d("common.js.profile"),f=d("common.js.events");$.widget("hao123.guesslike",{_create:function(){var c=this;c._showGuess(a.get("navigate"));f.on("navigate.inited",function(a){c._showGuess(a)})},_showGuess:function(a){var c=this.element.parent();this._needShow(a)?c.show():c.hide()},_needShow:function(a){return"hao123-indexguess"==
c.get("pageId")||0==a},destroy:function(){$.Widget.prototype.destroy.call(this)}});return e});window.js_EAoJaWGqbb&&window.js_EAoJaWGqbb(!0);
