__d("widget.rptipnew.rptipnew","common.js.widget,widget.popup.login,common.js.adjust,widget.newindex_movie.newindex_video_adjust,common.js.browser,common.js.config,common.js.cookie,common.js.events,common.js.format,common.js.log,common.js.profile".split(","),function(n,q,o,f){f("common.js.widget");f("widget.popup.login");f("common.js.adjust");f("widget.newindex_movie.newindex_video_adjust");f("common.js.browser");f("common.js.config");var k=f("common.js.cookie");f("common.js.events");var p=f("common.js.format");
f("common.js.log");f("common.js.profile");n=+new Date/36E5|0;$.widget("hao123.rptipnew",{options:{videoApi:"http://video.baidu.com/playrecord/?callback=?&id=",videoScript:"http://list.video.baidu.com/pc_static/open/record/bdv-record-api.js?_="+n,gameApi:"http://s0.hao123img.com/res/js/xyx_api.js?_="+n,rpApi:"/api/getinterest?c="+k.getCSRFId()+"&_="+ +new Date,vApi:"http://v.hao123.com/",vRp:"http://v.hao123.com/recommend/",itemTpl:"<li><a title='#{title}' href='#{url}'><em>[#{type}]</em>#{text}</a></li>",
interval:5E3,timeout:3500,videoTimeout:3E3,logType:"rptip"},_create:function(){var b=this.element;this.list=$(".rptipnew-list",b);this.title=$("h3",b);this.body=$(".rptipnew-body",b);this.hint=$(".rptipnew-hint",b);$.cacheScript=function(b,g){return $.ajax({url:b,success:g,dataType:"script",cache:!0})};this._timeoutErr="";this.hasVideoData=!0;this._getVideoData();this._bindEvents();this._getGameData();this._getRpData()},_bindEvents:function(){var b=this,h=b.element,g,i,c,d=null;b.title.hover(function(){b.title.addClass("selected");
3<b.list.children().length?b.hint.hide():b.hint.show();b.body.stop(!0,!0);var a=b.body.show().height();b.body.css({width:0,left:220,opacity:0,height:0}).animate({width:246,left:0,opacity:1,height:a},600)},function(){d=window.setTimeout(function(){b.body.hide();b.title.removeClass("selected")},100)});b.body.hover(function(){window.clearTimeout(d)},function(){b.body.hide();b.title.removeClass("selected")});h.bind("rptipnewgametimeout",function(){}).bind("rptipnewvideotimeout",function(){}).bind("rptipnewrptimeout",
function(){}).bind("rptipnewvideoready",function(a,d){var e=d.data;e.length?k.set("tvtip_notshow",0,{expires:7}):"0"===k.get("tvtip_notshow")&&k.remove("tvtip_notshow");g&&i?b._cookData(i,g,e):c=e}).bind("rptipnewgameready",function(a,d){var e=d.data;b.hasVideoData?c&&i?b._cookData(i,e,c):g=e:i?b._cookData(i,e,[]):g=e}).bind("rptipnewrpready",function(a,d){b.hasVideoData?c&&g?b._cookData(d,g,c):i=d:g?b._cookData(d,g,[]):i=d})},_getVideoData:function(){var b=this,h=b.options,g,i;g=!1;$.cacheScript(h.videoScript,
function(){bdvRecordAPI.init({proxy:"/proxy.htm"});bdvRecordAPI.getVideos(function(c){g||(clearTimeout(i),c=c||[],c=$.grep(c,function(b){return"tvplay"===b.type}),c=c.reverse().slice(0,6),b._trigger("videoready",null,{data:c}))})});i=setTimeout(function(){g=!0;b._timeoutErr+="1";b._trigger("videoready",null,{data:[]})},h.videoTimeout)},_cookData:function(b,h,g){function i(a,b){var c={},b=b||"id",d=a||[{}];return d=$.grep(d,function(a){var a=a[b],d=!c[a];c[a]=!0;return d})}var c=[],d=[],a=[];b.tvtip=
g.concat(b.tvtip||[]);d=d.concat(b.tvtip||[],b.comictip||[],b.zongyitip||[]);a=a.concat(b.filmrp||[],h,b.tvrp||[]);d=i(d,"id");a=i(a,"pid");5<d.length&&a.length?(c=d.slice(0,5),c.splice(2,0,a[1])):c=c.concat(d,a).slice(0,6);c.length&&this._showTip(c)},_showTip:function(b){function h(a,b,c){if(b>=2*a.length)return a;var b=b+2,c=c||"\u2026",d=a.slice(0,b).replace(/([^x00-xff])/g,"$1a").slice(0,b).replace(/([^x00-xff])a/g,"$1");return d===a?d:d.substr(0,b/2-1)+c}var g=this.options,i=b.length,c,d=[];
0<i?this.element.show():this.element.hide();for(c=0;c<i;c++){var a=b[c],f,e,l;switch(a.type){case "tvplay":f=a.title+" "+("1"==a.finish?"\u5168":"\u66f4\u65b0\u81f3")+a.update+"\u96c6 \u770b\u5230"+a.watched.pop()+"\u96c6";e=("1"==a.finish?h(a.title,16)+" \u5168":h(a.title,12)+" \u66f4\u65b0\u81f3")+a.update+"\u96c6";a.cls="0";a.url=g.vApi+"dianshi/"+a.id.substr(2)+".htm";a.attr='data-v="'+a.id+'"';l="\u7535\u89c6\u5267";break;case "101":f=a.title+" "+("1"==a.finish?"\u5168":"\u66f4\u65b0\u81f3")+
a.update+"\u96c6";e=("1"==a.finish?h(a.title,16)+" \u5168":h(a.title,12)+" \u66f4\u65b0\u81f3")+a.update+"\u96c6";a.cls="1";a.url=g.vApi+"dianshi/"+a.pid+".htm";l="\u7535\u89c6\u5267";break;case "103":f=a.title+" "+("1"==a.finish?"\u5168":"\u66f4\u65b0")+a.episode+"\u671f";e=h(a.title,10)+" "+("1"==a.finish?"\u5168":"\u66f4\u65b0")+a.episode+"\u671f";a.cls="2";a.url=g.vApi+"zongyi/"+a.pid+".htm";l="\u7efc\u827a";break;case "102":f=a.title+" "+("1"==a.finish?"\u5168":"\u66f4\u65b0\u81f3")+a.update+
"\u96c6";e=("1"==a.finish?h(a.title,16)+" \u5168":h(a.title,12)+" \u66f4\u65b0\u81f3")+a.update+"\u96c6";a.cls="3";a.url=g.vApi+"dongman/"+a.pid+".htm";l="\u52a8\u6f2b";break;case "4":f='\u7c7b\u4f3c"'+a.title+'"\u7684\u7535\u89c6\u5267';e='\u7c7b\u4f3c"'+h(a.title,10)+'"\u7684\u7535\u89c6\u5267';a.cls="4";l="\u7535\u89c6\u5267";break;case "1":f='\u7c7b\u4f3c"'+a.title+'"\u7684\u7535\u5f71';e='\u7c7b\u4f3c"'+h(a.title,12)+'"\u7684\u7535\u5f71';"m"===a.pid.charAt(0)&&(a.url=g.vRp+"dianying/?id="+a.pid.substr(1));
a.cls="5";l="\u7535\u5f71";break;default:f='\u66f4\u591a"'+a.title+'"\u7c7b\u5c0f\u6e38\u620f',e='\u66f4\u591a"'+h(a.title,12)+'"\u7c7b\u5c0f\u6e38\u620f',a.type="6",a.cls="6",a.gid=a.pid,l="\u5c0f\u6e38\u620f"}d.push(p(g.itemTpl,{title:f,text:e,url:a.url,type:l}))}this.list.html(d.join(""))},_getGameData:function(){var b=this,h=b.options,g,i;g=!1;$.cacheScript(h.gameApi,function(){xyxRecordAPI.init({proxy:"xyx_proxy.htm"});xyxRecordAPI.get(function(c){if(!g){clearTimeout(i);var c=c||{},d,a=[];for(d in c)a.push({pid:d,
title:c[d],url:"http://xyx.hao123.com/pic_0_0_1_"+d+"_1.html"});a=a.slice(0,6);b._trigger("gameready",null,{data:a})}})});i=setTimeout(function(){g=!0;b._timeoutErr+="2";b._trigger("gameready",null,{data:[]})},h.timeout)},_getRpData:function(){var b=this,h=b.options,g=h.rpApi,i="3",c,d;c=!1;$.getJSON(g,void 0,function(a){if(!c)if(i="4",a&&200==a.code&&a.data&&a.data.n&&a.data.n.length){var a=a.data.n,g=a.length,e=[],f,k={},m={tvtip:[],zongyitip:[],comictip:[],tvrp:[],filmrp:[]};for(f=0;f<g;f++){var j=
a[f];j.type=j.ptype;j.oid=j.id;j.url=j.purl;j.title=j.ptitle;switch(j.type){case "101":e.push("TV"+j.pid);k[e[e.length-1]]=j;break;case "103":e.push("T"+j.pid);k[e[e.length-1]]=j;break;case "102":e.push("C"+j.pid);k[e[e.length-1]]=j;break;case "4":m.tvrp.push(j);break;case "1":m.filmrp.push(j)}}e=e.join(",");""===e?c||(clearTimeout(d),b._trigger("rpready",null,m)):$.getJSON(h.videoApi+e,void 0,function(a){if(!c){clearTimeout(d);var g=a.length,e;for(e=0;e<g;e++){var f=a[e],h=k[f.id];f.oid=h.oid;f.type=
h.type;f.pid=h.pid;switch(f.type){case "101":m.tvtip.push(f);break;case "103":m.zongyitip.push(f);break;case "102":m.comictip.push(f)}}b._trigger("rpready",null,m)}})}else clearTimeout(d),b._trigger("rpready",null,{})});d=setTimeout(function(){c=!0;b._timeoutErr+=i;b._trigger("rpready",null,{})},h.timeout)}});return o});window.js_veJPFBEqpT&&window.js_veJPFBEqpT(!0);
