__d("widget.userlinks.userlinks","common.js.widget,widget.placeHolder.placeHolder,widget.suggest.suggest,common.js.events,common.js.cookie,common.js.format,common.js.profile,common.js.browser,widget.suggest.nssug".split(","),function(m,o,k,d,i,c){d("common.js.widget");d("widget.placeHolder.placeHolder");d("widget.suggest.suggest");d("common.js.events");var g=d("common.js.cookie"),l=d("common.js.format"),j=d("common.js.profile"),r=d("common.js.browser"),m=d("widget.suggest.nssug"),s=2,p=200,n=201,
t=500,u=501,v=503;$.widget("hao123.userlinks",{options:{linkIconTpl:"<a class=link link-hook' href='#{url|e}'><img src='http://s0.hao123img.com/res/cywzicon/#{icon|e}' width='124' height='74'/><i class='logo-delete' data-id='#{id|e}' data-url='#{url|e}' data-name='#{name|e}' title='\u5220\u9664\u8be5\u7f51\u5740'></i></a>",linkTextTpl:"<a class=link link-hook' href='#{url|e}'><span class='logo-text'>#{name|e}</span><i class='logo-delete' data-id='#{id|e}' data-url='#{url|e}' data-name='#{name|e}' title='\u5220\u9664\u8be5\u7f51\u5740'></i></a>",
blankTpl:"<span class='blank blank-hook' data-id='#{id|e}' style='display:none'></span>",maskTpl:"<div class='search-mask'></div>",searchTpl:"<div class='search-content'><div class='link-name search-area link-name-hook'><span class='search-label'>\u7f51\u5740\u540d\u79f0\uff1a</span><span class='search-textbox name-wrapper-hook'><input class='search-input name-hook'/></span><span class='search-error nameerr-hook'></span></div><div class='link-url search-area link-url-hook'><span class='search-label'>\u7f51\u5740\u94fe\u63a5\uff1a</span><span class='search-textbox url-wrapper-hook'><input class='search-input url-hook'/></span><span class='search-error urlerr-hook'></span></div><a href='#' class='search-add add-hook'></a><a href='#' class='search-close close-hook'></a></div>",
tipTpl:"<div class='tip' style='top:#{top}px;left:#{left}px'><a title='\u5173\u95ed' class='tip-close close-hook'></a></div>",modifyUrl:"/url/newmodify",errorCls:"error",shadowCls:"shadow"},_create:function(){var b=this.element;this.$items=$(".item-hook",b);this.$links=$(".link-hook",b);this.$blanks=$(".blank-hook",b);this.blankCount=this.$blanks.length},_init:function(){this._show([[0],[1,6],[2,7,12],[3,8,13],[4,9,14],[5,10,15],[11,16],[17]]);this._addLinksHandler(this.$links);this._addBlanksHandler(this.$blanks);
7>=r.ie&&this.$items.hover(function(){$(this).css({"z-index":10})},function(){$(this).css({"z-index":0})})},destroy:function(){$.Widget.prototype.destroy.call(this)},_show:function(b){function a(){var e=b[f++];$.each(e,function(a,b){var e=h.$items.eq(b);e&&h._doAnimation(e)});f<c&&setTimeout(a,160)}var h=this,c=b.length,f=0;setTimeout(a,200)},_tip:function(b,a){function h(){clearTimeout(e);f&&f.animate({height:0,top:a+97},function(){f.hide();f=null})}var c=this.options,f,e;"1"!=g.get("tu")&&(g.set("tu",
"1"),f=$(l(c.tipTpl,{top:a+97,left:b})),f.appendTo(this.element).animate({height:97,top:a}),c=$(".close-hook",f),c.on("click",function(){h()}),e=setTimeout(function(){h()},5E3))},_doAnimation:function(b){b.animate({opacity:0.7},500,function(){b.animate({opacity:1},500,function(){c(["common.js.widget","common.js.effect"],function(){if(b.index()+1==b.parent().find("li").length){var a=b.parent().find(".two");a.show().animate({top:["0","easeOutBounce"]},1600);a.delay(800).slideUp(600,function(){a.parent().remove()})}})})})},
_addBlanksHandler:function(b){var a=this;b.on("click",function(){a.$currentMask&&a._removeMask(a.$currentMask);a._showMask($(this))})},_addLinksHandler:function(b){var a=this,h=b.find("i");b.hover(function(){a._showDeleteBtn($(this))},function(){a._hideDeleteBtn($(this))});a._addLogoDeleteHandler(h)},_showDeleteBtn:function(b){b.find("i").stop().animate({width:25,height:25})},_hideDeleteBtn:function(b){b.find("i").stop().animate({width:0,height:0})},_addLogoDeleteHandler:function(b){var a=this,h=
a.options;b.on("click",function(){var b=$(this).data("id"),c=$(this).data("name"),e=$(this).data("url"),d=this;$.ajax({type:"POST",url:h.modifyUrl,data:{id:b,name:c,url:e,status:3,c:g.getCSRFId(),key:(new Date).getTime()},dataType:"json",success:function(b){var e=$(d).parent(),h=e.parent(),c=b.code;if(c==p||c==n)b=b.data,a._removeLink(e),a._createBlank(h,{id:b.id}),c==n&&a._refreshIDMap(b.map);j.set("cywz",1)}});return!1})},_showMask:function(b){var a=this,c=this.options,q=b.parent(),f=q.data("index"),
e=f%6,f=Math.floor(f/6),d,g;d=125*(2>e?0:4<e?3:e-1);e=125*e+62;g=74*f+37;f=$(c.maskTpl);f.appendTo(a.element);f.startLeft=e;f.startTop=g;f.css({left:e,top:g}).animate({left:d,top:0,width:375,height:225},function(){a.$content||(a.$content=$(c.searchTpl),a.$content.appendTo(a.element),a.$close=$(".close-hook",a.$content),a.$add=$(".add-hook",a.$content),a.$namewrapper=$(".name-wrapper-hook",a.$content),a.$name=$(".name-hook",a.$content),a.$url=$(".url-hook",a.$content),a.$urlwrapper=$(".url-wrapper-hook",
a.$content),a.$nameerr=$(".nameerr-hook",a.$content),a.$urlerr=$(".urlerr-hook",a.$content),a._addSearchHandler());a.$content.css({left:d,top:0}).show()});a.$currentMask=f;a.$currentBlank=b;a.$currentItem=q},_addSearchHandler:function(){function b(){var b=a.$currentBlank.data("id"),f=$.trim(a.$name.placeHolder("val")),e=$.trim(a.$url.placeHolder("val"));if(""==f)return a.$nameerr.show().text("\u8bf7\u8f93\u5165\u7f51\u7ad9\u540d\u79f0"),a.$namewrapper.addClass(c.errorCls),!1;if(""==e)return a.$urlerr.show().text("\u8bf7\u8f93\u5165\u7f51\u7ad9\u5730\u5740"),
a.$urlwrapper.addClass(c.errorCls),!1;e=a._fixUrl(e);$.ajax({type:"POST",url:c.modifyUrl,data:{id:b,name:f,url:e,status:s,c:g.getCSRFId(),key:(new Date).getTime()},dataType:"json",success:function(b){var d=b.code;d==p||d==n?(b=b.data,a._removeMask(a.$currentMask),a._removeBlank(a.$currentBlank),a._createLink(a.$currentItem,{id:b.id,name:f,url:e,icon:b.icon}),d==n&&a._refreshIDMap(b.map)):d==u?(a.$urlerr.show().text("\u8be5\u7f51\u5740\u5df2\u5b58\u5728"),a.$urlwrapper.addClass(c.errorCls)):d==v?(a.$nameerr.show().text("\u4f20\u5165id\u9519\u8bef"),
a.$namewrapper.addClass(c.errorCls)):d==t&&(a.$nameerr.show().text("\u53c2\u6570\u9519\u8bef"),a.$namewrapper.addClass(c.errorCls));j.set("cywz",1)}})}var a=this,c=a.options;a.$name.placeHolder({defaultVal:"\u5982\uff1a\u767e\u5ea6",defaultCls:"input-default"}).on("placeholderfocus",function(){a.$nameerr.hide();a.$namewrapper.removeClass(c.errorCls)});a.$name.suggest({classes:"search-suggest",hoverClass:"suggest-hover"}).suggest("handler",a._nssug).on("suggestinit",function(b,c){$(".link-name-hook",
a.$content).append(c);return!1}).on("suggestinput",function(){if(""!=$.trim(a.$url.placeHolder("val")))return!1}).on("suggestchange",function(b,c){var e=c.data;a.$name.placeHolder("val",e[0]);a.$url.placeHolder("val",e[1]);return!1}).on("suggestsubmit",function(){b()});a.$url.placeHolder({defaultVal:"\u5982\uff1awww.baidu.com",defaultCls:"input-default"}).on("placeholderfocus",function(){a.$urlerr.hide();a.$urlwrapper.removeClass(c.errorCls)});a.$url.suggest({classes:"search-suggest",hoverClass:"suggest-hover"}).suggest("handler",
a._nssug).on("suggestinit",function(b,c){$(".link-url-hook",a.$content).append(c);return!1}).on("suggestinput",function(){if(""!=$.trim(a.$name.placeHolder("val")))return!1}).on("suggestchange",function(b,c){var e=c.data;a.$name.placeHolder("val",e[0]);a.$url.placeHolder("val",e[1]);return!1}).on("suggestsubmit",function(){b()});a.$close.on("click",function(){a._removeMask(a.$currentMask);return!1});a.$add.on("click",function(){b();return!1})},_removeMask:function(b){this._clearContent();this.$content.hide();
b.animate({left:b.startLeft,top:b.startTop,width:0,height:0},function(){b.remove()});this.$currentMask=null},_createLink:function(b,a){var c=this.options,d=a.name,f=a.icon,e=b.data("index"),g=e%6,e=Math.floor(e/6);a.name=this._subByte(a.name,8);c=""!=f?$(l(c.linkIconTpl,a)):$(l(c.linkTextTpl,a));c.appendTo(b).attr("title",d);this._addLinksHandler(c);0==--this.blankCount&&this._tip(125*(g-1),75*(e-1))},_removeLink:function(b){b.fadeOut(function(){b.remove()})},_createBlank:function(b,a){var c;c=$(l(this.options.blankTpl,
a));c.appendTo(b).fadeIn();this._addBlanksHandler(c);++this.blankCount},_removeBlank:function(b){b.remove()},_fixUrl:function(b){var a=/^\s*(https?|ftp):\/\//i;b&&!a.test(b)&&(b="http://"+b);return b},_refreshIDMap:function(b){var a;this.$items.each(function(c){a=$(this).find("i");0==a.length&&(a=$(this).find("span"));a.data("id",b[c+1])})},_clearContent:function(){var b=this.options;this.$name.placeHolder("setDefaultValue");this.$url.placeHolder("setDefaultValue");this.$namewrapper.removeClass(b.errorCls);
this.$urlwrapper.removeClass(b.errorCls);this.$nameerr.hide();this.$urlerr.hide()},_shuffle:function(b){for(var a,c,d=b.length;d;a=parseInt(Math.random()*d),c=b[--d],b[d]=b[a],b[a]=c);return b},_getByteLength:function(b){return(""+b).replace(/[^\x00-\xff]/g,"ci").length},_subByte:function(b,a,c){b=""+b;c=c||"";if(0>a||this._getByteLength(b)<=a)return b+c;b=b.substr(0,a).replace(/([^\x00-\xff])/g,"$1 ").substr(0,a).replace(/[^\x00-\xff]$/,"").replace(/([^\x00-\xff]) /g,"$1");return b+c},_nssug:m("superpage",
{sc:"hao123"},function(b){var a=b.s,c={},b=b.q;if(0==a.length)this.hide();else{this.clear();for(var d=0,f=0;d<a.length&&3>f;d++){var e=$.parseJSON(a[d].split("0{#S+_}")[1]);e&&(e[1]=e[1]||"",e[4]&&(e[4]=e[4]||"",c[e[4]]||(f++,c[e[4]]=!0,this.add(e[4],l('<span class="suggest-name">#{name}</span><span class="suggest-url">#{url}</span>',{name:e[4].replace(b,"<strong>"+b+"</strong>"),url:e[1].replace(b,"<strong>"+b+"</strong>")}),[e[4],e[1]]))))}this.show()}})});return k});
__d("widget.newsite.newsite",["common.js.widget","common.js.profile"],function(m,o,k,d){d("common.js.widget");var i=d("common.js.profile");$.widget("hao123.newsite",{options:{upCls:"rollup",downCls:"rolldown",hrefs:["/api/ajax/?menu=newindex&ua=0","/api/ajax/?menu=newindex&ua=1"]},_create:function(){var c=this.element;this.$slider=$(".slider-hook",c);this.$wrapper=$(".wrapper-hook",c);this.$container=c.parent().parent();this.state=i.get("ns");this._bindEvent()},_init:function(){this._fixTabs(this.state)},
_bindEvent:function(){var c=this,d=c.options;c.$slider.on("click",function(){if(!c.$container.is(":animated"))return 0==c.state?(c.$wrapper.show(),$("#userarea").find(".list-hook").show(),c.$container.stop().animate({height:400},function(){c.$slider.removeClass(d.downCls);c.$slider.addClass(d.upCls);c.$slider.attr({title:"\u6536\u8d77\u7f51\u5740"})}),i.set("ns",1),c.state=1,c._fixTabs(1)):(c.$container.stop().animate({height:240},function(){c.$slider.removeClass(d.upCls);c.$slider.addClass(d.downCls);
c.$slider.attr({title:"\u5c55\u5f00\u7f51\u5740"});c.$wrapper.hide();$("#userarea").find(".list-hook").hide()}),i.set("ns",0),c.state=0,c._fixTabs(0)),!1})},_fixTabs:function(c){var d=this.options;$("#userarea").find(".remind-hook").find("a").each(function(i,j){$.each(d.hrefs,function(d,g){-1<$(j).attr("href").indexOf(g)&&$(j).attr({href:g+"&ns="+c})})})},setDefaultValue:function(){var c=this.options;this.element.addClass(c.defaultCls).val(c.defaultVal);this.state=STATE_UNINITIED},_clearValue:function(){this.element.removeClass(this.options.defaultCls).val("")},
val:function(c){var d=this.options;if(0<arguments.length)this.element.removeClass(d.defaultCls).val(c),this.state=STATE_INITIED;else return this.state==STATE_UNINITIED?"":this.element.val()},destroy:function(){$.Widget.prototype.destroy.call(this)}});return k});
__d("widget.newindex_remind2look.remind",["common.js.widget","common.js.profile"],function(m,o,k,d){d("common.js.widget");var i=d("common.js.profile");$.widget("hao123.remind",{options:{hrefs:["/api/ajax/?menu=newindex&ua=0","/api/ajax/?menu=newindex&ua=1"]},_create:function(){this.$menus=$("a",this.element);this.state=i.get("ns");this._bindEvent()},_init:function(){this._fixTabs(this.state)},_fixTabs:function(c){var d=this.options;this.$menus.each(function(i,j){$.each(d.hrefs,function(d,g){-1<$(j).attr("href").indexOf(g)&&
$(j).attr({href:g+"&ns="+c})})})},_bindEvent:function(){this.$menus.on("click",function(){var c=$(this).data("index");i.set("ua",c)})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return k});window.js_VXqhXRCKIs&&window.js_VXqhXRCKIs(!0);
